- Cargo.lock
- spki/CHANGELOG.md
- spki/Cargo.toml
- spki/src/lib.rs
> spki v0.4.1

- der/src/length.rs
There are legitimate cryptographic use cases that need to support ASN.1 DER-encoded documents larger than the previous maximum of 1 MiB.
Two notable applications are where messages can be quite large are:
- Certificate Revocation Lists (CRLs)
- Cryptographic Message Syntax (CMS) a.k.a. PKCS#7
This increases the maximum length to something which is hopefully still somewhat conservative but also useful enough for the above applications.
It can be further increased if there is a legitimate use case.
> der: increase `Length::MAX` to 256 MiB

- pem-rfc7468/src/decoder.rs
- pem-rfc7468/src/grammar.rs
- Moves decoding of encapsulated text to an inherent method of `Encapsulation`
- Changes the return type of this method to be the portion of the buffer containing the decoded data
> pem-rfc7468: refactor decoder

- Cargo.lock
- sec1/CHANGELOG.md
- sec1/Cargo.toml
- sec1/src/lib.rs
> sec1 v0.1.0

- der/src/asn1/context_specific.rs
Extracts a `decode_with` function that uses a callback function to implement decoding.
> der: refactor `ContextSpecific` decoder

- .github/workflows/der.yml
- Cargo.lock
- der/Cargo.toml
- der/src/asn1/generalized_time.rs
- der/src/datetime.rs
- der/src/error.rs
- der/src/lib.rs
Impls type conversions to `DateTime` and adds `GeneralizedTime` encoding/decoding impls to `time::PrimitiveDateTime`.
> der: add basic integration with `time` crate

- der/src/asn1/utf8_string.rs
- der/src/tag/number.rs
These can be used in match expressions
> der: add inherent constants for all valid `TagNumber`s

- der/README.md
Mention full list of format crates, and include info about canonicalization checks being performed.
> der: README.md improvements

- der/derive/src/attributes.rs
- der/derive/src/enumerated.rs
- der/derive/src/lib.rs
- der/src/lib.rs
- der/tests/derive.rs
Adds a proc macro for mapping ASN.1 `ENUMERATED` types to a C-like enum.
> der_derive: `Enumerated` custom derive macro

- .github/workflows/tai64.yml
- Cargo.lock
- Cargo.toml
- README.md
- tai64/CHANGELOG.md
- tai64/Cargo.toml
- tai64/LICENSE-APACHE
- tai64/LICENSE-MIT
- tai64/README.md
- tai64/src/lib.rs
Moves the source code for the `tai64` crate into this repository.
History is not preserved
> Import `tai64` crate

- tai64/src/lib.rs
Promotes the following to inherent constants:
- `TAI64_LEN` => `Tai64::BYTE_SIZE`
- `TAI64N_LEN` => `Tai64N::BYTE_SIZE`
- `UNIX_EPOCH_TAI64` => `Tai64::UNIX_EPOCH`
- `UNIX_EPOCH_TAI64N` => `Tai64N::UNIX_EPOCH`
> tai64: make constants inherent

- der/derive/src/choice.rs
- der/derive/src/enumerated.rs
- der/derive/src/sequence.rs
Uses `quote!` interpolations for repeated elements, and builds fields/variants as `Vec<TokenStream>` using `to_*_tokens` methods, rather than having them append to a `TokenStream` body.
This is a more idiomatic way to use `quote!`.
> der_derive: improve `quote!` interpolations

- .github/workflows/pkcs1.yml
- pkcs1/Cargo.toml
- pkcs1/src/pkcs8.rs
- pkcs1/src/private_key.rs
Tests more features on `no_std` targets
> pkcs1: expand CI test combinations

- Cargo.lock
- der/CHANGELOG.md
- der/Cargo.toml
- der/src/lib.rs
- `Any::NULL` constant ([#226])
[#226]: https://github.com/RustCrypto/formats/pull/226
> der v0.5.1

- Cargo.lock
- spki/CHANGELOG.md
- spki/Cargo.toml
- spki/src/lib.rs
- Replace `from_spki` with `TryFrom` ([#231])
[#231]: https://github.com/RustCrypto/formats/pull/231
> spki v0.5.1

- der/README.md
> der: add downloads image to README.md

- base64ct/src/decoder.rs
Adds support for padded variants of Base64 to the stateful `Decoder`
> base64ct: add padding support to `Decoder`

- Cargo.lock
- ssh-key/CHANGELOG.md
- ssh-key/Cargo.toml
- ssh-key/src/lib.rs
> ssh-key v0.1.0

- Cargo.lock
- spki/CHANGELOG.md
- spki/Cargo.toml
- spki/src/lib.rs
- Impl `ValueOrd` for `AlgorithmIdentifier` ([#289])
[#289]: https://github.com/RustCrypto/formats/pull/289
> spki v0.5.3

- base64ct/src/decoder.rs
Adds a mode to the `Decoder` type for decoding Base64 which is wrapped at a specific width.
The internal `BlockBuffer` is used to handle Base64 input blocks which are spread across multiple lines, so any line width greater than 0 is supported. This is important because the OpenSSH private key format linewraps at a width of 70, which is not a multiple of 4.
> base64ct: add `Decoder::new_linewrapped`

- base64ct/src/decoder.rs
This fix uses a similar approach of eagerly unpadding the input Base64 used when handling contiguous unwrapped Base64.
This is probably a naive strategy though: it's possible that the padding might end up getting split over a newline boundary.
A better approach would be to use a padded decoder when processing the last block of input Base64. That would require a bit more work to ensure that the correct Base64 variant is being used given the context.
> base64ct: fix `Decoder` handling of multi-line padded Base64

- ssh-key/src/mpint.rs
- Reject unnecessary leading `0` byte
- Fix tests to reflect that `from_bytes` does not include length prefix
- Add `MPInt::as_positive_bytes` to extract positive numbers
> ssh-key: `MPInt` improvements

- .github/workflows/base16ct.yml
- Cargo.lock
- Cargo.toml
- base16ct/CHANGELOG.md
- base16ct/Cargo.toml
- base16ct/LICENSE-APACHE
- base16ct/LICENSE-MIT
- base16ct/README.md
- base16ct/src/lib.rs
- base16ct/tests/lib.rs
- base64ct/src/errors.rs
- base64ct/src/lib.rs
Constant-time implementation of Base16 (a.k.a. hexadecimal) based on this C++ implementation:
https://github.com/Sc00bz/ConstTimeEncoding/blob/master/hex.cpp
Original C++ is MIT licensed. Relicensed as Apache 2.0+MIT with permission from the original author.
> base16ct: initial crate

- der/derive/src/sequence.rs
Extracts an internal stateful `TokenStream` newtype which handles transforming the AST-in-progress.
In somewhat handwavy MVC terms, if `DeriveSequence` is the "model", and `SequenceField` the controller, then `LowerFieldDecoder` is the view.
This should eventually help with more composable orderings that can better combine different features, however for now it retains many of the shortcomings (and likewise compatibility with) the previous implementation.
> der_derive: extract `LowerFieldDecoder`

- der/README.md
- Updates dependency list
- Updates downstream "reverse dependency" list
- Other small fixups
> der: updates to README.md

- pkcs10/tests/certreq.rs
- x501/src/attr.rs
> Choose a better field name for `Attribute`

- der/derive/src/choice/variant.rs
Adds a full set of unit tests for deriving context-specific `CHOICE` variants which tests all of the parameters which can be specified via attributes.
> der_derive: expand `ChoiceVariant` lowering tests

- der/derive/src/attributes.rs
> der: fix missing format argument

- x509/src/general_name.rs
- x509/tests/pkix_extensions.rs
> x509: derive(Sequence) for OtherName

- x509/src/ext/pkix/name/general.rs
- x509/src/ext/pkix/name/other.rs
- x509/src/lib.rs
> Unconditionally specify no_std

- der/src/lib.rs
> fix(der): export the Newtype derive

- der/src/asn1/set_of.rs
> fix(der): manually impl Default for SetOfVec

- x509/src/lib.rs
> feat(x509): re-export der crate

- const-oid/src/lib.rs
> feat(const-oid): add the AssociatedOid trait

- const-oid/oiddbgen/src/asn1.rs
- const-oid/src/db/gen.rs
> fix(oiddb): improve regex to find more OIDs

- x509/src/request.rs
> feat: add ExtensionReq type

- der/derive/src/newtype.rs
- x509/src/certificate.rs
- x509/src/request.rs
> feat(der): clean up Newtype implementations

- x509/src/attr.rs
- x509/src/ext/pkix/access.rs
- x509/src/ext/pkix/keyusage.rs
- x509/src/ext/pkix/name/dirstr.rs
- x509/src/ext/pkix/name/ediparty.rs
- x509/src/ext/pkix/policymap.rs
> chore(x509): remove unhelpful doc strings

- x509/src/certificate.rs
> feat(x509): add extension query methods to `TbsCertificate`

- x509/src/ext/pkix.rs
- x509/src/ext/pkix/access.rs
- x509/src/ext/pkix/authkeyid.rs
- x509/src/ext/pkix/certpolicy.rs
- x509/src/ext/pkix/constraints/basic.rs
- x509/src/ext/pkix/constraints/name.rs
- x509/src/ext/pkix/constraints/policy.rs
- x509/src/ext/pkix/crl.rs
- x509/src/ext/pkix/crl/dp.rs
- x509/src/ext/pkix/keyusage.rs
- x509/src/ext/pkix/policymap.rs
- x509/tests/pkix_extensions.rs
- x509/tests/trust_anchor_format.rs
> feat(x509): impl AssociatedOid for all extensions

- const-oid/oiddbgen/rfc6960.txt
- const-oid/oiddbgen/src/asn1.rs
- const-oid/oiddbgen/src/main.rs
- const-oid/src/db/gen.rs
> feat(oiddb): add RFC 6960

- x509/tests/pkix_extensions.rs
> chore: clean up extension testing

- x509/src/time.rs
> feat(x509): impl TryFrom<Duration> for Validity

- spki/src/spki.rs
> spki: impl `ValueOrd` for `SubjectPublicKeyInfo`

- crypto-serde/src/lib.rs
Adds static functions which can serialize any `T: AsRef<[u8]>`, which avoids making an intermediate copy unless the underlying format is human-readable.
> crypto-serde: add `serialize_hex_*_or_bin` functions

- crypto-serde/src/slice.rs
Follow-up on #538. I hope this is what you meant.
> crypto-serde: implement slice deserializing with buffer

- Cargo.lock
- serdect/CHANGELOG.md
- serdect/Cargo.toml
> serdect v0.1.0

- ssh-key/src/private.rs
Adds an encryption method which accepts explicit `Cipher` and `Kdf` parameters.
The `PrivateKey::encrypt` method is composed in terms of `encrypt_with`.
> ssh-key: add `PrivateKey::encrypt_with`

- ssh-key/src/checked.rs
Minor simplification to the implementation
> ssh-key: checked sum simplification

- ssh-key/src/private.rs
- ssh-key/src/private/keypair.rs
Factors all code related to privatekey/coment pair handling into the same methods.
Currently specialized to one private key.
> ssh-key: refactor privatekey comment pair handling

- .github/workflows/ssh-key.yml
- .github/workflows/workspace.yml
- Cargo.lock
- ssh-key/Cargo.toml
- ssh-key/README.md
- ssh-key/src/certificate/builder.rs
- ssh-key/src/private.rs
- ssh-key/src/private/ecdsa.rs
- ssh-key/src/public/ecdsa.rs
- ssh-key/src/signature.rs
- ssh-key/tests/certificate_builder.rs
- P-256 key generation support
- P-256 ECDSA signing support
- P-256 ECDSA verification support
> ssh-key: ECDSA/NIST P-256 support

- ssh-key/src/private/rsa.rs
- ssh-key/src/public/rsa.rs
- ssh-key/tests/certificate_builder.rs
Ensures that all RSA keys which are converted to types by the `rsa` crate (a necessary step for signing/verification) meet a minimum size requirement: 2048-bits.
Uses a hardcoded 2048-bit RSA key for certificate verification tests so as to avoid the time it takes to generate a key.
> ssh-key: enforce min RSA key size; remove keygen from tests

- der/src/encoder.rs
Uses a boolean `failed` flag rather than an `Option`.
While this eliminates a modicum of safety around using the `Encoder` after an encoding operation has failed, it drastically simplifies the implementation.
> der: simplify `Encoder` implementation

- .github/workflows/ssh-key.yml
This crate has various `std`-gated features that interact with the filesystem and file permissions, and also platform-gated features.
This commit ensures the crate at least builds on all of these platforms.
> ssh-key: CI build tests for 32-bit Linux, macOS, and Windows

- der/src/reader.rs
Adds a trait-based replacement for `Decoder::sequence` built on `Reader::read_nested` and `NestedReader`.
> der: add `Reader::sequence`

- Cargo.lock
- base32ct/CHANGELOG.md
- base32ct/Cargo.toml
> base32ct v0.1.0

- Cargo.lock
- x509-cert/CHANGELOG.md
- x509-cert/Cargo.toml
- x509-cert/src/lib.rs
- x509-ocsp/Cargo.toml
> x509-cert v0.1.0

- base16ct/Cargo.toml
- base16ct/src/lib.rs
- base64ct/Cargo.toml
- base64ct/src/lib.rs
- const-oid/src/lib.rs
- der/src/lib.rs
- pem-rfc7468/src/lib.rs
- pkcs1/src/lib.rs
- pkcs5/Cargo.toml
- pkcs5/src/lib.rs
- pkcs7/Cargo.toml
- pkcs7/src/lib.rs
- pkcs8/Cargo.toml
- pkcs8/src/lib.rs
- sec1/src/lib.rs
- serdect/src/lib.rs
- spki/src/lib.rs
- ssh-key/src/lib.rs
- tai64/Cargo.toml
- tai64/src/lib.rs
- x509-cert/Cargo.toml
- x509-cert/src/lib.rs
Also makes logo URL consistent across crates.
> Remove html_root_url

- .github/workflows/base16ct.yml
- .github/workflows/base32ct.yml
- .github/workflows/base64ct.yml
- .github/workflows/const-oid.yml
- .github/workflows/der.yml
- .github/workflows/pem-rfc7468.yml
- .github/workflows/pkcs1.yml
- .github/workflows/pkcs5.yml
- .github/workflows/pkcs7.yml
- .github/workflows/pkcs8.yml
- .github/workflows/sec1.yml
- .github/workflows/serdect.yml
- .github/workflows/spki.yml
- .github/workflows/ssh-key.yml
- .github/workflows/tai64.yml
- .github/workflows/tls_codec.yml
- .github/workflows/workspace.yml
- .github/workflows/x509-cert.yml
It might be the reason the cargo index is failing to update which is breaking #682.
> CI: remove caching

- .github/dependabot.yml
Curious if this might help resolve the build failures in #709
> CI: add dependabot configs to update actions

- .github/workflows/base16ct.yml
- .github/workflows/base32ct.yml
- .github/workflows/base64ct.yml
- .github/workflows/const-oid.yml
- .github/workflows/der.yml
- .github/workflows/pem-rfc7468.yml
- .github/workflows/pkcs1.yml
- .github/workflows/pkcs5.yml
- .github/workflows/pkcs7.yml
- .github/workflows/pkcs8.yml
- .github/workflows/sec1.yml
- .github/workflows/serdect.yml
- .github/workflows/spki.yml
- .github/workflows/tai64.yml
- .github/workflows/tls_codec.yml
- .github/workflows/x509-cert.yml
Adds the `github/workflows/*.yml` files as triggers to perform a build, ensuring that changes to workflow configs mean the corresponding workflows run in CI.
> CI: trigger build when workflow config changes

- base64ct/src/alphabet.rs
- base64ct/src/alphabet/shacrypt.rs
- base64ct/src/lib.rs
- base64ct/tests/shacrypt.rs
This replaces #738.  It is minimally invasive.
> Add sha2-style base64 crypt format

- Cargo.lock
- Cargo.toml
- pkcs12/CHANGELOG.md
- pkcs12/Cargo.toml
- pkcs12/LICENSE-APACHE
- pkcs12/LICENSE-MIT
- pkcs12/README.md
- pkcs12/src/lib.rs
Initial boilerplate for a PKCS#12 crate
> pkcs12: initial crate

- x509-cert/src/crl.rs
This caused highlighting errors in my editor.
> x509-cert: crl fixup comment

- .github/workflows/const-oid.yml
- .github/workflows/der.yml
- .github/workflows/pkcs1.yml
- .github/workflows/pkcs5.yml
- .github/workflows/pkcs7.yml
- .github/workflows/pkcs8.yml
- .github/workflows/sec1.yml
- .github/workflows/spki.yml
- .github/workflows/workspace.yml
- .github/workflows/x509-cert.yml
- spki/Cargo.toml
- spki/src/spki.rs
- spki/tests/spki.rs
> chore(spki): don't enable base64ct implicitly from alloc feature

- der/src/asn1/octet_string.rs
This is just a small API addition, designed to help with the (unfortunately) common case of DER nested within `OCTET STRING` slices.
This is effectively just a shorthand for `T::from_der(o.as_bytes())` for `T: Decode`.
(If this change isn't desired, please feel free to close!)
> asn1/octet_string: add `OctetStringRef::decode_into`

- pkcs7/src/cms_version.rs
- pkcs7/src/signer_info.rs
> pkcs7: add `ValueOrd` impls

- der/src/asn1.rs
Small cleanups to imports in the `asn1` module
> der: import cleanups

- Cargo.lock
- base16ct/CHANGELOG.md
- base16ct/Cargo.toml
- sec1/Cargo.toml
- serdect/Cargo.toml
> base16ct v0.2.0

- Cargo.lock
- der/CHANGELOG.md
- der/Cargo.toml
- Make `zeroize`'s `alloc` feature conditional ([#920])
[#920]: https://github.com/RustCrypto/formats/pull/920
> der v0.7.1

- Cargo.lock
- cmpv2/README.md
- cms/README.md
- crmf/README.md
- x509-ocsp/README.md
- Fixes incorrect MSRVs
- Use buildstats.info badges correctly
> README.md(s): fix badges

- pkcs7/src/content_info.rs
> pkcs7: avoid code duplication

- Cargo.lock
- cms/CHANGELOG.md
- cms/Cargo.toml
- crmf/Cargo.toml
> cms v0.2.0

- Cargo.lock
- const-oid/oiddbgen/Cargo.toml
- der/derive/Cargo.toml
- der/derive/src/attributes.rs
- der/derive/src/enumerated.rs
- der/derive/src/tag.rs
- der/src/datetime.rs
- der/src/tag/mode.rs
- tls_codec/derive/Cargo.toml
- tls_codec/derive/src/lib.rs
- x509-cert/src/anchor.rs
Additionally has a commit with some clippy fixes, I can drop it if you don't like them.
> Updates to syn-2

- x509-cert/src/attr.rs
- x509-cert/src/name.rs
Adds `FromStr` impls for the following types:
- `RdnSequence`
- `RelativeDistingiushedName`
- `AttributeTypeAndValue`
All of these types have `encode_from_string` methods which would parse the string and serialize the resulting type as a DER byte vector.
The `encode_from_string` methods now call the relevant `FromStr` impls.
> x509-cert: add `FromStr` impls for name-related functionality

- pkcs1/src/params.rs
Export default RSA PSS salt length.
> pkcs1: export RSAPSS_SALT_LEN_DEFAULT

- spki/src/traits.rs
There is a possibility that creating the AlgorithmIdentifier results in the Error. Change corresponding methods to return
Result<AlgorithmIdentifier>.
> spki: use Result for Dyn*AlgorithmIdentifier traits

- sec1/src/point.rs
> sec1: impl `ModulusSize` for `U24`

- pkcs1/CHANGELOG.md
- pkcs1/Cargo.toml
- Import failure ([#1021])
[#1021]: https://github.com/RustCrypto/formats/pull/1021
> pkcs1 v0.7.5

- Cargo.lock
- der/CHANGELOG.md
- der/Cargo.toml
Added
- adds support for `DateTime::INFINITY` (#1026)
> der: v0.7.5

- Cargo.lock
- x509-cert/CHANGELOG.md
- x509-cert/Cargo.toml
Got a bit excited with #1040 and pressed merge too early.
> x509-cert: v0.2.2

- der/src/asn1/ia5_string.rs
- der/src/asn1/printable_string.rs
- der/src/asn1/teletex_string.rs
- der/src/str_owned.rs
> Implement TryFrom<String> for strings based on StrOwned.

- gss-api/Cargo.toml
- gss-api/README.md
- Add "About" section to README.md with an overview of GSS-API
- Fix links in README.md
> gss-api: expand and improve documentation

- Cargo.lock
- gss-api/CHANGELOG.md
- gss-api/Cargo.toml
> gss-api v0.1.0

- Cargo.lock
- cmpv2/Cargo.toml
- crmf/CHANGELOG.md
- crmf/Cargo.toml
- crmf/LICENSE-APACHE
- crmf/LICENSE-MIT
> crmf v0.2.0

- Cargo.lock
- cmpv2/CHANGELOG.md
- cmpv2/Cargo.toml
- cmpv2/LICENSE-APACHE
- cmpv2/LICENSE-MIT
- x509-tsp/Cargo.toml
> cmpv2 v0.2.0

- x509-tsp/CHANGELOG.md
- x509-tsp/Cargo.toml
- x509-tsp/LICENSE-APACHE
- x509-tsp/LICENSE-MIT
> x509-tsp v0.1.0

- Cargo.lock
- der/CHANGELOG.md
- der/Cargo.toml
- `TryFrom<String>` impl for strings based on `StrOwned` ([#1064])
[#1064]: https://github.com/RustCrypto/formats/pull/1064
> der v0.7.7

- x509-cert/src/builder.rs
- x509-cert/src/request.rs
- x509-cert/test-support/src/openssl.rs
- x509-cert/tests/builder.rs
> x509-cert: adds `add_attribute` to `RequestBuilder`

- Cargo.lock
- base64ct/Cargo.toml
- x509-cert/test-support/Cargo.toml
> x509-cert: relax dependencies

- .github/workflows/cms.yml
- .github/workflows/pkcs12.yml
- .github/workflows/pkcs7.yml
- .github/workflows/x509-ocsp.yml
- .github/workflows/x509-tsp.yml
see: https://github.com/RustCrypto/actions/commit/2468f28fecbbae1206b019bcc220883fabd2ed34
> ci: follow changes made in RustCrypto/actions

- const-oid/oiddbgen/Cargo.lock
- const-oid/oiddbgen/rfc2985.txt
- const-oid/oiddbgen/src/main.rs
- const-oid/src/db/gen.rs
Beside others, this PR adds the OID for challenge passwords used in SCEP.
> const-oid: Added RFC 2985 for PKCS #9.

- Cargo.lock
- spki/CHANGELOG.md
- spki/Cargo.toml
Added:
- public key to `SubjectPublicKeyInfoOwned` helper (#1269)
> spki: v0.7.3

- Cargo.lock
- const-oid/CHANGELOG.md
- const-oid/Cargo.toml
> const-oid: 0.9.6

- Cargo.lock
- x509-ocsp/CHANGELOG.md
- x509-ocsp/Cargo.toml
- x509-ocsp/LICENSE-APACHE
- x509-ocsp/LICENSE-MIT
> x509-ocsp v0.2.0

- Cargo.lock
- pkcs12/CHANGELOG.md
- pkcs12/Cargo.toml
> pkcs12 v0.1.0

- tls_codec/src/lib.rs
- tls_codec/src/primitives.rs
- tls_codec/src/tls_vec.rs
- tls_codec/tests/decode.rs
- tls_codec/tests/decode_bytes.rs
- tls_codec/tests/encode.rs
- tls_codec/tests/encode_bytes.rs
> tls_codec: implement `U24`

- Cargo.lock
- der/Cargo.toml
- pkcs1/Cargo.toml
- pkcs5/Cargo.toml
- pkcs8/Cargo.toml
- sec1/Cargo.toml
- spki/Cargo.toml
Unfortunately #1310 didn't actually bump the version
> der v0.8.0-pre.0 redux

- Cargo.lock
- x509-ocsp/CHANGELOG.md
- x509-ocsp/Cargo.toml
- Builder ([#1259])
[#1259]: https://github.com/RustCrypto/formats/pull/1259
> x509-ocsp v0.2.1

- der/src/asn1/teletex_string.rs
Adds a citation for the quote from the ASN.1 mailing list
> der: improve `TeletexStringRef` docs

- const-oid/oiddbgen/src/main.rs
- const-oid/oiddbgen/tcg-tpm.md
- const-oid/src/db/gen.rs
All those OIDs are defined inline of various specs scattered in PDFs available on https://trustedcomputinggroup.org
> const-oid: add TPM related OIDs

- der/src/document.rs
This signature was missed in #1055
> der: fixup windows `write_secret_file` helper

- Cargo.lock
- base32ct/Cargo.toml
- base32ct/tests/proptests.rs
> chore(deps): bump base32 from 0.4.0 to 0.5.0

- x509-cert/src/builder/profile/cabf.rs
The `check_names_encoding` check did not allow for extraneous components. This rework the logic to allow that.
> x509-cert: rework the check for ordering of name

- cms/src/builder.rs
- cms/tests/builder.rs
> cms: implement a SignedDataBuilder for PSS

- cms/Cargo.toml
> cms: remove `pem` feature

- x509-cert/src/builder.rs
- x509-cert/src/request.rs
- x509-cert/src/request/builder.rs
See https://github.com/RustCrypto/formats/issues/1577
> x509-cert: move CSR builder to x509_cert::request

- tls_codec/src/primitives.rs
Implement all relevant traits for `Box<T>` as long as T implements the respective trait.
> tls_codec: implement traits for Box<T>

- tls_codec/derive/LICENSE-APACHE
- tls_codec/derive/LICENSE-MIT
> tls_codec: license files for derive crate

- sec1/src/point.rs
Instead of `impl_modulus_size!` for a number of types, impl `ModulusSize` for all types. This is useful for testing, see https://github.com/RustCrypto/formats/pull/1649
Note: the bound `UntaggedPointSize: Add<U1, Output = Self::UncompressedPointSize>` caused issues because there's another bound with `Output = Self::UncompressedPointSize`, and I don't think Rust's type system allows one to assert that two associated types are equal.
Removing that bound did not cause compilation issues, but it left the tag size unconstrained. So instead I added the `Add<U1, Output = Self::CompressedPointSize>` bound on `ModulusSize` itself.
> sec1: blanket impl ModulusSize for all typenums

- pkcs5/src/pbes2/encryption.rs
> pkcs5: fixup `cbc_decrypt` error

- der/src/asn1/set_of.rs
> der: Remove Decode<'a> bound in set_of.rs

- der/src/asn1/any.rs
- der/src/bytes_ref.rs
- der/src/error.rs
- der/src/length.rs
> der: add const ::new to Length, BytesRef, AnyRef

- der/src/asn1/context_specific.rs
Only tests. Useful for future Implicit/Explicit split.
> der: add test for ContextSpecificRef

- der/CHANGELOG.md
> der: 0.7.10 changelog entry

- x509-cert/test-support/src/zlint.rs
> x509-cert: fix test: stuck zlint stdout reader

- base64ct/src/decoder.rs
- base64ct/src/encoder.rs
- base64ct/src/test_vectors.rs
> base64ct: cargo fmt

- der/src/reader/slice.rs
```
Before:
2241 (3.7%,  8.6%)    12 (0.9%,  2.5%)  <der::reader::slice::SliceReader as der::reader::Reader>::read_nested
After:
1639 (2.8%, 14.7%)    12 (0.9%, 10.0%)  <der::reader::slice::SliceReader as der::reader::Reader>::read_nested
```
> der: reduce llvm-ir in `SliceReader::read_nested`

- der/src/tag.rs
Fixes #1237
Constructed bit is compared last.
> der: fix X.680 tag order: compare class and number first

- der/src/tag.rs
> der: fix `Tag::peek` for 6-byte and 7+ byte tags

- der/tests/datetime.proptest-regressions
> der: add DateTime leap year proptest-regressions

- Cargo.toml
Fixes #1848 which did not remove the workspace.excludes
> reunite workspace

- .github/workflows/der.yml
Removes `arbitrary` and `std` from the feature powerset, testing them separately
> der: CI performance improvements

- der/src/encoding_rules.rs
- der/src/error.rs
Helpful for dynamically choosing between BER and DER
> der: string conversions for `EncodingRules`

- Cargo.lock
- cmpv2/Cargo.toml
- cms/Cargo.toml
- crmf/Cargo.toml
- der/Cargo.toml
- gss-api/Cargo.toml
- pkcs1/Cargo.toml
- pkcs12/Cargo.toml
- pkcs5/Cargo.toml
- pkcs8/Cargo.toml
- sec1/Cargo.toml
- spki/Cargo.toml
- x509-cert/Cargo.toml
- x509-ocsp/Cargo.toml
- x509-tsp/Cargo.toml
This release notably includes some breaking changes to error handling and is not compatible with previous RCs
> der v0.8.0-rc.6

- Cargo.lock
- x509-cert/Cargo.toml
> x509-cert v0.3.0-rc.1

- spki/benches/mod.rs
`cargo bench -p spki -F alloc`
> spki: bench `SubjectPublicKeyInfoRef`

- cms/src/signed_data.rs
> cms: relax From certificate for SignerIdentifier to accept a reference

- x509-cert/src/builder/profile/cabf.rs
> x509-cert: update cabf BR to latest revision

- pkcs1/src/params.rs
> pkcs1: correct typo in params.rs

- .github/workflows/base16ct.yml
- .github/workflows/base32ct.yml
- .github/workflows/base64ct.yml
- .github/workflows/cmpv2.yml
- .github/workflows/cms.yml
- .github/workflows/const-oid.yml
- .github/workflows/crmf.yml
- .github/workflows/der.yml
- .github/workflows/gss-api.yml
- .github/workflows/pem-rfc7468.yml
- .github/workflows/pkcs1.yml
- .github/workflows/pkcs12.yml
- .github/workflows/pkcs5.yml
- .github/workflows/pkcs8.yml
- .github/workflows/sec1.yml
- .github/workflows/serdect.yml
- .github/workflows/spki.yml
- .github/workflows/tai64.yml
- .github/workflows/tls_codec.yml
- .github/workflows/workspace.yml
- .github/workflows/x509-cert.yml
- .github/workflows/x509-ocsp.yml
- .github/workflows/x509-tsp.yml
Same as https://github.com/RustCrypto/traits/pull/1948.
> Only run CI on latest commit of PR branches.
