Cargo.lock, base64ct/CHANGELOG.md, base64ct/Cargo.toml, base64ct/src/lib.rs
- Moved to `formats` repo; MSRV 1.51+ ([#2])
=> base64ct v1.1.0

Cargo.lock, const-oid/CHANGELOG.md, const-oid/Cargo.toml, const-oid/README.md, const-oid/src/lib.rs
=> const-oid v0.6.1

Cargo.lock, der/derive/CHANGELOG.md, der/derive/Cargo.toml, der/derive/README.md, der/src/lib.rs
=> der_derive v0.4.1

Cargo.lock, const-oid/CHANGELOG.md, der/CHANGELOG.md, der/Cargo.toml, der/derive/CHANGELOG.md, der/src/lib.rs
- ASN.1 `SET` type now flagged with the constructed bit
=> der v0.4.2

Cargo.lock, pkcs1/CHANGELOG.md, pkcs1/Cargo.toml, pkcs1/README.md, pkcs1/src/lib.rs
=> pkcs1 v0.2.4

Cargo.lock, pkcs5/CHANGELOG.md, pkcs5/Cargo.toml, pkcs5/src/lib.rs
- `3des` and `des-insecure` features
- `sha1` feature
- Support for AES-192-CBC
=> pkcs5 v0.3.2

Cargo.lock, pkcs8/CHANGELOG.md, pkcs8/Cargo.toml, pkcs8/src/lib.rs
- `3des` and `des-insecure` features
- `sha1` feature
- Support for AES-192-CBC
=> pkcs8 v0.7.6

.gitignore, pem-rfc7468/src/decoder.rs, pem-rfc7468/tests/decode.rs
Missed in PR https://github.com/RustCrypto/formats/pull/13
- add test coverage for new cases
- refactor out decoding of encapsulated text
- compromise here on estimating buffer size
- slightly more overestimation, due to counting whitespace
- faster due to no two-pass
- required to ensure that we attempt a base64 decode of the first line
before chopping the second line
=> detect PEM headers in decode_vec

pem-rfc7468/src/decoder.rs, pem-rfc7468/src/error.rs, pem-rfc7468/tests/decode.rs
It was previously `Error::HeaderDetected`, however that doesn't really indicate why it's an error.
The new error message notes that headers are explicitly disallowed in the RFC7468 interpretation of PEM.
cc @dwhjames
=> pem-rfc7468: rename `Error::HeaderDisallowed`

pem-rfc7468/src/decoder.rs, pem-rfc7468/src/lib.rs, pem-rfc7468/tests/decode.rs
Decode the encapsulation boundaries of a PEM document, returning the label.
The motivation is to capture the document label in the case of an error
(by repeating the decoding only to extract the label)
=> Add pem_rfc7468::decode_label

Cargo.lock, pem-rfc7468/CHANGELOG.md, pem-rfc7468/Cargo.toml, pem-rfc7468/src/decoder.rs, pem-rfc7468/src/lib.rs
- `decode_label` ([#22])
- `Error::HeaderDisallowed` ([#13], [#19], [#21])
[#13]: https://github.com/RustCrypto/formats/pull/13
[#19]: https://github.com/RustCrypto/formats/pull/19
[#21]: https://github.com/RustCrypto/formats/pull/21
[#22]: https://github.com/RustCrypto/formats/pull/22
=> pem-rfc7468 v0.2.1

pkcs5/src/pbes2/encryption.rs
Removes support for encrypting keys using 56-bit DES, which is trivially broken due to its small key size.
This functionality is already gated under the off-by-default `des-insecure` feature, however there is little reason why anyone should be encrypting DES keys today, and is a potential sharp edge if someone accidentally configure this setting.
=> pkcs5: remove DES encryption support

Cargo.lock, der/CHANGELOG.md, der/Cargo.toml, der/src/lib.rs
- `Tag::unexpected_error` ([#33])
[#33]: https://github.com/RustCrypto/formats/pull/33
=> der v0.4.3

sec1/src/error.rs, sec1/src/private_key/document.rs, sec1/src/traits.rs
Replaces some trait methods with `TryFrom`, and adds a `TryFrom<EcPrivateKey>` bound to `FromEcPrivateKey`.
=> sec1: better leverage `TryFrom`

pem-rfc7468/src/decoder.rs, pem-rfc7468/src/error.rs, pem-rfc7468/src/grammar.rs, pem-rfc7468/tests/decode.rs, pem-rfc7468/tests/examples/pkcs1_with_preceeding_junk.pem
I pushed another commit on top of #29 which simplifies the decoder cc @dwhjames
=> Allow for data before PEM (RFC 7468) encapsulation boundary

.github/workflows/workspace.yml, der/Cargo.toml, der/derive/src/choice.rs, der/derive/src/lib.rs, der/src/asn1/integer/int.rs, der/src/asn1/integer/uint.rs, pkcs5/src/pbes2/encryption.rs, pkcs8/src/encrypted_private_key_info.rs
Uses the latest stable version of clippy
Fixes the warnings which occur under it
=> Bump clippy to use Rust 1.55

Cargo.lock, pem-rfc7468/CHANGELOG.md, pem-rfc7468/Cargo.toml, pem-rfc7468/src/lib.rs
- Allow for data before PEM encapsulation boundary ([#40])
[#40]: https://github.com/RustCrypto/formats/pull/40
=> pem-rfc7468 v0.2.2

.github/workflows/pkcs8.yml, .github/workflows/sec1.yml, Cargo.lock, sec1/Cargo.toml, sec1/src/error.rs, sec1/src/lib.rs, sec1/src/point.rs, sec1/src/private_key/document.rs
Adds support for encoding elliptic curve points according to the following algorithms defined in SEC1:
- `Elliptic-Curve-Point-to-Octet-String`
- `Octet-String-to-Elliptic-Curve-Point`
These encodings use a tag byte (0x02/0x03 for compressed, 0x04 for uncompressed) followed by one or two big endian-serialized field elements representing the x/y coordinates of a curve point.
This is an extraction of the implementation from the `elliptic-curve` crate, decoupled from the types in that crate and thus generally useful for any crate which wishes to implement SEC1 support.
=> sec1: `Elliptic-Curve-Point-to-Octet-String` encoding

sec1/src/point.rs
The derived versions aren't working because they are attempting to compare values on the generic typenum, which doesn't impl the proper traits to allow the derive to work.
=> sec1: use manual impl of `(Partial)Eq` on EncodedPoint

sec1/src/point.rs, sec1/src/private_key.rs
The derived versions aren't working because they are attempting to compare values on the generic typenum, which doesn't impl the proper traits to allow the derive to work.
=> sec1: use manual impl of `(Partial)Ord` on EncodedPoint

README.md, sec1/README.md
Adds the `sec1` crate to the table in the toplevel README.md
=> README.md: add `sec1` crate

der/src/asn1/any.rs, der/src/asn1/bit_string.rs, der/src/asn1/context_specific.rs, der/src/asn1/octet_string.rs, pkcs8/src/private_key_info.rs, sec1/src/private_key.rs
This is a prerequisite for supporting IMPLICIT BIT STRING values, which can be prefixed by any e.g. CONTEXT SPECIFIC tag.
See also: #55
=> der: generalize leading octet support for `Any`

der/src/asn1/any.rs, der/src/asn1/context_specific.rs, der/src/asn1/octet_string.rs, der/src/decoder.rs, der/src/encoder.rs, der/src/error.rs, der/src/lib.rs, der/src/tag.rs, der/src/tag/class.rs, der/src/tag/mode.rs, der/src/tag/number.rs, pkcs8/src/private_key_info.rs, sec1/src/private_key.rs
Adds preliminary support for `IMPLICIT`, splitting `Decoder::context_specific` into separate `_explicit` and `_implicit`
versions.
Two functions are necessary for now because they have different trait bounds, and furthermore, support for `IMPLICIT` fields is highly restricted for now: it requires an `Into<Any>` bound.
Some refactoring of the encoding traits will be necessary to support more types.
=> der: add support for IMPLICIT mode CONTEXT-SPECIFIC

Cargo.lock, der/Cargo.toml, pkcs1/Cargo.toml, pkcs5/Cargo.toml, pkcs8/Cargo.toml, sec1/Cargo.toml, spki/Cargo.toml, x509/Cargo.toml
RustCrypto/formats#61 contained breaking changes to the public API.
As such, this commit bumps `der` and all of the crates which depend on it to prerelease versions to reflect that
=> Bump `der`-dependent crates to prerelease versions

der/src/asn1/context_specific.rs, der/src/decoder.rs
Factors the methods for decoding context specific types into the `context_specific` module.
=> der: factor context specific methods into relevant module

der/src/asn1/generalized_time.rs, der/src/asn1/utc_time.rs, der/src/datetime.rs, der/src/error.rs, der/src/lib.rs
Debatably we should switch to something like `chrono`, but since we have a rich built-in `no_std`-friendly date-and-time type we might as well expose it.
=> der: expose `DateTime` through public API

pkcs5/src/error.rs, pkcs5/src/lib.rs, pkcs5/src/pbes1.rs, pkcs5/src/pbes2.rs, pkcs5/src/pbes2/encryption.rs, pkcs5/src/pbes2/kdf.rs
- introduce Error enum with one and only existing error value
- introduce specialized Result type for crate
- rewrite references to der crate Error & Result types
=> Refactor Error and Result usage for pkcs5 crate

der/src/asn1/sequence.rs
Removes a `Copy` bound from the `SEQUENCE OF` decoder bound on `[T; N]`
=> der: improve `SEQUENCE OF` bounds

der/src/asn1/set_of.rs
None of these are necessary as the relevant lifetimes are in-scope. They also make the bounds overly general such that types unexpectedly won't receive impls.
It seems like they were leftover from refactoring but never properly removed. This commit removes them.
=> der: remove `SetOf*` HRTBs

der/src/arrayvec.rs, der/src/asn1.rs, der/src/asn1/sequence.rs, der/src/asn1/set_of.rs, der/src/lib.rs
Adds a type for `SequenceOf`, backed by the internal `ArrayVec` type.
This allows for array-backed storage of an ASN.1 SEQUENCE OF, where the array size acts as a maximum, rather than an exact length requirement.
Support for modeling `[T; N]` as a SEQUENCE OF is retained, and now implemented using `SequenceOf` to handle decoding.
=> der: add `SequenceOf` type

der/src/asn1/sequence.rs, der/src/lib.rs
Allows using a `Vec` to represent a `SEQUENCE OF`.
=> der: `SEQUENCE OF` support for `Vec`

.github/workflows/pkcs8.yml, pkcs8/src/document/private_key.rs, pkcs8/src/document/public_key.rs, pkcs8/src/traits.rs, pkcs8/tests/private_key.rs, pkcs8/tests/public_key.rs
These types previously had similarly "shaped" inherent methods.
This commit impls the traits instead, providing a common API, and better consistency with the `pkcs1` and `sec1` crates which work this way.
=> pkcs8: impl `From*Key`/`To*Key` traits on `Document` types

pkcs1/src/lib.rs
Note that PEM-encoded keys must follow a strict interpretation outlined in RFC7468 and can't include things like "headers".
Closes #112
=> pkcs1: add note about RFC7468 PEM encoding

.github/workflows/der.yml, .github/workflows/spki.yml, Cargo.lock, der/Cargo.toml, der/src/asn1/generalized_time.rs, der/src/decoder.rs, der/src/document.rs, der/src/error.rs, der/src/lib.rs, pem-rfc7468/src/lib.rs, pkcs1/Cargo.toml, pkcs1/src/public_key/document.rs, pkcs1/src/traits.rs, pkcs1/tests/public_key.rs, spki/Cargo.toml, spki/src/lib.rs, spki/src/spki.rs
Adds a trait for representing ASN.1 DER-encoded documents, including generalized support for PEM encoding as well as reading/writing such documents from/to the underlying filesystem.
The intended usage is to DRY out the `*Document` types that exist in the `pkcs1`, `pkcs8`, and `sec1` crates.
As a prototype/POC, this commit also impls the trait for `RsaPublicKey` in the `pkcs1` crate. The rest are left as a followup exercise.
=> der: add `Document` trait

.github/workflows/spki.yml, Cargo.lock, der/src/document.rs, der/src/error.rs, der/src/lib.rs, pkcs1/Cargo.toml, pkcs1/src/error.rs, pkcs1/src/lib.rs, pkcs8/Cargo.toml, pkcs8/src/document.rs, pkcs8/src/document/encrypted_private_key.rs, pkcs8/src/encrypted_private_key_info.rs, pkcs8/src/error.rs, pkcs8/src/lib.rs, pkcs8/src/private_key_info.rs, pkcs8/src/traits.rs, sec1/Cargo.toml, sec1/src/error.rs, sec1/src/lib.rs, spki/Cargo.toml, spki/src/document.rs, spki/src/lib.rs, spki/src/spki.rs, spki/src/traits.rs, spki/tests/examples/ed25519-pub.pem, spki/tests/spki.rs
This type provides heap-backed storage for `SubjectPublicKeyInfo`.
It was placed in the `pkcs8` crate instead of the `spki` crate because that's where PEM support used to live.
Now that PEM support has been extracted into the `pem-rfc7468` crate, this type can move to the `spki` crate.
To provide backwards compatibility, it's re-exported from the `pkcs8` crate (where it's effectively the associated "public key type").
=> spki: move `PublicKeyDocument` from `pkcs8` crate

pkcs8/src/lib.rs, pkcs8/tests/public_key.rs, spki/src/document.rs, spki/src/lib.rs, spki/src/traits.rs, spki/tests/spki.rs
Renames the traits for decoding/encoding SPKI public keys, emphasizing that they're encoding related and not just `From/`To` conversions.
=> spki: rename `From/ToPublicKey` => `DecodePublicKey`/`EncodePublicKey`

der/src/document.rs, pkcs1/src/lib.rs, pkcs1/src/private_key/document.rs, pkcs1/src/public_key/document.rs, pkcs1/src/traits.rs, pkcs8/src/traits.rs, spki/src/traits.rs
Following suit with the changes to the `spki` crate in #119, renames the traits for decoding/encoding RSA keys, emphasizing that they're encoding-related and not just `From/`To` conversions.
=> pkcs1: rename `From/ToRsa*Key` => `DecodeRsa*Key`/`EncodeRsa*Key`

pkcs1/src/traits.rs, pkcs8/src/document/private_key.rs, pkcs8/src/lib.rs, pkcs8/src/traits.rs, pkcs8/tests/private_key.rs
Following suit with the changes to the `spki` and `pkcs1` crates in #119 and #120, renames the traits for decoding/encoding PKCS#8 private keys, emphasizing that they're encoding-related and not just `From/`To` conversions.
=> pkcs8: rename `From/ToPrivateKey` => `DecodePrivateKey`/`EncodePrivateKey`

Cargo.lock, sec1/Cargo.toml, sec1/src/lib.rs, sec1/src/private_key/document.rs, sec1/src/traits.rs
Following suit with the changes in #119, #120, and #121, renames the traits for decoding/encoding SEC1 private keys, emphasizing that they're encoding-related and not just `From/`To` conversions.
=> sec1: rename `From/ToEcPrivateKey` => `DecodeEcPrivateKey`/`EncodeEcPrivateKey`

.github/workflows/der.yml, der/src/document.rs, pkcs1/src/public_key/document.rs
When persisting `der::Document` as either DER or PEM, and the document contains a secret (e.g. cryptographic key), this commit adds support for using hardened file permissions on Unix platforms to prevent accidental leakage to other users on the same host.
The `pkcs1`, `pkcs8`, and `sec1` crates already use such permissions, however this change allows the file permission handling to be implemented in a single place, so adding support for hardened permissions on other OSes (Windows would be desirable) can happen in a single location.
The aforementioned crates have not yet been updated to use this new API, but it is at least now possible.
=> der: add support for hardened `Document` file permissions

Cargo.lock, der/Cargo.toml, der/src/asn1/utc_time.rs, der/src/datetime.rs, der/tests/datetime.proptest-regressions, der/tests/datetime.rs
Using `proptest` provides both a greater breadth of tested inputs as well as better performance, since the old tests were effectively brute force testing a set of valid inputs, whereas proptest generates randomized test cases instead.
=> der: use `proptest` for `DateTime`/`UtcTime` tests

pkcs1/src/private_key/document.rs, sec1/src/private_key.rs, sec1/src/private_key/document.rs, sec1/src/traits.rs, sec1/tests/private_key.rs
Uses the new `Document` trait to impl `EcPrivateKeyDocument`, including the newly added support for hardened file permissions gated on the associated `const SENSITIVE: bool = true`.
=> sec1: use `der::Document` to impl `EcPrivateKeyDocument`

der/src/tag.rs
Support for the ASN.1 `ENUMERATED` universal tag.
This doesn't yet include support for e.g. mapping `ENUMERATED` to enums. Future work here might involve adding an `Enumerated` trait similar to `Choice`, along with custom derive support, which could be applied to a C-like enum where each variant maps to an integer value.
=> der: add `Tag::Enumerated`

der/derive/src/choice.rs, der/src/error.rs, der/src/tag.rs, der/src/tag/mode.rs, der/src/tag/number.rs
Renames the following to emphasize the `Tag` on the beginning of the variant name instead of the end:
- `ErrorKind::UnknownTagMode` => `ErrorKind::TagModeUnknown`
- `ErrorKind::UnexpectedTag` => `ErrorKind::TagUnexpected`
- `ErrorKind::UnknownTag` => `ErrorKind::TagUnknown`
=> der: rename `ErrorKind::Tag*`

der/src/error.rs, der/src/tag/number.rs
Handles the specific case that the lower 5-bits of a tag are all `1`.
This is a bit different from the `ErrorKind::TagUnknown` previously used, in that it specifically related to an unsupported BER encoding.
=> der: add `ErrorKind::TagNumberInvalid`

der/src/arrayvec.rs, der/src/encodable.rs, der/src/error.rs, der/src/length.rs
The latter was used for encoding errors and the former for decoding errors, but really the error types have the same "shape" and there's no need for separate variants for encoding/decoding, since there's no way they could get confused.
=> der: consolidate `ErrorKind::{Incomplete, Underlength}`

pkcs1/src/error.rs, pkcs1/src/private_key.rs, pkcs1/src/public_key.rs, pkcs1/src/public_key/document.rs, pkcs8/src/error.rs, pkcs8/src/private_key_info.rs, sec1/src/error.rs
Removes error variants like `FileNotFound` and `PermissionDenied` from the `pkcs1`, `pkcs8`, and `sec1` crates, now that these concerns are encapsulated by `der::Document`.
=> Remove I/O related errors from key format crates

der/src/encoder.rs
This commit adds a type hint for a `Length` that is being TryInto'd a
usize. I'm not sure what causes this failure, but this seems to be a
bandaid fix.
Closes https://github.com/RustCrypto/formats/issues/146
=> Add type hint in `der` encoder `sequence` method

der/src/tag.rs
These are used by X.509's `DisplayText` as defined in RFC5280.
See also: #154
=> der: add `Tag::VisibleString` and `Tag::BmpString`

der/src/asn1/context_specific.rs
This needlessly constrains the types which are possible to implicitly tag inside of a `ContextSpecific`.
Unfortunately this removes the canonicalization check on the constructed bit as well, however there are other ways it could potentially be added, such as adding a `const CONSTRUCTED: bool` field to `DecodeValue`.
=> der: remove `Tagged` bound on `ContextSpecific::decode_implicit`

der/src/error.rs
It appears to be entirely vistigial at this point
=> der: remove `ErrorKind::DuplicateField`

der/derive/src/attributes.rs, der/derive/src/choice.rs, der/derive/src/lib.rs, der/derive/src/sequence.rs, der/derive/src/tag.rs, der/derive/src/types.rs, der/src/asn1/utf8_string.rs, der/src/encoder.rs, der/tests/derive.rs, pkcs7/src/content_info.rs
Adds backend support for implicitly tagged variants of a `Choice`.
=> der_derive: implement `tag_mode = "implicit"` attribute

der/derive/src/lib.rs
Prints out a slightly friendlier error messages when deriving `Choice` on non-enums or `Sequence` on non-structs.
=> der_derive: improve diagnostics for type/trait mismatches

der/derive/src/attributes.rs, der/derive/src/choice.rs, der/derive/src/tag.rs, der/tests/derive.rs
The custom derive support for `IMPLICIT`-ly tagged context-specific fields was previously incomplete and didn't work correctly.
This commit finishes basic end-to-end support for both decoding and encoding and adds an initial integration test.
=> der: finish deriving context-specific `Choice`; add tests

der/src/lib.rs, der/tests/derive.rs
Adds integration tests based on the X.509 test cases covered in the documentation.
=> der_derive: add integration tests for `Sequence` macro

der/derive/src/choice.rs, x509/src/time.rs
Previously the custom derive for `Choice` would also write `From` impls for each of the variants, which would convert the inner type into a particular variant of the enum. This used to be an integral part of the `Decode` impl, but is no longer.
This is problematic because it means no two variants can have the same inner type. This commit gets rid of these derives since they're no longer needed for decoding and have this limitation.
=> der_derive: don't automatically derive `From` impls for `Choice`

der/src/asn1/integer.rs
These were commented out during the `DecodeValue`/`EncodeValue` refactor and the commented out code not up-to-date.
=> der: restore `INTEGER` canonicalization checks

README.md, pkcs7/Cargo.toml, pkcs7/README.md, pkcs7/src/content_info.rs, pkcs7/src/data_content.rs, pkcs7/src/encrypted_data_content.rs, pkcs7/src/enveloped_data_content.rs, pkcs8/README.md
- Replace outdated references to RFC 2315 with references to RFC 5652 and RFC 8933
- Add `pkcs7` crate to the toplevel table
=> pkcs7: doc fixups

const-oid/src/encoder.rs, const-oid/src/lib.rs, der/src/asn1/oid.rs
Renames the `MAX_LENGTH` field to `MAX_SIZE` for consistency with other usages of "size" within the RustCrypto project.
Bumps it to 31 as we've encountered some real-world PKIX OIDs which are excessively large.
=> const-oid: rename `MAX_LENGTH` to `MAX_SIZE`; bump to 31

Cargo.lock, base64ct/CHANGELOG.md, base64ct/Cargo.toml, base64ct/src/lib.rs, pem-rfc7468/Cargo.toml, spki/Cargo.toml
- Benchmarks ([#135])
[#135]: https://github.com/RustCrypto/formats/pull/135
=> base64ct v1.2.0

const-oid/src/lib.rs
This primarily impacts how the derived `PartialOrd`/`Ord` impls behave.
It ensures that the longer OID is always greater.
=> const-oid: make `length` the first field of `ObjectIdentifier`

der/src/asn1/set_of.rs, der/tests/set_of.rs
These were failing to parse correctly until inadvertently fixed by #178.
The problem is not fully addressed, but it's good to at least capture it in a regression test to prevent future breakages.
Note that this test also seems to be uncovering another bug in `const-oid` which will get separately addressed in a followup.
=> der: add test for `SetOf` regression

const-oid/src/arcs.rs, const-oid/tests/lib.rs
There was an off-by-one error in this assertion which was causing it to fire on a well-formed, in-range arc.
=> const-oid: fix `debug_assert!` misfire on large arc

pem-rfc7468/src/decoder.rs, pem-rfc7468/src/lib.rs
This adds a `Decoder` struct which supports one configurable setting: the Base64 line-wrapping width.
From RFC7468 Section 2:
> Parsers MAY handle other line sizes.
Closes #176
=> pem-rfc7468: add `Decoder` struct

tai64/src/lib.rs
Follows the conventions enforced by `clippy::upper_case_acronyms` and renames the acronym parts of struct names to be lower case.
This follows standard Rust idioms which weren't being honored before.
=> tai64: rename `TAI64` => `Tai64`; `TAI64N` => `Tai64N`

Cargo.lock, tai64/Cargo.toml, tai64/src/lib.rs
I attempted to translate these to `proptest`, but they don't really seem to be doing a whole lot for us.
=> tai64: remove `quickcheck` tests

Cargo.lock, tai64/CHANGELOG.md, tai64/Cargo.toml, tai64/src/lib.rs
- Upgrade to Rust 2021 edition; MSRV 1.56+
- Moved to `RustCrypto/utils` repository ([#182])
- Rename `TAI64` => `Tai64`; `TAI64N` => `Tai64N` ([#183])
- Make constants inherent ([#184])
- `TAI64_LEN` => `Tai64::BYTE_SIZE`
- `TAI64N_LEN` => `Tai64N::BYTE_SIZE`
- `UNIX_EPOCH_TAI64` => `Tai64::UNIX_EPOCH`
- `UNIX_EPOCH_TAI64N` => `Tai64N::UNIX_EPOCH`
- `chrono` support
[#182]: https://github.com/RustCrypto/formats/pull/182
[#183]: https://github.com/RustCrypto/formats/pull/183
[#184]: https://github.com/RustCrypto/formats/pull/184
=> tai64 v4.0.0

pkcs1/src/private_key.rs, pkcs1/tests/private_key.rs
Uses an approach similar to the one from the `pkcs8` crate, where the `version` field is computed based on the presence or absence of the `other_prime_infos` field in the private key.
This avoids scenarios where the user has set it incorrectly.
=> pkcs1: make `RsaPrivateKey::version` implicit

der/src/asn1/any.rs, der/src/asn1/bit_string.rs, der/src/asn1/boolean.rs, der/src/asn1/context_specific.rs, der/src/asn1/generalized_time.rs, der/src/asn1/ia5_string.rs, der/src/asn1/integer.rs, der/src/asn1/null.rs, der/src/asn1/octet_string.rs, der/src/asn1/oid.rs, der/src/asn1/optional.rs, der/src/asn1/printable_string.rs, der/src/asn1/sequence_of.rs, der/src/asn1/utc_time.rs, der/src/asn1/utf8_string.rs, der/src/byte_slice.rs, der/src/header.rs, der/src/length.rs, der/src/lib.rs, der/src/ord.rs, der/src/tag.rs
Adds traits for establishing a lexicographic ordering for DER serialized values, for use with `SET OF`:
- `DerOrd`: ordering of two types when serialized as ASN.1 DER
- `ValueOrd`: ordering of the value portion of a TLV-encoded DER production, with a blanket impl for `DerOrd` that computes the header
- `OrdIsValueOrd`: marker trait for types whose `Ord` impl can be used as the `ValueOrd` impl
=> der: add `*Ord` traits

der/src/asn1/integer/bigint.rs, der/src/asn1/sequence_of.rs, der/src/lib.rs
Turns on the `unused_lifetimes` lint and fixes the occurrances.
=> der: fix unused lifetimes

pem-rfc7468/CHANGELOG.md
This commit adds a changelog entry about `pem-rfc7468` v0.2.4, which was released to address RustCrypto/RSA#116.
The release is identical to v0.2.3, but with `base64ct` restricted to `<1.2` in order to prevent MSRV-related breakages.
Since `master` is already on `pem-rfc7468` v0.3.0-pre which is also a 2021 edition crate, those changes are not actually included in this commit, but rather just the changelog entry.
=> pem-rfc7468 v0.2.4

Cargo.lock, der/derive/Cargo.toml, der/derive/src/lib.rs
Provides better formatted errors for the proc macro
=> der_derive: use `proc-macro-error` crate

der/derive/src/attributes.rs, der/derive/src/choice.rs, der/derive/src/enumerated.rs, der/derive/src/sequence.rs
Replaces all remaining occurrences of `panic!` with the `proc-macro-error` crate's `abort!` macro, which provides better diagnostics.
=> der_derive: replace `panic!` with `proc-macro-error`

der/derive/src/choice.rs, der/derive/src/enumerated.rs, der/derive/src/lib.rs, der/derive/src/sequence.rs
Refactors the constructors for:
- `DeriveChoice`
- `DeriveEnumerated`
- `DeriveSequence`
The constructors now handle all of the `DeriveInput` parsing, and return `Self`, which allows for a 2-step process with an IR, which should enable unit testing.
=> der_derive: refactor `Derive*` constructors

der/derive/src/attributes.rs, der/derive/src/choice.rs, der/derive/src/sequence.rs, der/derive/src/tag.rs
Changes `FieldAttrs` to support parsing `tag_mode`, and if unspecified inheriting `tag_mode` from the type-level attributes, or defaulting to `EXPLICIT` if also unspecified at the type-level.
=> der_derive: add field-level `tag_mode` support

der/src/asn1.rs, der/src/asn1/context_specific.rs, der/src/encoder.rs, der/src/lib.rs
Adds a reference type for encoding context-specific fields, and unifies all context-specific encoding under that.
This also makes it possible to construct a context-specific encoder trait object for use with `Sequence::fields`.
=> der: add `ContextSpecificRef` type

der/src/asn1/bit_string.rs
Previously this conversion was infallible because only octet-aligned `BIT STRING`s were accepted.
Now that we support "unused bits", this conversion should only succeed if the number of unused bits is equal to zero.
=> der: switch `impl From<BitString> for &[u8]` to `TryFrom`

der/derive/src/attributes.rs, der/derive/src/lib.rs, der/derive/src/sequence.rs, der/src/asn1.rs, der/src/asn1/optional.rs, der/tests/derive.rs
PR #202 removed support for the `#[asn1(type = "...")]` attribute when deriving `Sequence`.
This PR restores it, and also slightly changes the way the `default` attribute is handled, with added tests.
=> der_derive: fix `#[asn1(type = "...")]` attribute

der/derive/src/asn1_type.rs, der/derive/src/attributes.rs, der/derive/src/choice.rs, der/derive/src/lib.rs, der/derive/src/sequence.rs, der/derive/src/value_ord.rs, der/src/lib.rs, der/tests/derive.rs
Support for deriving `ValueOrd` on structs, which is used by the `SetOf*` types to determine ordering.
=> der_derive: add proc macro for deriving `ValueOrd`

Cargo.lock, pkcs8/src/lib.rs
This makes it possible to access things like `spki::Error` without having to re-export all of them
=> pkcs8: re-export `spki` crate

pkcs8/src/document/encrypted_private_key.rs, pkcs8/src/document/private_key.rs, pkcs8/src/lib.rs
It can be easily accessed as `pkcs8::der::pem`
=> pkcs8: don't re-export `der::pem`

pkcs8/src/error.rs, spki/src/algorithm.rs, spki/src/error.rs
- Renames `spki::Error::UnknownOid` => `OidUnknown` for consistency with `der::ErrorKind::OidUnknown`
- Adds `pkcs8::Error::PublicKey` as a wrapper for `spki::Error`
=> spki: error improvements

pkcs8/src/document/private_key.rs, pkcs8/src/encrypted_private_key_info.rs, pkcs8/src/error.rs
Renames the old variant and has it propagate the newly added `pkcs5::Error` type, which includes information about why PKCS#5 operations failed.
=> pkcs8: rename `Error::Crypto` => `Error::EncryptedKey`

pkcs8/src/error.rs
More consistent with the rest of the type names
=> pkcs8: rename `Error::EncryptedKey` => `::EncryptedPrivateKey`

Cargo.lock, const-oid/CHANGELOG.md, const-oid/Cargo.toml, const-oid/src/lib.rs, der/Cargo.toml
- Rename `MAX_LENGTH` to `MAX_SIZE`; bump to `31` ([#174])
- Make `length` the first field of `ObjectIdentifier` ([#178])
- `debug_assert!` false positive on large arc ([#180])
[#174]: https://github.com/RustCrypto/formats/pull/174
[#178]: https://github.com/RustCrypto/formats/pull/178
[#180]: https://github.com/RustCrypto/formats/pull/180
=> const-oid v0.7.0

Cargo.lock, der/Cargo.toml, pem-rfc7468/CHANGELOG.md, pem-rfc7468/Cargo.toml, pem-rfc7468/src/lib.rs
- `Decoder` struct ([#177])
- Bump `base64ct` dependency to v1.2 ([#175])
[#175]: https://github.com/RustCrypto/formats/pull/175
[#177]: https://github.com/RustCrypto/formats/pull/177
=> pem-rfc7468 v0.3.0

der/derive/src/attributes.rs, der/derive/src/choice.rs, der/derive/src/lib.rs, der/derive/src/sequence.rs, der/tests/derive.rs
Adds support for deriving `CONTEXT-SPECIFIC` fields when using the `Sequence` proc macro.
It's a bit incomplete with corner cases involving combinations of attributes probably not handled correctly, but it's a start.
=> der_derive: CONTEXT-SPECIFIC support for SEQUENCE

Cargo.lock, der/Cargo.toml, der/derive/CHANGELOG.md, der/derive/Cargo.toml, der/derive/src/lib.rs
- `asn1(tag_mode = "...")` derive attribute ([#150])
- `asn1(context_specific = "...")` derive attribute ([#150])
- `Enumerated` custom derive macro ([#171])
- `asn1(tag_mode = "...")` attribute ([#197])
- Support for handling `DEFAULT` values of `SEQUENCE`s ([#202])
- `ValueOrd` custom derive macro ([#206])
- `CONTEXT-SPECIFIC` support for `Sequence` custom derive ([#220])
- Rename `Message` trait to `Sequence` ([#99])
- Don't automatically derive `From` impls for `Choice` ([#168])
[#99]: https://github.com/RustCrypto/formats/pull/99
[#150]: https://github.com/RustCrypto/formats/pull/150
[#168]: https://github.com/RustCrypto/formats/pull/150
[#171]: …
=> der_derive v0.5.0

Cargo.lock, der/CHANGELOG.md, der/Cargo.toml, der/src/lib.rs, pkcs1/Cargo.toml, pkcs5/Cargo.toml, pkcs7/Cargo.toml, pkcs8/Cargo.toml, sec1/Cargo.toml, spki/Cargo.toml, x509/Cargo.toml
- Support for `IMPLICIT` mode `CONTEXT-SPECIFIC` fields ([#61])
- `DecodeValue`/`EncodeValue` traits ([#63])
- Expose `DateTime` through public API ([#75])
- `SEQUENCE OF` support for `[T; N]` ([#90])
- `SequenceOf` type ([#95])
- `SEQUENCE OF` support for `Vec` ([#96])
- `Document` trait ([#117])
- Basic integration with `time` crate ([#129])
- `Tag::NumericString` ([#132])
- Support for unused bits to `BitString` ([#141])
- `Decoder::{peek_tag, peek_header}` ([#142])
- Type hint in `encoder `sequence` method ([#147])
- `Tag::Enumerated` ([#153])
- `ErrorKind::TagNumberInvalid` ([#156])
- `Tag::VisibleString` and `Tag::BmpString` ([#160])
- Inherent constants for all valid `TagNumber`s ([#165])
- `DerOrd` and `ValueOrd` traits ([#190])
- `ContextSpecificRef` type ([#199])
- Make …
=> der v0.5.0

Cargo.lock, pkcs5/Cargo.toml, pkcs7/Cargo.toml, pkcs8/Cargo.toml, spki/CHANGELOG.md, spki/Cargo.toml, spki/src/lib.rs, x509/Cargo.toml
- SPKI fingerprint support ([#36])
- `PublicKeyDocument` type originally from `pkcs8` crate ([#118])
- `Error` type ([#143])
- Rename `From/ToPublicKey` => `DecodePublicKey`/`EncodePublicKey` ([#119])
- Use `der::Document` to impl `PublicKeyDocument` ([#134])
- Bump `der` dependency to v0.5 ([#222])
[#36]: https://github.com/RustCrypto/formats/pull/36
[#118]: https://github.com/RustCrypto/formats/pull/118
[#119]: https://github.com/RustCrypto/formats/pull/119
[#134]: https://github.com/RustCrypto/formats/pull/134
[#143]: https://github.com/RustCrypto/formats/pull/143
[#222]: https://github.com/RustCrypto/formats/pull/222
=> spki v0.5.0

Cargo.lock, pkcs5/CHANGELOG.md, pkcs5/Cargo.toml, pkcs5/src/lib.rs, pkcs8/Cargo.toml
- Introduce `Error` enum with new error cases ([#26])
- Introduce specialized `Result` type for crate ([#26])
- Bump `der` dependency to v0.5 ([#222])
- Bump `spki` dependency to v0.5 ([#223])
- Legacy DES encryption support ([#25])
[#25]: https://github.com/RustCrypto/formats/pull/25
[#26]: https://github.com/RustCrypto/formats/pull/26
[#222]: https://github.com/RustCrypto/formats/pull/222
[#223]: https://github.com/RustCrypto/formats/pull/223
=> pkcs5 v0.4.0

Cargo.lock, pkcs7/CHANGELOG.md, pkcs7/Cargo.toml, pkcs7/src/lib.rs
Initial release of the RustCrypto `pkcs7` crate
=> pkcs7 v0.3.0

der/src/asn1/any.rs, der/src/byte_slice.rs
Adds a `const fn` for obtaining an `Any` value representing the ASN.1 `NULL` type.
=> der: add `Any::null()`

Cargo.lock, der/src/asn1/any.rs, der/src/byte_slice.rs, pkcs1/Cargo.toml, pkcs1/src/error.rs, pkcs1/src/lib.rs, pkcs1/src/pkcs8.rs, pkcs1/src/private_key/document.rs, pkcs1/src/public_key/document.rs, pkcs1/src/traits.rs
Adds an optional `pkcs8` crate integration which provides a blanket impl of the `pkcs1` decoding/encoding traits for any type that impls the corresponding `pkcs8` traits.
=> pkcs1: add `pkcs8` feature

.github/workflows/sec1.yml, Cargo.lock, pkcs1/src/lib.rs, pkcs1/src/pkcs8.rs, sec1/Cargo.toml, sec1/src/error.rs, sec1/src/lib.rs, sec1/src/pkcs8.rs, sec1/src/traits.rs
Adds an optional `pkcs8` crate integration which provides a blanket impl of the `sec1` decoding/encoding traits for any type that impls the corresponding `pkcs8` traits.
=> sec1: add `pkcs8` feature

pkcs1/Cargo.toml, sec1/Cargo.toml
Ideally weak feature activation could be used here, but unfortunately it is not yet stable.
This otherwise makes it possible to use the PEM functionality of `pkcs8` directly via blanket impls in `pkcs1` and `sec1`.
=> pkcs1+sec1: activate `pkcs8/pem` when `pem` feature is enabled

Cargo.lock, pkcs1/Cargo.toml, pkcs8/CHANGELOG.md, pkcs8/Cargo.toml, pkcs8/src/lib.rs, sec1/Cargo.toml
- Re-export `spki` crate ([#210])
- Replace usages of `expect` with fallible methods ([#108])
- Impl `From*Key`/`To*Key` traits on `Document` types ([#110])
- Rename `From/ToPrivateKey` => `DecodePrivateKey`/`EncodePrivateKey` ([#121])
- Use `der::Document` to impl `*PrivateKeyDocument` ([#140])
- Rename `Error::Crypto` => `Error::EncryptedPrivateKey` ([#213], [#214])
- Bump `der` dependency to v0.5 ([#222])
- Bump `spki` dependency to v0.5 ([#223])
- Bump `pkcs5` dependency to v0.4 ([#224])
- Replace `from_pkcs8_private_key_info` with `TryFrom` ([#230])
- `*_with_le` PEM encoding methods ([#109])
- PKCS#1 support; moved to `pkcs1` crate ([#124])
- I/O related errors from key format crates ([#158])
- `der::pem` export ([#211])
[#108]: …
=> pkcs8 v0.8.0

Cargo.lock, pkcs1/CHANGELOG.md, pkcs1/Cargo.toml, pkcs1/src/lib.rs
- Support for multi-prime RSA keys ([#115])
- `pkcs8` feature ([#227], [#233])
- Rename `From/ToRsa*Key` => `DecodeRsa*Key`/`EncodeRsa*Key` ([#120])
- Use `der::Document` to impl `RsaPrivateKeyDocument` ([#131])
- Make `RsaPrivateKey::version` implicit ([#188])
- Bump `der` dependency to v0.5 ([#222])
- Activate `pkcs8/pem` when `pem` feature is enabled ([#232])
- `*_with_le` PEM encoding methods ([#109])
- I/O related errors ([#158])
[#109]: https://github.com/RustCrypto/formats/pull/109
[#115]: https://github.com/RustCrypto/formats/pull/115
[#120]: https://github.com/RustCrypto/formats/pull/120
[#131]: https://github.com/RustCrypto/formats/pull/131
[#158]: …
=> pkcs1 v0.3.0

Cargo.lock, pkcs1/CHANGELOG.md, sec1/CHANGELOG.md, sec1/Cargo.toml, sec1/src/lib.rs
- `pkcs8` feature ([#229])
- Rename `From/ToEcPrivateKey` => `DecodeEcPrivateKey`/`EncodeEcPrivateKey` ([#122])
- Use `der::Document` to impl `EcPrivateKeyDocument` ([#133])
- Bump `der` crate dependency to v0.5 ([#222])
- I/O related errors ([#158])
[#122]: https://github.com/RustCrypto/formats/pull/122
[#133]: https://github.com/RustCrypto/formats/pull/133
[#158]: https://github.com/RustCrypto/formats/pull/158
[#222]: https://github.com/RustCrypto/formats/pull/222
[#229]: https://github.com/RustCrypto/formats/pull/229
=> sec1 v0.2.0

pem-rfc7468/Cargo.toml, spki/Cargo.toml
Neither of these crates are depending on functionality added after the original v1.0 release.
However, they were pinned to `1.2` instead of `1` following the latest round of prereleases, effectively by mistake when the version in their respective Cargo.toml files was changed from a prerelease to the final release.
This makes these crates (and anything depending on them) mutually incompatible with at least the `password-hash` crate, which has `base64ct` pinned to prevent MSRV breakages:
https://github.com/RustCrypto/traits/runs/4239715372?check_suite_focus=true
```
error: failed to select a version for `base64ct`.
... required by package `spki v0.5.1`
... which satisfies dependency `spki = "^0.5"` of package `pkcs8 v0.8.0`
... which satisfies dependency `pkcs8 = "^0.8"` of package `sec1 …
```
=> pem-rfc7468+spki: relax `base64ct` requirements to `^1`

Cargo.lock, pem-rfc7468/CHANGELOG.md, pem-rfc7468/Cargo.toml, pem-rfc7468/src/lib.rs
- Relax `base64ct` version requirement to `^1` ([#239])
[#239]: https://github.com/RustCrypto/formats/pull/239
=> pem-rfc7468 v0.3.1

Cargo.lock, spki/CHANGELOG.md, spki/Cargo.toml, spki/src/lib.rs
- Relax `base64ct` version requirement to `^1` ([#239])
[#239]: https://github.com/RustCrypto/formats/pull/239
=> spki v0.5.2

sec1/src/lib.rs, sec1/src/traits.rs
Fix broken links and malformed `doc(cfg(...))` attributes
=> sec1: rustdoc fixups

pkcs1/src/private_key.rs, pkcs8/src/encrypted_private_key_info.rs, pkcs8/src/private_key_info.rs, sec1/src/private_key.rs
Various private key types had TODOs to use it. It was stabilized in Rust 1.53.
=> Use `finish_non_exhaustive` in `Debug` impls

.github/workflows/sec1.yml, Cargo.lock, sec1/Cargo.toml, sec1/src/lib.rs, sec1/src/point.rs
Adds an optional `serde` feature with support for decoding/encoding `EncodedPoint`s using the `Serialize`/`Deserialize` traits.
This additionally adds support for hex encoding/decoding points which is always available.
=> sec1: `serde` feature

Cargo.lock, sec1/CHANGELOG.md, sec1/Cargo.toml, sec1/src/lib.rs
- `serde` feature ([#248])
- Hexadecimal serialization/deserialization support for `EncodedPoint` ([#248])
[#248]: https://github.com/RustCrypto/formats/pull/248
=> sec1 v0.2.1

tls_codec/derive/src/lib.rs, tls_codec/derive/tests/decode.rs, tls_codec/derive/tests/encode.rs
This attribute allows to designate a module where to find functions to serialize, deserialize or get the serialized size of a field. This is similar to [serde's attribute](https://serde.rs/field-attrs.html#with).
The main motivation is to avoid having to resort to a manual implementation of the `tls_codec` traits for a struct as soon as the type of a field does not implement them, which is more error-prone and less maintainable.
This PR also makes structs and tuple structs share more code, and fixes a derive macro that relied on a trait being in scope.
Thank you!
cc @tomleavy
=> Add `tls_codec(with = "module")` attribute to customize how struct fields are handled by derive macro

Cargo.lock, tls_codec/Cargo.toml, tls_codec/derive/Cargo.toml, tls_codec/derive/tests/encode.rs, tls_codec/src/arrays.rs, tls_codec/src/primitives.rs, tls_codec/tests/decode.rs
- Implement traits for `&T`.
- set version to 0.2.0 pre.2
The changes in #250 require implementing traits for the borrowed type explicitly.
=> tls_codec: Implement traits for `&T`

.github/workflows/ssh-key.yml, Cargo.lock, Cargo.toml, README.md, ssh-key/CHANGELOG.md, ssh-key/Cargo.toml, ssh-key/LICENSE-APACHE, ssh-key/LICENSE-MIT, ssh-key/README.md, ssh-key/src/lib.rs
Initial boilerplate for an `ssh-key` format parser crate, which can leverage the other crates in this repo, most notably `pem-rfc7468`.
=> ssh-key: initial crate

Cargo.lock, pkcs1/CHANGELOG.md, pkcs1/Cargo.toml, pkcs1/src/lib.rs
- Use `finish_non_exhaustive` in `Debug` impls ([#245])
[#245]: https://github.com/RustCrypto/formats/pull/245
=> pkcs1 v0.3.1

Cargo.lock, const-oid/CHANGELOG.md, const-oid/Cargo.toml, const-oid/src/lib.rs
- Increase `MAX_SIZE` to 39 ([#258])
[#258]: https://github.com/RustCrypto/formats/pull/258
=> const-oid v0.7.1

.cargo/audit.toml
Ignores `RUSTSEC-2021-0127`: `serde_cbor` is unmaintained
This is a transitive dependency of `criterion`
=> .cargo/audit.toml: initial config with RUSTSEC-2021-0127

base64ct/src/decoder.rs, base64ct/src/encoding.rs, base64ct/src/lib.rs, base64ct/src/variant.rs, base64ct/src/variant/bcrypt.rs, base64ct/src/variant/crypt.rs, base64ct/src/variant/standard.rs, base64ct/src/variant/url.rs
Adds a buffered `Decoder` which is able to incrementally decode an output stream from an unpadded input.
Presently constrained to contiguous Base64 inputs which do not contain newlines, although an important next step is to encapsulate line-wrapped inputs.
Support for padded inputs is untested and broken, but will be fixed in a followup commit.
=> base64ct: add stateful `Decoder` type

tls_codec/derive/src/lib.rs, tls_codec/src/tls_vec.rs
This PR cleans up unnecessary bounds in `tls_codec` (e.g. generic `Size` implementations requiring `Serialize`).
Thank you.
=> Clean up bounds in tls_codec

tls_codec/src/primitives.rs
This allows to derive the `tls_codec` traits for types that contain fields of type unit (e.g. a private unit field to prevent direct construction in other modules).
Thank you.
=> Implement `tls_codec` traits for the unit type

Cargo.lock, base64ct/Cargo.toml, base64ct/tests/proptests.proptest-regressions, base64ct/tests/proptests.rs
Adds a set of property-based equivalence tests to ensure that `base64ct` is able to decode inputs generated by `base64` and also encodes inputs equivalently to the `base64` crate.
=> base64ct: proptests for equivalence to `base64` crate

der/CHANGELOG.md
Adds a CHANGELOG.md entry for the v0.4.5 release of the `der` crate, which backports a fix for #146 from the v0.5.x series to the v0.4.x series.
As this is a backport, there aren't associated code changes.
=> der v0.4.5

.github/workflows/ssh-key.yml, Cargo.lock, base64ct/src/decoder.rs, sec1/src/point.rs, ssh-key/Cargo.toml, ssh-key/README.md, ssh-key/src/algorithm.rs, ssh-key/src/base64.rs, ssh-key/src/error.rs, ssh-key/src/lib.rs, ssh-key/src/mpint.rs, ssh-key/src/public.rs, ssh-key/src/public/openssh.rs, ssh-key/tests/public_key.rs
Adds an initial `public` module with a set of public key types:
- `ecdsa-sha2-nistp256`
- `ecdsa-sha2-nistp384`
- `ecdsa-sha2-nistp521`
- `ssh-dss`
- `ssh-ed25519`
- `ssh-rsa`
Support is implemented for decoding OpenSSH-formatted public keys.
=> ssh-key: initial `public` key types

base64ct/src/decoder.rs, base64ct/tests/proptests.rs, ssh-key/src/base64.rs
Consolidates the `decode_partial` and `decode_exact` methods into a single `decode` method, since that's all that's needed (for now).
Makes the `BlockBuffer` persistent which simplifies the implementation somewhat.
=> base64ct: simplify incremental decoder

Cargo.lock, base64ct/CHANGELOG.md, base64ct/Cargo.toml, base64ct/src/lib.rs, ssh-key/Cargo.toml
- Stateful `Decoder` type ([#266])
[#266]: https://github.com/RustCrypto/formats/pull/266
=> base64ct v1.3.0

spki/src/algorithm.rs
Allows for storing `AlgorithmIdentifier`s in SET OF types.
Closes #288
=> spki: impl `ValueOrd` for `AlgorithmIdentifier`

base64ct/src/decoder.rs
This change hasn't been released yet, so renaming is okay and a non-breaking change.
=> base64ct: rename `Decoder::new_linewrapped` => `::new_wrapped`

.github/workflows/tls_codec.yml, tls_codec/Cargo.toml, tls_codec/src/arrays.rs, tls_codec/src/lib.rs, tls_codec/src/primitives.rs, tls_codec/src/tls_vec.rs
Adds initial support for `no_std` targets (currently with a hard `alloc` dependency) by gating all `std`-related functionality on a newly added eponymous crate feature.
Unfortunately all serialization/deserialization is currently performed in terms of the `Read` and `Write` traits from `std::io`, so this doesn't result in something immediately useful on `no_std` targets. However, it does provide the initial boilerplate and first steps towards making that possible.
=> tls_codec: preliminary `no_std` support

Cargo.lock, base64ct/CHANGELOG.md, base64ct/Cargo.toml, base64ct/src/lib.rs
- `Decoder::new_wrapped` with support for line-wrapped Base64 ([#292], [#293], [#294])
[#292]: https://github.com/RustCrypto/formats/pull/292
[#293]: https://github.com/RustCrypto/formats/pull/292
[#294]: https://github.com/RustCrypto/formats/pull/294
=> base64ct v1.3.1

Cargo.lock, base64ct/src/decoder.rs, ssh-key/Cargo.toml, ssh-key/src/algorithm.rs, ssh-key/src/algorithm/dsa.rs, ssh-key/src/algorithm/ecdsa.rs, ssh-key/src/algorithm/ed25519.rs, ssh-key/src/algorithm/rsa.rs, ssh-key/src/base64.rs, ssh-key/src/error.rs, ssh-key/src/lib.rs, ssh-key/src/private.rs, ssh-key/src/private/openssh.rs, ssh-key/src/public.rs, ssh-key/src/public/openssh.rs, ssh-key/tests/private_key.rs, ssh-key/tests/public_key.rs
Adds initial support for decoding private keys from the OpenSSH private key format:
https://github.com/openssh/openssh-portable/blob/master/PROTOCOL.key
This commit implements initial support for Ed25519 private keys, however the larger goal is to implement support for DSA, ECDSA, and RSA as well, which will occur in follow-up commits.
=> ssh-key: initial private key support (Ed25519-only)

base64ct/src/decoder.rs, base64ct/src/lib.rs
Changes from a buggy implementation that tried to eagerly unpad inputs to one which uses the built-in padding support and validation when decoding the final data in a given input message.
=> base64ct: fix `Decoder` unpadding

ssh-key/Cargo.toml, ssh-key/src/algorithm.rs, ssh-key/src/algorithm/ecdsa.rs, ssh-key/src/algorithm/ed25519.rs, ssh-key/src/base64.rs, ssh-key/src/error.rs, ssh-key/src/lib.rs, ssh-key/src/private.rs, ssh-key/src/public.rs, ssh-key/tests/private_key.rs, ssh-key/tests/public_key.rs
Support for decoding ECDSA private keys into an `EcdsaKeypair` type.
Tested against vectors for the NIST P-256, P-384, and P-521 elliptic curves.
=> ssh-key: ECDSA private key support

Cargo.lock, base64ct/CHANGELOG.md, base64ct/Cargo.toml, base64ct/src/lib.rs, ssh-key/Cargo.toml
- `Decoder` unpadding ([#299])
- Edge case when using `Decoder::new_wrapped` ([#300])
[#299]: https://github.com/RustCrypto/formats/pull/299
[#300]: https://github.com/RustCrypto/formats/pull/300
=> base64ct v1.3.2

ssh-key/src/algorithm.rs, ssh-key/src/algorithm/dsa.rs, ssh-key/src/algorithm/ecdsa.rs, ssh-key/src/algorithm/ed25519.rs, ssh-key/src/algorithm/rsa.rs, ssh-key/src/base64.rs, ssh-key/src/mpint.rs, ssh-key/src/private.rs, ssh-key/src/public.rs
Adds an internal `Decode` trait which encapsulates the same-shaped `fn decode` method used to decode various types throughout the crate.
=> ssh-key: `Decode` trait

base64ct/src/decoder.rs
A potential infinite loop existed in the event the decoder is asked to decode more data than is available.
This commit adds a check for that case which returns `InvalidLength`.
=> base64ct: fix potential infinite loop in `Decoder::decode`

ssh-key/src/algorithm/dsa.rs, ssh-key/src/algorithm/ecdsa.rs, ssh-key/src/base64.rs, ssh-key/src/mpint.rs, ssh-key/src/private.rs, ssh-key/src/public.rs, ssh-key/tests/private_key.rs
Support for decoding DSA private keys into a `DsaKeypair` type.
Gated on the `alloc` feature.
=> ssh-key: DSA private key support

Cargo.lock, base64ct/CHANGELOG.md, base64ct/Cargo.toml, base64ct/src/lib.rs, ssh-key/Cargo.toml
- Potential infinite loop in `Decoder::decode` ([#305])
[#305]: https://github.com/RustCrypto/formats/pull/305
=> base64ct v1.3.3

ssh-key/src/private.rs, ssh-key/src/private/dsa.rs, ssh-key/src/private/ecdsa.rs, ssh-key/src/private/ed25519.rs, ssh-key/src/private/rsa.rs, ssh-key/src/public.rs, ssh-key/src/public/dsa.rs, ssh-key/src/public/ecdsa.rs, ssh-key/src/public/ed25519.rs, ssh-key/src/public/rsa.rs, ssh-key/tests/private_key.rs
Support for decoding RSA private keys into an `RsaKeypair` type.
Gated on the `alloc` feature.
=> ssh-key: RSA private key support

ssh-key/src/lib.rs, ssh-key/src/private/openssh.rs
Provides an example for how to parse OpenSSH-formatted private keys
=> ssh-key: `PrivateKey` usage example

Cargo.lock, ssh-key/CHANGELOG.md, ssh-key/Cargo.toml, ssh-key/src/lib.rs
- OpenSSH private key decoder ([#297], [#301], [#307], [#311])
- `MPInt::as_positive_bytes` ([#312])
- `MPInt` validates the correct number of leading zeroes are used ([#312])
[#297]: https://github.com/RustCrypto/formats/pull/297
[#301]: https://github.com/RustCrypto/formats/pull/301
[#307]: https://github.com/RustCrypto/formats/pull/307
[#311]: https://github.com/RustCrypto/formats/pull/311
[#312]: https://github.com/RustCrypto/formats/pull/312
=> ssh-key v0.2.0

ssh-key/README.md
Removes a line which duplicates information from the newly added "Features" section
=> ssh-key: README.md fixup

spki/src/error.rs
Adds an error variant similar to `pkcs8::Error::KeyMalformed` for relaying that binary data contained in `subject_public_key` is in some way malformed beyond what errors can be communicated via `Error::Asn1` for DER decoding errors.
This is useful if DER decoding succeeds but something else is wrong, e.g. an elliptic curve public key is not a valid solution to the curve equation.
=> spki: add `Error::KeyMalformed` variant

Cargo.lock, spki/CHANGELOG.md, spki/Cargo.toml, spki/LICENSE-MIT, spki/src/lib.rs
- `Error::KeyMalformed` variant ([#318])
[#318]: https://github.com/RustCrypto/formats/pull/318
=> spki v0.5.4

base16ct/src/lib.rs, base16ct/src/lower.rs, base16ct/src/mixed.rs, base16ct/src/upper.rs, base16ct/tests/lib.rs
Code re-organized into free-standing functions inside 3 modules: mixed, lower, and upper. The former has only decoding functions, while the latter two have both decoding and encoding functions. Also added `encode_str` functions which return `&str` instead of `&[u8]`. I wonder if it could be useful to have `decode_in_place` functions like in `base64ct`.
Unfortunately, even though decoding functions [get auto-vectorized](https://rust.godbolt.org/z/f9Ws54bzY) properly with default build parameters, we are not so lucky with encoding functions: https://rust.godbolt.org/z/TxM6v1W45 It could be worth to help compiler with it somehow.
=> base16ct: re-organize crate

base16ct/benches/mod.rs
Results on AMD Ryzen 7 2700x with default build parameters:
```
test decode_lower ... bench:       6,906 ns/iter (+/- 366) = 2372 MB/s
test decode_mixed ... bench:       4,934 ns/iter (+/- 122) = 3320 MB/s
test decode_upper ... bench:       6,960 ns/iter (+/- 290) = 2354 MB/s
test encode_lower ... bench:      22,188 ns/iter (+/- 777) = 738 MB/s
test encode_upper ... bench:      22,073 ns/iter (+/- 678) = 742 MB/s
// hex v0.4 for comparison:
test hex_decode_to_slice ... bench:      34,859 ns/iter (+/- 565) = 470 MB/s
test hex_encode_to_slice ... bench:      23,880 ns/iter (+/- 413) = 686 MB/s
```
Weirdly enough the mixed decoding is the fastest, even though it requires more operations. Also we can see results of the lacking auto-vectorization.
With `-C target-cpu=native`:
```
test …
```
=> base16ct: add benches

base16ct/src/display.rs, base16ct/src/error.rs, base16ct/src/lib.rs, base16ct/tests/lib.rs
Adds a `HexDisplay` wrapper type with impls of `Display`, `UpperHex`, and `LowerHex` from `core::fmt` which can be used to display a byte slice using a constant-time hex encoder.
=> base16ct: add `HexDisplay` type

Cargo.lock, base16ct/CHANGELOG.md, base16ct/Cargo.toml, base16ct/src/lib.rs
- `HexDisplay` type ([#329])
[#329]: https://github.com/RustCrypto/formats/pull/329
=> base16ct v0.1.1

pkcs1/src/error.rs
Allows coercing `pkcs1::Error` to `pkcs8::Error` using `?`.
This is useful for decoding PKCS#1-encoded data inside of the `pkcs8` traits.
=> pkcs1: add error conversion support for pkcs8::Error

Cargo.lock, pkcs1/CHANGELOG.md, pkcs1/Cargo.toml, pkcs1/src/lib.rs
- Error conversion support for `pkcs8::Error` ([#331])
[#331]: https://github.com/RustCrypto/formats/pull/331
=> pkcs1 v0.3.2

pkcs1/src/error.rs
Allows coercing `pkcs1::Error` to `pkcs8::spki::Error` using `?`.
This is useful for decoding PKCS#1-encoded data inside of the `spki` crate's traits.
=> pkcs1: add error conversion support to `pkcs8::spki::Error`

Cargo.lock, pkcs1/CHANGELOG.md, pkcs1/Cargo.toml, pkcs1/src/lib.rs
- Error conversion support to `pkcs8::spki::Error` ([#333])
[#333]: https://github.com/RustCrypto/formats/pull/331
=> pkcs1 v0.3.3

pkcs8/src/error.rs
Allows coercing `pkcs8::Error` to `pkcs8::spki::Error` using `?`.
=> pkcs8: add error conversion support to `pkcs8::spki::Error`

der/derive/src/sequence.rs, der/derive/src/sequence/field.rs
Similar to #336, this extracts a `LowerFieldEncoder` type along with a `field` module where `SequenceField` is also placed.
Additionally it adds some basic tests for the generated code.
=> der_derive: extract `LowerFieldEncoder`

der/derive/src/attributes.rs, der/derive/src/choice.rs, der/derive/src/choice/variant.rs
Refactors the `choice` module in a similar way to how the `sequence` module was refactored in #337.
This makes it easier to extend and test. Additionally, this PR includes an initial set of basic tests for `ChoiceVariant` lowerings.
=> der_derive: extract `choice::variant` module

Cargo.lock, const-oid/CHANGELOG.md, const-oid/Cargo.toml, const-oid/LICENSE-MIT, const-oid/src/lib.rs, der/Cargo.toml
- Leverage `const_panic`; MSRV 1.57 ([#341])
[#341]: https://github.com/RustCrypto/formats/pull/341
=> const-oid v0.8.0

.github/workflows/der.yml, Cargo.lock, Cargo.toml, der/Cargo.toml, der/src/asn1/integer/bigint.rs, pkcs1/Cargo.toml
Removes the optional dependency on `crypto-bigint`, with the goal of reversing the relationship between the two and having `crypto-bigint` pull in `der` as an optional dependency.
=> der: remove `bigint` feature

der/derive/src/choice/variant.rs, der/derive/src/sequence.rs, der/derive/src/sequence/field.rs, der/derive/src/tag.rs, der/tests/derive.rs
This also adds a context-specific tag test to the code for #[derive(Choice)], and cleans up the tests in these files.
If you'd like I would be happy to add more tests to cover the interactions between the various options, but I admit that I'm not an ASN.1 expert so I would need some guidance as to how these options interact so that I could formulate the correct desugaring.
Closes #322.
=> Implement context-specific tags on #[derive(Sequence)]

x509/tests/certificate.rs
Clippy now complains about the use of a manual counter in the loops. These
tests can be more succinctly expressed using `.zip(EXTENSIONS)`.
=> Clean up certificate extension tests

der/src/asn1/boolean.rs, der/src/asn1/generalized_time.rs, der/src/asn1/ia5_string.rs, der/src/asn1/null.rs, der/src/asn1/octet_string.rs, der/src/asn1/oid.rs, der/src/asn1/printable_string.rs, der/src/asn1/utc_time.rs, der/src/asn1/utf8_string.rs, der/src/lib.rs, x509/src/attribute.rs
While this trait is useful for defining the `ValueOrd` impl for various ASN.1 universal types within the `der` crate itself, it is easily abused outside the context of the `der` crate.
`ValueOrd` handles comparing DER serializations for ordering. The `OrdIsValueOrd` is tempting in that it makes it appear that `Ord` can be used instead, but this only works in hyper-specific cases where `Ord` is identical to `ValueOrd`, which is primarily the ASN.1 universal types.
To prevent misuse, this commit seals the trait to force downstream users to impl `ValueOrd`.
=> der: make `OrdIsValueOrd` into sealed trait

base64ct/src/decoder.rs, base64ct/src/lib.rs
Enables the lint for unused qualifications, and fixes up the places where they occur.
Additionally adds an `unused_lifetimes` lint, but there were no occurrences of unused lifetimes that needed correcting.
Finally, adds some additional checks and documentation for `InvalidLength` cases.
=> base64ct: add `unused_qualifications` lint

der/src/arrayvec.rs, der/src/asn1/sequence_of.rs, der/src/asn1/set_of.rs, der/src/ord.rs
Adds impls which make it possible to compare the DER encoded orderings of `SET OF` types.
=> der: impl `ValueOrd` for `SetOf` and `SetOfVec`

Cargo.lock, base64ct/Cargo.toml, base64ct/src/decoder.rs, base64ct/src/encoder.rs, base64ct/src/errors.rs, base64ct/src/lib.rs, base64ct/src/test_vectors.rs, base64ct/tests/proptests.rs, der/Cargo.toml, pem-rfc7468/Cargo.toml, spki/Cargo.toml, ssh-key/Cargo.toml
Adds a buffered `Encoder` type, similar to the `Decoder` type, which accepts incremental variable-sized binary inputs to encode and incrementally writes Base64 output to a provided buffer.
This initial version doesn't yet support linewrapping, but that can be added in a followup.
=> base64ct: buffered encoder

der/derive/src/enumerated.rs
=> der_derive: remove static lifetime from ENUMERATED's derived `DecodeValue`

ssh-key/src/private.rs, ssh-key/src/public.rs
The `PublicKey` and `PrivateKey` types both have inherent `from_openssh` methods with the goal of potentially supporting some earlier legacy formats in addition to the most current OpenSSH formats.
However, they didn't previously have `FromStr`. This commit adds a `FromStr` thunk which calls `from_openssh`.
=> ssh-key: add `FromStr` impls to key types

ssh-key/src/algorithm.rs, ssh-key/src/base64.rs, ssh-key/src/error.rs, ssh-key/src/public.rs, ssh-key/src/public/ed25519.rs, ssh-key/src/public/openssh.rs, ssh-key/tests/public_key.rs
Adds initial support for encoding `PublicKey` data in OpenSSH format.
Uses the new buffered `base64ct::Encoder` type.
Ed25519 keys are supported with a `no_std`-friendly profile.
=> ssh-key: initial `PublicKey` encoder w\ Ed25519 support

base64ct/src/encoder.rs
A loop is really only necessary for a linewrapped encoder. It can be added back when that feature is implemented, with the logic reflecting the complexities of linewrapping.
=> base64ct: remove encoder loop

der/src/asn1.rs, der/src/asn1/sequence.rs, der/src/decoder.rs
Adds a type which wraps the value portion / "body" of a DER-serialized `SEQUENCE`.
This type subsumes the previous decoding logic for `Decoder::sequence`, parsing the `SEQUENCE` using `DecodeValue` and storing its position within the outer document.
In addition to simplifying the sequence decoding logic, this also makes it possible to use this type within the `Sequence` proc macro, which will allow it to impl `DecodeValue`. However, that work is left for a followup PR.
=> der: add `SequenceRef` type

der/derive/src/sequence.rs
The proc macro previously derived the `Decode` trait, which is not composable with context-specific fields, which depend on the `DecodeValue` trait in order to support IMPLICIT fields.
This commit changes the custom derive macro for `Sequence` to produce a `DecodeValue` impl instead of `Decode`. This leverages the newly introduced `SequenceRef` type from #374.
=> der_derive: have `Sequence` macro derive `DecodeValue`

der/src/asn1/set_of.rs
Adds impls of these traits for `SetOfVec`, which sort elements using `DerOrd`. The `FromIterator` impl is composed in terms of the `From<Vec<T>>` impl, which collects the elements into a `Vec`, then sorts them with `sort_by`.
One problem is `DerOrd::der_cmp` is fallible, so in order to use it with `sort_by` the only option is to panic if it returns an `Err`. I'm not sure if this can be resolved short of shipping a custom sort function or getting something like `try_sort_by` added to `core`. FWIW I proposed the latter here:
https://internals.rust-lang.org/t/fallible-sorting/16066
=> der: impl `From`/`FromIterator` for `SetOfVec`

Cargo.lock, pkcs10/Cargo.toml, pkcs10/src/lib.rs, x501/Cargo.toml, x501/src/lib.rs, x509/Cargo.toml
This allows them to be incremented in the release PRs
=> pkcs10+x501: bump versions to 0.0.0

der/derive/src/attributes.rs, der/derive/src/choice.rs, der/derive/src/choice/variant.rs
This enables `Choice` values to be used as a field in a `Sequence`.
=> Derive `EncodeValue` for `Choice`

der/src/asn1/set_of.rs, der/src/lib.rs
Removes the panicking `From` and `FromIterator` impls on `SetOfVec`, replacing it with a `TryFrom` impl that can gracefully handle sorting errors when using `DerOrd`.
Also adds a test for the sorting implementation.
=> der: replace/remove panicking `SetOfVec` APIs

der/derive/src/choice/variant.rs
The purpose of this transformation is for when the caller specifies `type =
"..."`. In that case, we decode into the specified type and then convert into
actual type. However, in cases where no type is specified, we have to decode
into an unspecified type `T` and then convert into the final type; but the
compiler (obviously) cannot determine the type `T`.
Therefore, when no `type` is specified, we drop the `.try_into()?` and just
attempt to decode into the final type directly.
=> Only emit `.try_into()?` when a type is specified

der/derive/src/attributes.rs, der/derive/src/lib.rs, der/derive/src/sequence/field.rs
This allows for deriving `Choice` over constructed types.
=> Add `#[asn1(constructed = "true")]`

der/src/arrayvec.rs
It previously didn't allow adding the last available element in the array, and would return `ErrorKind::Overlength`.
=> der: fix off-by-one error in `ArrayVec::add`

der/derive/src/choice/variant.rs
When deriving `Choice`, the existing macros emit incorrect length
calculation code when explicit tags are used.
=> Fix length calculation for explicit tags

der/src/asn1/set_of.rs, der/tests/set_of.rs
Rust's built-in `[T]::sort_by` requires both `alloc` and a panic handler, which is limiting for `no_std` targets.
This commit switches to using a heapless-friendly insertion sort implementation which is also fallible and can bubble up errors from `DerOrd::der_cmp`.
Insertion sort is small (<10loc) and should perform well when the input is mostly in order, which should hopefully often be the case for `SetOf` constructors. It also works completely in-place and is thus friendly to heapless targets.
This PR replaces the previous `[T]::sort_by` approach used by `SetOfVec`, which included a workaround which handled `DerOrd::der_cmp` errors by returning `Ordering::Less` and doing a second pass over the results to check they were correctly ordered. This might provide better performance and be …
=> der: support `SetOf` sorting on heapless `no_std` targets

base64ct/src/decoder.rs, base64ct/src/encoder.rs, base64ct/src/errors.rs
Conditionally impls the `Read` trait when the `std` feature is enabled.
=> base64ct: impl `std::io::Read` for `Decoder`

base64ct/src/encoding.rs, base64ct/src/variant.rs, base64ct/src/variant/bcrypt.rs, base64ct/src/variant/crypt.rs, base64ct/src/variant/standard.rs, base64ct/src/variant/url.rs
Deriving traits like `Copy`, `Clone`, and `Debug` on types which include an encoding as a generic parameter is presently problematic because there are no trait bounds specified.
These traits, `Encoding` and the sealed `Variant` which receives a blanket impl of the former, are not intended to be implemented by types outside of this crate. While adding bounds is technically a breaking change, it would be highly unexpected for this to have any real-world impact as external crates should only be consuming these traits and using them with the encoding ZSTs defined in this crate.
=> base64ct: add bounds for `Encoding`/`Variant` ZSTs

pem-rfc7468/Cargo.toml, pem-rfc7468/src/decoder.rs, pem-rfc7468/src/error.rs, pem-rfc7468/src/lib.rs, pem-rfc7468/tests/decode.rs
Modifies `pem_rfc7468::Decoder` to be a wrapper around the buffered `base64ct::Decoder` type.
This allows incrementally decoding PEM, as opposed to a one-shot approach, however support for one-shot decoding is still preserved as a set of static functions which previously served as the crate's primary API, meaning this should not be a breaking change for most current applications.
Additionally impls `std::io::Read` for `pem_rfc7468::Decoder`, delegating to the `std::io::Read` implementation added to `base64ct::Decoder` in #404.
=> pem-rfc7468: buffered Base64 decoder

der/derive/src/attributes.rs, der/derive/src/choice/variant.rs
By default, presume that a choice enum's type implements FixedTag. For
many cases, this means that no `#[asn1(...)]` is required at all. In
particular, this means that deriving `Choice` for `SEQUENCE` types
without a context-specific tag is now possible.   
=> der: use type's tag by default on derive(Choice)

der/derive/src/enumerated.rs, der/derive/src/lib.rs, pkcs10/src/version.rs, x509/src/certificate.rs, x509/tests/certificate.rs, x509/tests/pkix_extensions.rs
1. add a derive macro for deriving enumerations that are tagged as `INTEGER`.
2. use the new macro for `pkcs10::Version`.
3. add `x509::Version`.
=> Derived Version Structs

x509/src/certificate.rs, x509/src/pkix_extensions.rs, x509/src/trust_anchor_format.rs, x509/tests/certificate.rs, x509/tests/pkix_extensions.rs, x509/tests/trust_anchor_format.rs
This PR derives implementations for x509 types. I have taken great care to ensure that every commit passes all existing tests. This PR is the early portion of the larger #414 PR.
=> x509: derive all implementations

.github/workflows/base16ct.yml, .github/workflows/base64ct.yml, .github/workflows/const-oid.yml, .github/workflows/der.yml, .github/workflows/pem-rfc7468.yml, .github/workflows/pkcs1.yml, .github/workflows/pkcs10.yml, .github/workflows/pkcs5.yml, .github/workflows/pkcs7.yml, .github/workflows/pkcs8.yml, .github/workflows/sec1.yml, .github/workflows/spki.yml, .github/workflows/ssh-key.yml, .github/workflows/tai64.yml, .github/workflows/tls_codec.yml, .github/workflows/x501.yml, .github/workflows/x509.yml, Cargo.lock, Cargo.toml, der/Cargo.toml, der/derive/Cargo.toml, der/tests/derive.rs, pkcs5/Cargo.toml, sec1/Cargo.toml, tls_codec/Cargo.toml, tls_codec/derive/Cargo.toml
All fixed crates except `tls_codec(_derive)` are on the pre versions, so I haven't mentioned the fix in changelogs.
@tarcieri
I will leave for you to decide whether a patch release for `tls_codec` is needed or not.
Closes #439
=> Fix and test min versions build

.github/workflows/base16ct.yml, .github/workflows/base64ct.yml, Cargo.lock
Benches build is now checked as part of `minimal-versions`.
=> Remove benches build from workflows

tls_codec/Cargo.toml, tls_codec/benches/quic_vec.rs, tls_codec/derive/tests/decode.rs, tls_codec/src/lib.rs, tls_codec/src/primitives.rs, tls_codec/src/quic_vec.rs, tls_codec/src/tls_vec.rs, tls_codec/tests/decode.rs, tls_codec/tests/encode.rs
This implements the variable-length integer encoding from [RFC 9000] (quic) used to serialize variable-length vectors in quic and in [MLS].
It's opinionated because it doesn't allow anything longer than `u16::MAX` when deserialising (same as the other vectors), and it requires minimum lengths like MLS (unlike quic).
cc @kkohbrok @raphaelrobert if one of you wants to have a look at this.
[rfc 9000]: https://www.rfc-editor.org/rfc/rfc9000.html#name-variable-length-integer-enc
[mls]: https://messaginglayersecurity.rocks/mls-protocol/draft-ietf-mls-protocol.html#name-variable-size-vector-header
=> tls codec: variable-length vectors

spki/src/algorithm.rs
=> Add AlgorithmIdentifier::oids() helper function

der/src/asn1/integer/uint.rs
The previous implementation used `saturating_sub` rather than `checked_sub` to compute the number of leading zeroes to use, which would cause a panic if the input exceeded the output (see #446).
This commit switches to `checked_sub`, returning `ErrorKind::Length` in the event the output buffer is too small for the given input. It also adds unit tests for this behavior as well as the happy paths.
=> der: fix handling of oversized unsigned `INTEGER` inputs

der/src/asn1/integer/uint.rs
Covers a noncanonical extra zero as well as a needed missing zero
=> der: add additional tests for unsigned integer decoding

spki/src/algorithm.rs
This enables AlgorithmIdentifier to be decoded from an Any type.
=> fix: impl DecodeValue for AlgorithmIdentifier

der/derive/src/lib.rs, der/derive/src/newtype.rs, der/tests/derive.rs
There are a number of der types that could benefit from wrapping in a
newtype. For example, `RelativeDistinguishedName` could benefit from
an `impl Display` to convert it to a string representation. But because
it is just `Vec<AttributeTypeAndValue>` we can't really do this.
Having a systematic way to derive newtypes in these cases is thus
beneficial.
=> feat: add new NewType derive

ssh-key/Cargo.toml, ssh-key/README.md, ssh-key/src/authorized_keys.rs, ssh-key/src/error.rs, ssh-key/src/lib.rs, ssh-key/src/public.rs, ssh-key/tests/authorized_keys.rs, ssh-key/tests/examples/authorized_keys
Adds a parser for `authorized_keys` files which contain a list of SSH public keys each predicated by option flags.
=> ssh-key: `AuthorizedKeys` parser

ssh-key/src/authorized_keys.rs, ssh-key/tests/authorized_keys.rs
Adds a type for modeling the "options" field of the `authorized_keys` file, which parses comma-delimited strings while incorporating basic quoting logic.
The `Options` type is an iterator over comma-separated `str` and performs an eager first-pass iteration to ensure the contents are valid and can be iterated over infallibly.
=> ssh-key: `authorized_keys::Options` type

base64ct/src/decoder.rs, base64ct/src/encoder.rs, base64ct/src/lib.rs, base64ct/src/line_ending.rs, pem-rfc7468/src/encoder.rs, pem-rfc7468/src/lib.rs
Adds support for buffered incremental Base64 encoding which inserts newline characters at a specified line width.
This commit also moves the `LineEnding` type previously defined in `pem-rfc7468` into `base64ct`, and re-exporting it.
=> base64ct: add linewrapping support to `Encoder`

const-oid/oiddbgen/rfc5911.txt, const-oid/oiddbgen/rfc5912.txt, const-oid/oiddbgen/rfc6268.txt, const-oid/oiddbgen/rfc7107.txt, const-oid/oiddbgen/rfc7299.txt, const-oid/oiddbgen/src/asn1.rs, const-oid/oiddbgen/src/main.rs, const-oid/src/db/gen.rs
* RFC 5911
* RFC 5912
* RFC 6268
* RFC 7107
* RFC 7299
=> feat(const-oid): add additional RFCs to the OID DB

base64ct/src/encoder.rs
Allows buffered Base64 encoding using the `io::Write` trait.
=> base64ct: feature-gated `io::Write` impl for `Encoder`

const-oid/src/arcs.rs, const-oid/src/lib.rs
Consolidates the logic in `ObjectIdentifier::from_bytes` and the `Arcs` type, allowing `Arcs` to be used to make a first pass to ensure that an OID is well-formed.
=> const-oid: use `Arcs` to validate OID well-formedness

pem-rfc7468/src/decoder.rs, pem-rfc7468/src/encoder.rs, pem-rfc7468/src/error.rs
Allows using the `std::io` API to encode data as PEM.
=> pem-rfc7468: impl `io::Write` for `Encoder`

spki/src/algorithm.rs
=> feat(spki): impl PartialOrd for AlgorithmIdentifier

pem-rfc7468/src/encoder.rs, pem-rfc7468/src/error.rs
Changes the return type of `encode` from `[u8]` to `str`.
It's easy to go the other direction with `.as_bytes()`.
=> pem-rfc7468: return `str` from `encode`

pem-rfc7468/src/decoder.rs, ssh-key/src/algorithm.rs, ssh-key/src/base64.rs, ssh-key/src/mpint.rs, ssh-key/src/private.rs, ssh-key/src/private/ecdsa.rs, ssh-key/src/private/ed25519.rs, ssh-key/src/public.rs, ssh-key/src/public/ecdsa.rs, ssh-key/src/public/ed25519.rs
Implements the SSH key wire format in terms of traits rather than newtypes.
Traits can be used with either the raw Base64 or PEM encoders.
=> ssh-key: factor out `DecoderExt`/`EncoderExt` traits

ssh-key/src/algorithm.rs, ssh-key/src/base64.rs, ssh-key/src/mpint.rs, ssh-key/src/private.rs, ssh-key/src/private/dsa.rs, ssh-key/src/private/ecdsa.rs, ssh-key/src/private/ed25519.rs, ssh-key/src/private/rsa.rs, ssh-key/src/public.rs, ssh-key/src/public/dsa.rs, ssh-key/src/public/ecdsa.rs, ssh-key/src/public/ed25519.rs, ssh-key/src/public/openssh.rs, ssh-key/src/public/rsa.rs
Changes the `Decode` and `Encode` traits to accept `impl DecoderExt`/`impl EncoderExt` (respectively) as parameters.
This abstracts over the decoder/encoder type, which may be raw Base64 (as used by public keys) or PEM (as used by private keys).
=> ssh-key: trait-based decoder/encoder

ssh-key/src/private.rs, ssh-key/src/private/dsa.rs, ssh-key/src/private/ed25519.rs, ssh-key/src/private/rsa.rs
Support for getting the `PublicKey` associated with a `PrivateKey`, along with `From` conversions between them and the various intermediate types.
=> ssh-key: add `PrivateKey::public_key` and `From` conversions

const-oid/oiddbgen/src/asn1.rs, const-oid/src/db/gen.rs
Some of these branch nodes are actually used for types.
=> fix(oiddb): don't filter out branch nodes

x509/src/attr.rs, x509/src/name.rs, x509/tests/certificate.rs, x509/tests/certreq.rs, x509/tests/name.rs, x509/tests/pkix_extensions.rs, x509/tests/trust_anchor_format.rs
The main commit is the last one. The previous commits are just enablement.
This PR depends on:
Resolves: #417
=> feat(x509): implement RFC 4514 string serialization for x509 names

x509/src/anchor.rs, x509/src/lib.rs, x509/src/time.rs
Also, clean up the types they warn about.
=> chore(x509): enable unused_lifetimes and unused_qualifications lints

Cargo.lock, pem-rfc7468/src/encoder.rs, pem-rfc7468/src/error.rs, pem-rfc7468/src/lib.rs, ssh-key/Cargo.toml, ssh-key/src/algorithm.rs, ssh-key/src/base64.rs, ssh-key/src/error.rs, ssh-key/src/lib.rs, ssh-key/src/mpint.rs, ssh-key/src/private.rs, ssh-key/src/private/dsa.rs, ssh-key/src/private/ecdsa.rs, ssh-key/src/private/ed25519.rs, ssh-key/src/private/rsa.rs, ssh-key/src/public.rs, ssh-key/src/public/dsa.rs, ssh-key/src/public/rsa.rs, ssh-key/tests/private_key.rs
Support for encoding OpenSSH private keys in PEM format
=> ssh-key: private key encoder

Cargo.lock, base64ct/CHANGELOG.md, base64ct/Cargo.toml, base64ct/src/lib.rs, pem-rfc7468/Cargo.toml, spki/Cargo.toml, ssh-key/Cargo.toml
- Buffered `Encoder` type ([#366], [#455], [#457])
- `Decoder::decoded_len` method ([#403])
- Impl `std::io::Read` for `Decoder` ([#404])
- Bounds for `Encoding`/`Variant` ZSTs ([#405], [#408])
[#366]: https://github.com/RustCrypto/formats/pull/366
[#403]: https://github.com/RustCrypto/formats/pull/403
[#404]: https://github.com/RustCrypto/formats/pull/404
[#405]: https://github.com/RustCrypto/formats/pull/405
[#408]: https://github.com/RustCrypto/formats/pull/408
[#455]: https://github.com/RustCrypto/formats/pull/455
[#457]: https://github.com/RustCrypto/formats/pull/457
=> base64ct v1.4.0

ssh-key/README.md, ssh-key/src/base64.rs, ssh-key/src/lib.rs, ssh-key/src/private.rs, ssh-key/src/public.rs, ssh-key/tests/authorized_keys.rs, ssh-key/tests/private_key.rs, ssh-key/tests/public_key.rs
Replaces direct field access with accessor methods.
This helps smooth out the absence of heap-allocated comments when the `alloc` feature isn't enabled.
=> ssh-key: make `PublicKey`/`PrivateKey` fields private

base64ct/src/decoder.rs, base64ct/tests/proptests.rs, pem-rfc7468/src/decoder.rs, ssh-key/src/base64.rs, ssh-key/src/private.rs
This is technically a breaking change, but this method was only just introduced in the v1.4.0 release which occurred less than 24h ago, so changing things now, yanking that release, and cutting a replacement v1.4.1 release should hopefully not cause any real-world breakages.
In using this method it felt confusingly named: it returns the number of bytes of as-yet-to-be-decoded data, but the "decoded" name implies past tense, which feels more like it's returning the number of bytes which have been decoded so far.
It *would* be useful to have such a method as well which tracks the current cursor/position within the decoded output, but adding one would be rather confusing as `decoded_len` would be a good candidate for *that* name.
=> base64ct: rename `Decoder::decoded_len` => `::remaining_len`

Cargo.lock, base64ct/CHANGELOG.md, base64ct/Cargo.toml, base64ct/src/lib.rs
- Rename `Decoder::decoded_len` => `::remaining_len` ([#500])
[#500]: https://github.com/RustCrypto/formats/pull/500
=> base64ct v1.4.1

ssh-key/src/algorithm.rs, ssh-key/src/authorized_keys.rs, ssh-key/src/lib.rs, ssh-key/src/private.rs, ssh-key/tests/authorized_keys.rs
Owned types are easier to work with.
This commit retains the config options parser in a heapless mode but requires `alloc` to actually store them.
Since they were the only borrowed part of `authorized_key::Entry`, it can become owned as well.
This allows `AuthorizedKeys::read_file` to return a `Vec<Entry>` rather than taking a callback that borrows a string.
=> ssh-key: make `authorized_keys` types owned

const-oid/src/encoder.rs, const-oid/src/lib.rs, const-oid/tests/lib.rs
=> const-oid: add `ObjectIdentifier::push_arc`

const-oid/src/lib.rs, const-oid/tests/lib.rs
Adds a method for getting the parent of a given OID in the hierarchy.
This also changes the `ObjectIdentifier::from_arcs` method to take `Arc`s by value rather than reference.
=> const-oid: add `ObjectIdentifier::parent`

Cargo.lock, der/Cargo.toml, der/derive/Cargo.toml, der/src/lib.rs, pem-rfc7468/Cargo.toml, pem-rfc7468/src/lib.rs, pkcs1/Cargo.toml, pkcs5/Cargo.toml, pkcs7/Cargo.toml, pkcs8/Cargo.toml, sec1/Cargo.toml, spki/Cargo.toml, spki/src/lib.rs, ssh-key/Cargo.toml, x509/Cargo.toml
This bumps the prerelease versions for the following crates:
der
der_derive
pem-rfc7468
spki
=> chore: bump crate prerelease versions

Cargo.lock, der/Cargo.toml, pem-rfc7468/CHANGELOG.md, pem-rfc7468/Cargo.toml, pem-rfc7468/src/lib.rs, ssh-key/Cargo.toml
- Buffered `Decoder` type ([#406])
- Buffered `Encoder` type ([#463], [#474])
- Return `str` from `encode` ([#482])
[#406]: https://github.com/RustCrypto/formats/pull/406
[#463]: https://github.com/RustCrypto/formats/pull/463
[#474]: https://github.com/RustCrypto/formats/pull/474
[#482]: https://github.com/RustCrypto/formats/pull/482
=> pem-rfc7468 v0.4.0

Cargo.lock, ssh-key/Cargo.toml, ssh-key/src/algorithm.rs, ssh-key/src/decoder.rs, ssh-key/src/encoder.rs, ssh-key/src/fingerprint.rs, ssh-key/src/lib.rs, ssh-key/src/private.rs, ssh-key/src/private/ecdsa.rs, ssh-key/src/private/ed25519.rs, ssh-key/src/public.rs, ssh-key/src/public/ed25519.rs, ssh-key/tests/public_key.rs
Optional support for computing SHA-256 fingerprints of keys.
Uses the `Encoder` trait to write data to `Sha256`, allowing OTF computation of key fingerprints.
=> ssh-key: SHA-256 fingerprint support

ssh-key/README.md, ssh-key/src/public.rs, ssh-key/tests/public_key.rs
The only errors that occur in this calculation would represent bugs in the `ssh-key` crate itself.
For anyone wanting a panic-free solution, there is still an impl of `TryFrom<PublicKey>` for `Fingerprint` and `Sha256Fingerprint`.
=> ssh-key: make `PublicKey::fingerprint` infallible

Cargo.lock, ssh-key/CHANGELOG.md, ssh-key/Cargo.toml, ssh-key/src/lib.rs
- `FromStr` impls for key types ([#368])
- `PublicKey` encoder ([#369], [#371], [#372], [#373])
- `AuthorizedKeys` parser ([#452])
- `PrivateKey::public_key` and `From` conversions ([#485])
- `PrivateKey` encoder ([#494])
- Validate private key padding bytes ([#495])
- File I/O methods for `PrivateKey` and `PublicKey` ([#494], [#503])
- SHA-256 fingerprint support ([#513])
- Use `pem-rfc7468` for private key PEM parser ([#407])
- Make `PublicKey`/`PrivateKey` fields private ([#498])
[#368]: https://github.com/RustCrypto/formats/pull/368
[#369]: https://github.com/RustCrypto/formats/pull/369
[#371]: https://github.com/RustCrypto/formats/pull/371
[#372]: https://github.com/RustCrypto/formats/pull/372
[#373]: https://github.com/RustCrypto/formats/pull/373
[#407]: …
=> ssh-key v0.3.0

sec1/Cargo.toml, sec1/src/lib.rs, ssh-key/Cargo.toml
This allows users who aren't using EncodedPoint to omit dependencies on generic-array, typenum, and version_check.
=> feat(sec1): add default cargo feature for disabling point module

der/src/decode.rs, der/src/lib.rs
Adds a marker trait for types which can be `der::Decode`d without borrowing any data from the input.
It's useful for cases where borrowing from the input isn't possible. For example, if we were to add on-the-fly PEM decoding as proposed in #525.
Inspired by the [`DeserializeOwned`](https://docs.rs/serde/latest/serde/de/trait.DeserializeOwned.html) trait from `serde`.
=> der: add `DecodeOwned` marker trait

.github/workflows/workspace.yml, base64ct/src/decoder.rs, base64ct/src/encoder.rs, der/src/asn1/utf8_string.rs, der/src/decode.rs, der/src/encode.rs, pkcs1/src/traits.rs, pkcs5/src/lib.rs, ssh-key/src/fingerprint.rs
Ensures `cargo doc --all-features` runs successfully without warnings
=> CI: add workspace-level `doc` tests

Cargo.lock, crypto-serde/Cargo.toml, crypto-serde/tests/bincode.rs, crypto-serde/tests/cbor.rs, crypto-serde/tests/json.rs
Adds initial proptests which ensure that randomly generated inputs round trip back to their original values
=> crypto-serde: proptests

crypto-serde/Cargo.toml, crypto-serde/src/lib.rs, crypto-serde/tests/bincode.rs, crypto-serde/tests/cbor.rs, crypto-serde/tests/json.rs, crypto-serde/tests/toml.rs
Adds a baseline heapless `no_std` profile which is capable of serializing binary data without `alloc`.
=> crypto-serde: `alloc` feature

ssh-key/src/private.rs, ssh-key/tests/encrypted_private_key.rs
#535 implemented a decoder for encrypted private keys.
This PR adds encoder support.
=> ssh-key: encrypted private key encoding support

ssh-key/src/algorithm.rs, ssh-key/src/kdf.rs, ssh-key/src/lib.rs, ssh-key/src/private.rs, ssh-key/tests/encrypted_private_key.rs
Support for parsing bcrypt-pbkdf's KDF options into `KdfOpts::Bcrypt` and encoding them into an output private key document
=> ssh-key: bcrypt-pbkdf KDF options decoder/encoder

Cargo.lock, pkcs5/src/pbes2.rs, pkcs5/src/pbes2/kdf.rs, ssh-key/Cargo.toml, ssh-key/src/algorithm.rs, ssh-key/src/decoder.rs, ssh-key/src/error.rs, ssh-key/src/kdf.rs, ssh-key/src/private.rs, ssh-key/src/public.rs, ssh-key/tests/encrypted_private_key.rs
Preliminary support for decrypting encrypted OpenSSH private keys, with support for `bcrypt-pbkdf` as the KDF and `aes256-ctr` as the encryption cipher.
Tested against an example encrypted private key (`id_ed25519.enc`) produced using the `ssh-keygen` utility:
$ ssh-keygen -p -f id_ed25519
=> ssh-key: private key decryption support

ssh-key/src/kdf.rs, ssh-key/src/lib.rs, ssh-key/src/private.rs, ssh-key/tests/encrypted_private_key.rs, ssh-key/tests/private_key.rs
Since the KDF algorithm and options are located side-by-side in private keys, and this crate models them as effectively a single `enum`, this commit makes that a first-class arrangement, combining the two into a unified `pub enum Kdf`.
This allows the enum to impl the `Decode` trait proper.
Internally it still decodes/encodes a `KdfAlg`, however it only uses it to select the enum variant and inform the KDF options decoding.
=> ssh-key: consolidate `KdfAlg` and `KdfOpts` into `Kdf`

ssh-key/src/private.rs, ssh-key/tests/encrypted_private_key.rs, ssh-key/tests/private_key.rs, ssh-key/tests/public_key.rs
- Removes `PrivateKey::kdf_alg` in favor of `.kdf().algorithm()`
- Removes "ossh_"/"OSSH_" prefixes from test fixtures
=> ssh-key: various naming fixups

ssh-key/src/algorithm.rs, ssh-key/src/cipher.rs, ssh-key/src/lib.rs, ssh-key/src/private.rs, ssh-key/tests/encrypted_private_key.rs, ssh-key/tests/private_key.rs
- Renames the type to `Cipher`
- Models the property of `PrivateKey` as `Option<Cipher>`. This eliminates the need to return `Option` from every method as the type always represents a valid cipher.
- Extracts `Cipher` into a `cipher` module
- Move decryption-related functionality into `Cipher::decrypt`
=> ssh-key: rename `CipherAlg` => `Cipher`; refactoring

.github/workflows/ssh-key.yml, Cargo.lock, ssh-key/Cargo.toml, ssh-key/README.md, ssh-key/src/algorithm.rs, ssh-key/src/cipher.rs, ssh-key/src/encoder.rs, ssh-key/src/kdf.rs, ssh-key/src/lib.rs, ssh-key/src/private.rs, ssh-key/tests/encrypted_private_key.rs
Support for encrypting an unencrypted SSH private key using the default recommended algorithms:
- Cipher: `aes256-ctr`
- KDF: `bcrypt` (i.e. bcrypt-pbkdf)
=> ssh-key: private key encryption support

Cargo.lock, ssh-key/src/decoder.rs, ssh-key/src/encoder.rs, ssh-key/src/kdf.rs, ssh-key/src/private.rs, ssh-key/src/private/ecdsa.rs, ssh-key/src/private/ed25519.rs, ssh-key/src/public/ed25519.rs
Adds a helper method for decoding length-prefixed data which calls a provided decoder function/closure and then afterward validates that the correct amount of data was read.
This could potentially be adapted to use a special decoder wrapper which enforces that data can't be read past the end of the buffer, but for now it uses a late check after the inner decoder function is finished.
=> ssh-key: add `Decoder::decode_length_prefixed`

ssh-key/src/algorithm.rs, ssh-key/src/cipher.rs, ssh-key/src/encoder.rs, ssh-key/src/kdf.rs, ssh-key/src/private.rs, ssh-key/src/private/rsa.rs, ssh-key/src/public.rs, ssh-key/tests/encrypted_private_key.rs, ssh-key/tests/private_key.rs
It was originally removed in #544, replacing it with `Option<Cipher>`, however there are various properties it'd be nice to attach to `Cipher` which can't be modeled with an `Option`, namely the block size.
=> ssh-key: add back `Cipher::None` variant

ssh-key/src/algorithm.rs, ssh-key/src/authorized_keys.rs, ssh-key/src/cipher.rs, ssh-key/src/encoder.rs, ssh-key/src/kdf.rs, ssh-key/src/lib.rs, ssh-key/src/mpint.rs, ssh-key/src/private.rs, ssh-key/src/private/dsa.rs, ssh-key/src/private/ecdsa.rs, ssh-key/src/private/ed25519.rs, ssh-key/src/private/rsa.rs, ssh-key/src/public/dsa.rs, ssh-key/src/public/ecdsa.rs, ssh-key/src/public/ed25519.rs, ssh-key/src/public/openssh.rs, ssh-key/src/public/rsa.rs
Code is now warning-free under the `clippy::integer_arithmetic` lint.
Additionally adds a check that decoded ciphertexts are properly aligned to the expected block size.
=> ssh-key: enforce checked arithmetic

ssh-key/src/private.rs, ssh-key/src/private/keypair.rs
The `private` module it was previously inside of had grown quite large.
=> ssh-key: factor `KeypairData` into its own module

Cargo.lock, ssh-key/Cargo.toml, ssh-key/README.md, ssh-key/src/lib.rs, ssh-key/src/private.rs, ssh-key/src/private/ed25519.rs, ssh-key/src/private/keypair.rs, ssh-key/src/public.rs, ssh-key/src/public/ed25519.rs
Support for converting the following types:
- `Ed25519PrivateKey` <=> `ed25519_dalek::SecretKey`
- `Ed25519PublicKey`  <=> `ed25519_dalek::PublicKey`
- `Ed25519Keypair`    <=> `ed25519_dalek::Keypair`
Also adds `PrivateKey::random_ed25519` to support generating random Ed25519 keys.
=> ssh-key: integration with `ed25519-dalek`

der/src/asn1/real.rs, der/src/lib.rs
Enable the available static analysis that `clippy` provides to ensure the crate is free of macros that cause panics.
=> der: enable clippy's panic lints

base64ct/src/decoder.rs, base64ct/src/encoder.rs, base64ct/src/encoding.rs, base64ct/src/lib.rs, base64ct/src/variant.rs
Ensures that (almost) all arithmetic is checked.
The lint is disabled in several places that need further review. Each of these places has an accompanying TODO.
=> base64ct: add `clippy::integer_arithmetic` lint

ssh-key/src/algorithm.rs, ssh-key/src/checked.rs, ssh-key/src/kdf.rs, ssh-key/src/lib.rs, ssh-key/src/mpint.rs, ssh-key/src/private.rs, ssh-key/src/private/dsa.rs, ssh-key/src/private/ecdsa.rs, ssh-key/src/private/ed25519.rs, ssh-key/src/private/keypair.rs, ssh-key/src/private/rsa.rs, ssh-key/src/public.rs, ssh-key/src/public/dsa.rs, ssh-key/src/public/ecdsa.rs, ssh-key/src/public/ed25519.rs, ssh-key/src/public/rsa.rs
Simplifies performing checked arithmetic of `usize`. In the context of this crate, it's primarily useful for clarity and eliminating boilerplate when summing multiple lengths.
=> ssh-key: add internal `CheckedSum` trait

const-oid/src/arcs.rs, const-oid/src/checked.rs, const-oid/src/db.rs, const-oid/src/encoder.rs, const-oid/src/error.rs, const-oid/src/lib.rs, const-oid/src/parser.rs
Enforces checked arithmetic (where possible) and that production builds don't use panicking macros.
For now some of the arithmetic is annotated with an explicit allow, along with an explanation of why it shouldn't overflow.
=> const-oid: add clippy lints for checked arithmetic and panics

base64ct/src/decoder.rs, base64ct/src/encoder.rs, base64ct/src/encoding.rs
The `Encoding` trait defines this crate's public API, however internally it's implemented in terms of `Variant`.
`Variant` is a sealed trait. Previously it was exposed as the bound on the generic parameter of `Decoder` and `Encoder`.
This is technically a breaking change but it theoretically corrects a deficiency/bug: it was technically possible before for a user of `base64ct` to impl the `Encoding` trait themselves. But this was never intended to be supported, and in theory adding this bound on a sealed trait should both otherwise get the sealed trait out of the public API as well as ensuring that nothing but `base64ct` itself can impl `Encoding`.
=> base64ct: bound `Encoding` on `Variant`

Cargo.lock, base64ct/CHANGELOG.md, base64ct/Cargo.toml
- Ensure checked arithmetic with `clippy::integer_arithmetic` lint ([#557])
- Prevent foreign impls of `Encoding` by bounding on sealed `Variant` trait ([#562])
[#557]: https://github.com/RustCrypto/formats/pull/557
[#562]: https://github.com/RustCrypto/formats/pull/562
=> base64ct v1.5.0

Cargo.lock, der/Cargo.toml, pem-rfc7468/Cargo.toml, pem-rfc7468/src/decoder.rs, pem-rfc7468/src/encoder.rs, pem-rfc7468/src/grammar.rs, pem-rfc7468/src/lib.rs, ssh-key/Cargo.toml, ssh-key/src/private.rs
Enforces checked arithmetic (where possible) and that production builds don't use panicking macros.
This is a breaking change because it makes previously infallible length calculation functions infallible, so it bumps the version to v0.5.0-pre.
=> pem-rfc7468:  add clippy lints for checked arithmetic and panics

pem-rfc7468/src/encoder.rs, pem-rfc7468/src/lib.rs
There's a unsafety versus sidechannel resistence tradeoff in converting PEM output by the `Encoder` type to a `str` (which performs branch-heavy UTF-8 validity checks).
This commit introduces a tiny bit of `unsafe` code (the very first `unsafe` code in this crate) to bypass these checks.
In their place, there is both a `debug_assert!` which performs the full `str::from_utf8` check when `debug_assertions` are enabled, as well as an always-on constant time-ish runtime check to ensure characters in the output document are all in the 7-bit ASCII set.
=> pem-rfc7468: use `str::from_utf8_unchecked` in `encode`

Cargo.lock, der/Cargo.toml, pem-rfc7468/CHANGELOG.md, pem-rfc7468/Cargo.toml, ssh-key/Cargo.toml
- Clippy lints for checked arithmetic and panics ([#564])
- Use `str::from_utf8_unchecked` in `encode` ([#565])
[#564]: https://github.com/RustCrypto/formats/pull/564
[#565]: https://github.com/RustCrypto/formats/pull/565
=> pem-rfc7468 v0.5.0

base64ct/src/encoding.rs
Adds a list of types which impl the `Encoding` trait
=> base64ct: add `Encoding` docs

der/src/document.rs, pem-rfc7468/src/lib.rs, pkcs1/src/private_key/document.rs, pkcs1/src/public_key/document.rs, pkcs8/src/document/encrypted_private_key.rs, pkcs8/src/document/private_key.rs, sec1/src/private_key/document.rs, spki/src/document.rs, ssh-key/src/private.rs, x509/src/certificate/document.rs
It's more intuitive for the names to match, and also clearer that the label is PEM-related.
=> pem-rfc7468: rename `PemLabel::TYPE_LABEL` => `::PEM_LABEL`

ssh-key/README.md, ssh-key/src/algorithm.rs, ssh-key/src/cipher.rs
This commit does *NOT* actually implement support for the FIDO/U2F key formats as described in:
https://cvsweb.openbsd.org/src/usr.bin/ssh/PROTOCOL.u2f?annotate=HEAD
Instead, it only adds support for the algorithm and certificate names to the `Algorithm` and `CertificateAlg` enums:
- `sk-ecdsa-sha2-nistp256@openssh.com`
- `sk-ecdsa-sha2-nistp256-cert-v01@openssh.com`
- `sk-ssh-ed25519@openssh.com`
- `sk-ssh-ed25519-cert-v01@openssh.com`
Actual support for these algorithms remains to be implemented.
=> ssh-key: add FIDO/U2F algorithms to algorithm registry

ssh-key/src/private.rs, ssh-key/src/private/keypair.rs, ssh-key/src/public.rs, ssh-key/src/public/dsa.rs, ssh-key/src/public/rsa.rs
This commit adds support for storing the "checkint" for a private key in the `PrivateKey` type. This makes it possible to reserialize a decoded private key byte-for-byte.
Additionally, encryption and random key generation now generate a random "checkint".
The fallback deterministic method is moved from the public to private key, ensuring that a "checkint" is always secret. This should help prevent hypothetical bitflipping attacks which would be possible if the deterministic checkint were computed from public data.
=> ssh-key: private key checkint improvements

ssh-key/src/certificate.rs, ssh-key/src/encoder.rs, ssh-key/src/public.rs, ssh-key/tests/certificate.rs
Support for encoding OpenSSH certificates from the `Certificate` type.
=> ssh-key: preliminary certificate encoder support

der/src/arrayvec.rs, der/src/asn1/bit_string.rs, der/src/asn1/generalized_time.rs, der/src/asn1/integer/uint.rs, der/src/asn1/real.rs, der/src/asn1/set_of.rs, der/src/asn1/utc_time.rs, der/src/datetime.rs, der/src/error.rs, der/src/length.rs, der/src/lib.rs, der/src/tag.rs, der/src/tag/class.rs
Enables the following lints globally:
- `clippy::cast_lossless`
- `clippy::cast_possible_truncation`
- `clippy::cast_possible_wrap`
- `clippy::cast_precision_loss`
- `clippy::cast_sign_loss`
- `clippy::checked_conversions`
- `clippy::implicit_saturating_sub`
- `clippy::integer_arithmetic`
Some code related to datetime-handling and ASN.1 REAL has been grandfathered in and allows these lints, although it's been labeled with TODOs to convert it to checked arithmetic.
=> der: enable arithmetic and casting clippy lints

ssh-key/Cargo.toml, ssh-key/README.md, ssh-key/src/signature.rs
Adds RFC citations for signature formats
=> ssh-key: additional `Signature` documentation

ssh-key/src/algorithm.rs, ssh-key/src/certificate.rs, ssh-key/src/decoder.rs, ssh-key/src/encoder.rs, ssh-key/src/kdf.rs, ssh-key/src/mpint.rs, ssh-key/src/private.rs, ssh-key/src/private/ecdsa.rs, ssh-key/src/private/ed25519.rs, ssh-key/src/private/keypair.rs, ssh-key/src/public.rs, ssh-key/src/public/ecdsa.rs, ssh-key/src/public/ed25519.rs, ssh-key/src/signature.rs, ssh-key/tests/private_key.rs
Refactors encoding to be trait-based, removing most of the previous inherent methods on `Decoder` and `Encoder` and replacing them with impls of the `Encode` and `Decode` traits on the respective types.
=> ssh-key: refactor encoder/decoder

Cargo.lock, ssh-key/Cargo.toml, ssh-key/src/algorithm.rs, ssh-key/src/certificate.rs, ssh-key/src/lib.rs, ssh-key/src/private.rs, ssh-key/src/private/ecdsa.rs, ssh-key/src/private/keypair.rs, ssh-key/src/public.rs, ssh-key/src/public/ecdsa.rs, ssh-key/src/signature.rs, ssh-key/tests/certificate.rs, ssh-key/tests/private_key.rs, ssh-key/tests/public_key.rs
Support for parsing RFC8332-flavored RSASSA-PKCS#1v1.5 signatures on OpenSSH certificates.
Implementing this required further paramaterizing the `Algorithm` enum around a `HashAlg` associated with the `Algorithm::Rsa` variant. Separately, the `CertificateAlg` type was folded into `Algorithm`, which now also supports certificate-specific decoding/encoding functions.
Additionally, the `Signature` type has changed from an enum to a struct, which carries an algorithm and the signature data serialized as a byte vector.
=> ssh-key: RSA signature support

Cargo.lock, ssh-key/Cargo.toml, ssh-key/README.md, ssh-key/src/certificate.rs, ssh-key/src/lib.rs, ssh-key/src/public.rs, ssh-key/src/public/key_data.rs, ssh-key/tests/certificate.rs, ssh-key/tests/private_key.rs
Support for serializing/deserializing `Certificate` and `PublicKey` using `serde`'s traits.
Uses the OpenSSH string serialization with human-readable formats, and the binary serialization with binary formats.
=> ssh-key: initial `serde` support

ssh-key/src/certificate.rs, ssh-key/src/private.rs
Rely on nested calls to `Encode::encoded_len` more heavily when calculating lengths, leaving fewer commented literals to explain how the length calculations work.
=> ssh-key: length calculation improvements

ssh-key/src/public.rs, ssh-key/src/public/key_data.rs, ssh-key/src/public/sk.rs, ssh-key/tests/certificate.rs, ssh-key/tests/public_key.rs
Factors out Security Key (FIDO/U2F) types which can store the associated `application` string when the `alloc` feature is enabled.
=> ssh-key: factor out `public::Sk*` types

ssh-key/README.md, ssh-key/src/decode.rs, ssh-key/src/encode.rs, ssh-key/src/private.rs, ssh-key/src/private/dsa.rs, ssh-key/src/private/ecdsa.rs, ssh-key/src/private/keypair.rs, ssh-key/src/private/rsa.rs, ssh-key/src/private/sk.rs, ssh-key/src/public/sk.rs
The `sk-*` algorithms support a "private" key format which includes some additional information including flags and a key handle. Note that the actual private key lives on or is derived by the Security Key hardware token itself.
This commit adds decoding/encoding support for these formats.
=> ssh-key: FIDO/U2F "private" key support

ssh-key/src/certificate.rs, ssh-key/src/error.rs, ssh-key/src/private.rs, ssh-key/src/public.rs, ssh-key/src/reader.rs
- Adds `Reader::finish` method which checks all data has been consumed
- Adds `Error::TrailingData` with a `remaining` field which returns the number of bytes of unexpected trailing data at the end of the input
- Impls `PrivateKey` encoding in terms of the `Decode`/`Encode` traits
- Adds `PrivateKey::{from_bytes, to_bytes}`
- Adds `Certificate::{read_file, write_file}
=> ssh-key: encoding improvements

Cargo.lock, ssh-key/Cargo.toml, ssh-key/README.md, ssh-key/src/algorithm.rs, ssh-key/src/certificate.rs, ssh-key/src/certificate/builder.rs, ssh-key/src/certificate/cert_type.rs, ssh-key/src/certificate/options_map.rs, ssh-key/src/certificate/signing_key.rs, ssh-key/src/error.rs, ssh-key/src/private.rs, ssh-key/src/public.rs, ssh-key/src/signature.rs, ssh-key/tests/certificate_builder.rs
Adds a builder/signer type for `ssh_key::Certificate` which is able to sign OpenSSH certificates as a certificate authority.
Currently Ed25519 only.
=> ssh-key: `certificate::Builder` (i.e. SSH CA support)

ssh-key/src/algorithm.rs, ssh-key/src/certificate.rs, ssh-key/src/certificate/builder.rs, ssh-key/src/fingerprint.rs, ssh-key/src/lib.rs, ssh-key/src/private.rs, ssh-key/src/public.rs, ssh-key/src/public/key_data.rs, ssh-key/src/writer.rs, ssh-key/tests/certificate.rs, ssh-key/tests/certificate_builder.rs, ssh-key/tests/public_key.rs
Simplifies and unifies the fingerprint implementation into a single `Fingerprint` enum type which makes it simple to plug in new hash functions.
Also adds SHA-512 support, which makes it possible for the fingerprint methods to be infallible.
=> ssh-key: fingerprint simplification + SHA-512 support

ssh-key/README.md, ssh-key/src/certificate.rs, ssh-key/src/fingerprint.rs, ssh-key/src/lib.rs, ssh-key/src/public.rs
Support for serializing OpenSSH fingerprints using `serde`.
Additionally includes documentation improvements.
=> ssh-key: `serde` support for `Fingerprint`

der/derive/src/sequence/field.rs, der/src/asn1.rs, der/src/asn1/context_specific.rs, der/src/asn1/optional.rs, der/src/encode_ref.rs, der/src/encoder.rs, der/src/lib.rs
Closes #527.
Adds generic wrapper types for encoding references to types which impl encoding traits:
- `EncodeRef`: impls `Encode` for &T where T: `Encode`
- `EncodeValueRef`: impls `EncodeValue` and `Tagged` for &T
This, in conjunction with impls for `&Option<T>`, eliminates the need to have a dedicated `OptionalRef` type.
The `ContextSpecificRef` type is retained as it's a useful constructor for use in proc macros.
All in all it would be nice to have a better solution like this, like a blanket impl of `Encode` for &T where T: `Encode`. That's a direction which may still be worth exploring, but in the meantime the wrapper types mean there's a generic solution for reference type encoding.
=> der: add `EncodeRef`/`EncodeValueRef`; remove `OptionalRef`

der/src/asn1/any.rs, der/src/asn1/bit_string.rs, der/src/asn1/boolean.rs, der/src/asn1/generalized_time.rs, der/src/asn1/integer/bigint.rs, der/src/asn1/integer/int.rs, der/src/asn1/integer/uint.rs, der/src/asn1/oid.rs, der/src/asn1/real.rs, der/src/asn1/utc_time.rs, der/src/byte_slice.rs, der/src/datetime.rs, der/src/document.rs, der/src/encoder.rs, der/src/length.rs, der/src/lib.rs, der/src/str_slice.rs, der/src/tag.rs, der/src/writer.rs
Begins moving core encoding functionality into a `Writer` trait.
The longer-term goal is to make the `Encode` trait accept a generic type as a backend, which can enable things like 1-pass PEM encoding or computing key fingerprints by impl'ing `Writer` for a hash function.
=> der: initial `Writer` trait

der/derive/src/choice.rs, der/src/asn1/bit_string.rs, der/src/asn1/boolean.rs, der/src/asn1/context_specific.rs, der/src/asn1/optional.rs, der/src/asn1/sequence.rs, der/src/asn1/sequence_of.rs, der/src/asn1/set_of.rs, der/src/byte_slice.rs, der/src/decoder.rs, der/src/document.rs, der/src/error.rs, der/src/length.rs, der/src/lib.rs, der/src/reader.rs, der/src/tag.rs, pkcs8/src/private_key_info.rs
Begins moving core decoding functionality into a `Reader` trait.
The longer-term goal is to move enough functionality to the trait to support things like one-pass decoding directly from PEM for `DecodeOwned` types.
=> der: initial `Reader` trait

der/src/decoder.rs, der/src/error.rs, der/src/reader.rs, x509/tests/pkix_extensions.rs
It was previously fallible to support runtime calculations, but with a bit of refactoring and simplification it's possible to query this for the current `Decoder` type using `ByteSlice::len`.
Other readers may need to compute it, but this can be performed as an eager calculation of a fallible constructor (similar to how `ByteSlice` does it). Since it's a static, non-changing value for the lifecycle of any given reader it makes sense to make it infallible.
This decision may need to be revisited if we ever want to support "streaming" readers which don't know the total size of the input data ahead of time.
=> der: make `Reader::input_len` infallible

der/src/decoder.rs, der/src/length.rs, der/src/reader.rs
Like #607, this makes a length calculation infallible, and also adds a default implementation.
It uses saturating arithmetic to avoid panics, with `debug_assert!` to make sure the operands of the calculation make sense.
That said, if there is a bug where a reader's cursor/position exceeds the `input_len()`, it will still calculate a value that makes sense for `remaining_len()` when using saturating arithmetic: 0.
=> der: make `Reader::remaining_len` infallible

ssh-key/src/certificate/builder.rs, ssh-key/src/certificate/field.rs
Adds a `std` feature-gated constructor method for `certificate::Builder` which allows specifying the validity window in terms of `SystemTime`.
This is helpful when computing the validity window relative to the system clock as queried with `SystemTime::now()`.
=> ssh-key: add `certificate::Builder::new_with_validity_times`

ssh-key/src/certificate.rs, ssh-key/src/certificate/builder.rs, ssh-key/src/certificate/unix_time.rs, ssh-key/src/error.rs
Adds a type for modeling Unix timestamps for use in OpenSSH certificate validity windows.
This puts all time-related code in a single place.
=> ssh-key: add internal `UnixTime` helper type

spki/src/fingerprint.rs, spki/src/lib.rs, spki/src/spki.rs, spki/tests/spki.rs
Uses the `Writer` trait to compute SPKI fingerprints by hashing output DER on-the-fly as opposed to encoding it first to an intermediate buffer then computing the SHA-256 digest.
Besides simply being more efficient, the buffered method had a hardcoded limit of 4096-bytes. The new implementation has no such limit because it hashes data as soon as it's encoded.
This additionally renames `SubjectPublicKeyInfo::fingerprint` to `::fingerprint_bytes`. "True" SPKI fingerprints are Base64-encoded, and this commit also promotes `fingerprint_base64` to being earlier in the impl block so it's the first fingerprinting method people see.
=> spki: streaming fingerprint builder

.github/workflows/ssh-key.yml, ssh-key/src/private.rs
Whoops, it seems #614 contained a parse error and CI didn't actually do a proper run. This fixes the configuration.
=> ssh-key: fix CI

der/src/encode.rs, der/src/error.rs, der/src/lib.rs, der/src/writer.rs
Adds a `PemWriter` type which impls the `Writer` trait and can perform on-the-fly PEM encoding.
=> der: add `PemWriter` and 1-pass `EncodePem`

Cargo.lock, der/Cargo.toml, der/src/encode.rs, pem-rfc7468/Cargo.toml, pem-rfc7468/src/encoder.rs, pem-rfc7468/src/lib.rs, ssh-key/Cargo.toml, ssh-key/src/private.rs
Estimates upper bound of the length of encoded line-wrapped Base64 with a specified customizable line width and line ending.
Also changes the input parameters of `encapsulated_len`, which now accepts the length of the raw input data prior to Base64 encoding, making it significantly less error prone.
Together these functions are used to DRY out similar calculations presently occurring in the `der` and `ssh-key` crates.
This is a breaking change, so it also bumps the version to v0.6.0-pre.
=> pem-rfc7468: revamp encapsulated length calculation functions

Cargo.lock, der/Cargo.toml, pem-rfc7468/CHANGELOG.md, pem-rfc7468/Cargo.toml, ssh-key/Cargo.toml
- `encapsulated_len_wrapped` ([#619])
- `encapsulated_len` now accepts the length of the raw input bytes prior to Base64 encoding, and computes the length of the full PEM encoded document including newlines when the resulting Base64 is linewrapped ([#619])
[#619]: https://github.com/RustCrypto/formats/pull/619
=> pem-rfc7468 v0.6.0

ssh-key/src/certificate/unix_time.rs
Caps maximum allowed Unix timestamps to:
9999-12-31 23:59:59 UTC
This is a sanity limit intended to catch nonsense values which are excessively distant in the future.
=> ssh-key: further restrict maximum allowed timestamps

Cargo.lock, ssh-key/CHANGELOG.md, ssh-key/Cargo.toml
- Internal `UnixTime` helper type ([#613])
- Bump `pem-rfc7468` dependency to v0.6.0 ([#620])
- Further restrict maximum allowed timestamps ([#621])
[#613]: https://github.com/RustCrypto/formats/pull/613
[#620]: https://github.com/RustCrypto/formats/pull/620
[#621]: https://github.com/RustCrypto/formats/pull/621
=> ssh-key v0.4.1

der/Cargo.toml, der/src/asn1.rs, der/src/asn1/real.rs, der/src/lib.rs
Most users of this crate do not need `real`, however its implementation may be problematic in environments that don't have access to floating point, e.g. UEFI or uCs with no FPU.
Feature gating it ensures there will be no complications building in these environments.
=> der: feature-gate `real` implementation

der/src/arrayvec.rs, der/src/asn1/set_of.rs, der/tests/set_of.rs, x509/tests/name.rs
Some DER serializer implementations fail to properly sort elements of a `SET OF`. This is technically non-canonical, but occurs frequently enough that most DER decoders tolerate it. Unfortunately because of that, we must also follow suit.
This commit builds an `ArrayVec` or `Vec` of the incoming decoded set elements, and then unconditionally sorts it retroactively, ensuring all `SET OF` types internally reflect the proper order, but out-of-order `SET OF` messages are tolerated when coming off-the-wire.
The sort implementation is merge sort, which should be efficient for already-in-order or mostly-in-order sets.
=> der: remove decode-time SET OF ordering checks

ssh-key/Cargo.toml, ssh-key/README.md, ssh-key/src/known_hosts.rs, ssh-key/src/lib.rs, ssh-key/src/public/openssh.rs, ssh-key/tests/authorized_keys.rs, ssh-key/tests/examples/authorized_keys, ssh-key/tests/examples/known_hosts, ssh-key/tests/known_hosts.rs
This is largely based on the authorized_keys parse functionality already present, and there are probably some opportunities to remove redundancy between them, but this is a functional start.
Note that also in this PR is making it so that it treats the comments field of an ssh key as optional. This is correct both according to the ssh(8) man page and the comments all over the codebase here, but it was using a lack of comment as an indication that the key was truncated. This does mean that a validity check has been removed, but this was probably always the wrong place to do it (the key parser itself should know the expected length of the key).
=> Add support for parsing keys out of the ssh known_hosts file format

ssh-key/src/private.rs, ssh-key/src/private/keypair.rs, ssh-key/src/public.rs, ssh-key/src/public/key_data.rs
Adds support for converting the various algorithm-specific key types (e.g. `RsaPublicKey`, `RsaPrivateKey`) directly into `PublicKey` and `PrivateKey` using the `From` trait.
Unlike `private::KeypairData`, these conversions can be infallible.
=> ssh-key: add more key conversions

Cargo.lock, ssh-key/CHANGELOG.md, ssh-key/Cargo.toml
- Support for parsing keys out of the ssh known_hosts file format ([#624])
- Export `RsaPrivateKey` ([#629])
- `From` conversions between algorithmic-specific key types and `PublicKey`/`PrivateKey` ([#629])
[#624]: https://github.com/RustCrypto/formats/pull/624
[#629]: https://github.com/RustCrypto/formats/pull/629
=> ssh-key v0.4.2

base16ct/README.md, base64ct/README.md, const-oid/README.md, der/README.md, pem-rfc7468/README.md, pkcs1/README.md, pkcs5/README.md, pkcs7/README.md, pkcs8/README.md, sec1/README.md, serdect/README.md, spki/README.md, ssh-key/README.md, tai64/README.md, x509/README.md
These badges include download figures, which eliminates the need to have a separate badge that measures downloads.
=> Use crates.io info badges from buildstats.info in README.mds

der/src/lib.rs, der/src/writer.rs, der/src/writer/pem.rs
Internal refactor in preparation for adding `PemReader`.
=> der: move `PemWriter` to its own module

der/src/asn1.rs, der/src/asn1/any.rs, der/src/asn1/bit_string.rs, der/src/asn1/octet_string.rs, der/src/asn1/utf8_string.rs, der/src/lib.rs, der/src/reader.rs
Adds owned forms of these two ASN.1 types, now that the borrowed forms have been renamed to `AnyRef` and `OctetStringRef`.
Includes some refactoring of the owned `BitString` type.
Also adds a `Reader::read_vec` method for reading a byte vector from a reader, and uses it to impl `DecodeValue` for `String`.
=> der: add owned `Any` and `OctetString` types

Cargo.lock, der/Cargo.toml, der/derive/Cargo.toml, pkcs1/Cargo.toml, pkcs5/Cargo.toml, pkcs7/Cargo.toml, pkcs8/Cargo.toml, sec1/Cargo.toml, spki/Cargo.toml, x509/Cargo.toml
Also includes a release bump for `der_derive` v0.6.0-pre.4
=> der v0.6.0-pre.4

Cargo.lock, pkcs1/Cargo.toml, pkcs5/Cargo.toml, pkcs8/Cargo.toml, sec1/Cargo.toml
Releases the following pre.2 versions:
- `pkcs1` v0.4.0-pre.2
- `pkcs5` v0.5.0-pre.2
- `pkcs8` v0.9.0-pre.2
- `sec1` v0.3.0-pre.2
=> pkcs1/5/8 and sec1 pre.2 releases

pkcs8/src/lib.rs
This trait can be used to associate an OID with a particular type
=> pkcs8: re-export `AssociatedOid`

Cargo.lock, sec1/Cargo.toml, sec1/src/lib.rs, sec1/src/point.rs, serdect/Cargo.toml
Uses these crates to impl hex encoding/decoding and serde support
=> sec1: use `base16ct` and `serdect` crates

der/src/asn1/any.rs, der/src/asn1/context_specific.rs, der/src/asn1/generalized_time.rs, der/src/asn1/integer.rs, der/src/asn1/integer/bigint.rs, der/src/asn1/utc_time.rs, der/src/decode.rs, der/src/document.rs, der/src/encode.rs, der/src/length.rs, der/src/lib.rs, der/src/reader.rs, der/src/reader/slice.rs, der/src/writer.rs, der/src/writer/slice.rs, der/tests/datetime.rs, der/tests/derive.rs, pkcs5/tests/pbes2.rs, pkcs7/src/content_info.rs, pkcs7/tests/content_tests.rs, x509-cert/tests/trust_anchor_format.rs
Renames the following types:
- `Decoder` => `SliceReader`
- `Encoder` => `SliceWriter`
=> der: rename `SliceReader`/`SliceWriter`

Cargo.lock, der/Cargo.toml, der/derive/CHANGELOG.md, der/derive/Cargo.toml, der/derive/src/lib.rs
- Support for Context-Specific fields with default values ([#246])
- Context-Specific tags on `#[derive(Sequence)]` ([#349])
- `#[asn1(constructed = "true")]` ([#398])
- Have `Sequence` macro derive `DecodeValue` ([#375])
- Pass `Header` to `DecodeValue` ([#392])
- Have `Choice` macro derive `EncodeValue` ([#395])
- Only emit `.try_into()?` when a type is specified ([#397])
- Use type's tag by default on `derive(Choice)` ([#416])
- Length calculation for explicit tags ([#400])
- Static lifetime from ENUMERATED's derived `DecodeValue` ([#367])
[#246]: https://github.com/RustCrypto/formats/pull/246
[#349]: https://github.com/RustCrypto/formats/pull/349
[#367]: https://github.com/RustCrypto/formats/pull/367
[#375]: https://github.com/RustCrypto/formats/pull/375
[#392]: …
=> der_derive v0.6.0

Cargo.lock, der/CHANGELOG.md, der/Cargo.toml, der/LICENSE-MIT, der/derive/LICENSE-MIT, der/src/lib.rs, pkcs1/Cargo.toml, pkcs5/Cargo.toml, pkcs7/Cargo.toml, pkcs8/Cargo.toml, sec1/Cargo.toml, spki/Cargo.toml, x509-cert/Cargo.toml, x509-ocsp/Cargo.toml
- Impl `ValueOrd` for `SetOf` and `SetOfVec` ([#362])
- `SequenceRef` type ([#374])
- Support for `SetOf` sorting on heapless `no_std` targets ([#401])
- Support for mapping `BitString` to/from a `FlagSet` ([#412])
- `DecodeOwned` marker trait ([#529])
- Support for the ASN.1 `REAL` type ([#346])
- `DecodePem` and `EncodePem` traits ([#571])
- `Document` and `SecretDocument` types ([#571])
- `EncodeRef`/`EncodeValueRef` wrapper types ([#604])
- `Writer` trait ([#605])
- `Reader` trait ([#606])
- Streaming on-the-fly `PemReader` and `PemWriter` ([#618], [#636])
- Owned `BitString` ([#636])
- Owned `Any` and `OctetString` types ([#640])
- Pass `Header` to `DecodeValue` ([#392])
- Bump `const-oid` dependency to v0.9 ([#507])
- Renamed `Decodable`/`Encodable` => `Decode`/`Encode` ([#523])
- …
=> der v0.6.0

Cargo.lock, pkcs5/Cargo.toml, pkcs7/Cargo.toml, pkcs8/Cargo.toml, spki/CHANGELOG.md, spki/Cargo.toml, spki/src/lib.rs, x509-cert/Cargo.toml, x509-ocsp/Cargo.toml
- `AlgorithmIdentifier::oids()` helper function ([#443])
- Impl `PartialOrd` for `AlgorithmIdentifier` ([#476])
- Impl `DecodeValue` for `AlgorithmIdentifier` ([#449])
- Impl `ValueOrd` for `SubjectPublicKeyInfo` ([#522])
- Replace `PublicKeyDocument` with `der` crate's `Document` type ([#571])
- Streaming fingerprint builder ([#616])
- Bump `der` crate dependency to v0.6 ([#653])
- `PublicKeyDocument` ([#571])
[#443]: https://github.com/RustCrypto/formats/pull/443
[#449]: https://github.com/RustCrypto/formats/pull/449
[#476]: https://github.com/RustCrypto/formats/pull/476
[#522]: https://github.com/RustCrypto/formats/pull/522
[#571]: https://github.com/RustCrypto/formats/pull/571
[#616]: https://github.com/RustCrypto/formats/pull/616
=> spki v0.6.0

Cargo.lock, pkcs5/CHANGELOG.md, pkcs5/Cargo.toml, pkcs8/Cargo.toml
- Update `hmac`, `pbkdf2`, and `sha2`
- Update cipher v0.4 crates ([#411])
- Switch from `sha-1` to `sha1`; `sha1` feature is renamed to `sha1-insecure` ([#426])
- Bump `scrypt` dependency to v0.9 ([#441])
- Bump `der` to v0.6 ([#653])
- Bump `spki` to v0.6 ([#654])
[#411]: https://github.com/RustCrypto/formats/pull/411
[#426]: https://github.com/RustCrypto/formats/pull/426
[#441]: https://github.com/RustCrypto/formats/pull/441
[#654]: https://github.com/RustCrypto/formats/pull/654
=> pkcs5 v0.5.0

Cargo.lock, pkcs1/Cargo.toml, pkcs8/CHANGELOG.md, pkcs8/Cargo.toml, sec1/Cargo.toml
- Error conversion support to `pkcs8::spki::Error` ([#335])
- Re-export `AssociatedOid` ([#645])
- Use `finish_non_exhaustive` in `Debug` impls ([#245])
- Replace `PrivateKeyDocument` with `der::SecretDocument` ([#571])
- Bump `der` to v0.6 ([#653])
- Bump `spki` to v0.6 ([#654])
- Bump `pkcs5` to v0.5 ([#655])
- `PrivateKeyDocument` ([#571])
[#245]: https://github.com/RustCrypto/formats/pull/245
[#335]: https://github.com/RustCrypto/formats/pull/335
[#571]: https://github.com/RustCrypto/formats/pull/571
[#645]: https://github.com/RustCrypto/formats/pull/645
[#654]: https://github.com/RustCrypto/formats/pull/654
[#655]: https://github.com/RustCrypto/formats/pull/655
=> pkcs8 v0.9.0

Cargo.lock, pkcs1/CHANGELOG.md, pkcs1/Cargo.toml
- Replace document types with `doc::{Document, SecretDocument}` types ([#571])
- Bump `der` to v0.6 ([#653])
- Bump `pkcs8` to v0.9 ([#656])
[#571]: https://github.com/RustCrypto/formats/pull/571
[#656]: https://github.com/RustCrypto/formats/pull/656
=> pkcs1 v0.4.0

Cargo.lock, pkcs1/Cargo.toml, pkcs1/LICENSE-MIT, pkcs1/src/lib.rs, sec1/CHANGELOG.md, sec1/Cargo.toml, sec1/LICENSE-MIT, sec1/src/lib.rs
- Make `der` feature optional but on-by-default ([#497])
- Make `point` feature optional but on-by-default ([#516])
- Use `base16ct` and `serdect` crates ([#648])
- Bump `der` to v0.6 ([#653])
- Bump `pkcs8` to v0.9 ([#656])
[#497]: https://github.com/RustCrypto/formats/pull/497
[#516]: https://github.com/RustCrypto/formats/pull/516
[#648]: https://github.com/RustCrypto/formats/pull/648
[#656]: https://github.com/RustCrypto/formats/pull/656
=> sec1 v0.3.0

Cargo.lock, pkcs7/Cargo.toml, x509-cert/Cargo.toml, x509-ocsp/Cargo.toml
The following are the remaining crates which haven't yet received a final release with `der` v0.6, with this commit cutting the following prereleases:
- `pkcs7` v0.4.0-pre.0
- `x509-cert` v0.1.0-pre.0
- `x509-ocsp` v0.1.0-pre.0
The idea is to give one last opportunity to make breaking changes before cutting final releases.
cc @bstrie @carl-wallace @npmccallum
=> Cut prereleases with `der` v0.6 dependency

pkcs8/src/lib.rs
Adds `doc_cfg` for the features needed for the re-exports to be available
=> pkcs8: document `alloc` and `pkcs5` features for re-exports

base32ct/src/lib.rs
Support for decoding/encoding upper case Base32.
=> base32ct: add `Base32Upper`

base64ct/README.md, base64ct/src/alphabet.rs, base64ct/src/alphabet/bcrypt.rs, base64ct/src/alphabet/crypt.rs, base64ct/src/alphabet/standard.rs, base64ct/src/alphabet/url.rs, base64ct/src/decoder.rs, base64ct/src/encoder.rs, base64ct/src/encoding.rs, base64ct/src/lib.rs
Matches the name used in #668.
The trait is sealed, so renaming it is not a breaking change.
=> base64ct: rename `Variant` trait to `Alphabet`

base64ct/src/encoding.rs, base64ct/tests/standard.rs
Generalizes the internal `validate_padding` function into a `validate_last_block` function which can work on unpadded variants as well.
The function performs round-trip re-encoding the decoded last block, ensuring that it matches the provided input, or otherwise returns an `InvalidEncodingError`.
Closes #679
=> base64ct: fix last block validation

Cargo.lock, base64ct/CHANGELOG.md, base64ct/Cargo.toml
- Last block validation ([#680])
[#680]: https://github.com/RustCrypto/formats/pull/680
=> base64ct v1.5.1

x509-cert/src/attr.rs, x509-cert/src/ext/pkix/name/dirstr.rs
Enable using TeletexString in several places where it should be enabled.
=> x509-cert: support `TeletexString`

der/src/asn1/ia5_string.rs, der/src/asn1/printable_string.rs, der/src/asn1/teletex_string.rs, der/src/asn1/utf8_string.rs, der/src/asn1/videotex_string.rs, der/src/str_slice.rs
Use Deref<StrSlice> to limit amount of boilerplace code in the
*StringRef implementations.
Signed-off-by: Dmitry Baryshkov <dmitry.baryshkov@linaro.org>
=> der/asn1: remove bolerplate code by using Deref (#693)

Cargo.lock, base64ct/CHANGELOG.md, base64ct/Cargo.toml, base64ct/src/decoder.rs, base64ct/src/lib.rs
Users of the trait expect that implementations should return `Ok(0)` to signal end of stream.
The issue was raised in the [Zulip chat](https://rustcrypto.zulipchat.com/#narrow/stream/300570-formats/topic/base64ct.20decoder).
=> base64ct: fix io::Read impl

x509-cert/src/lib.rs
SubjectPublicKeyInfo is required in order to create a CertReqInfo and was not currently exported
=> x509-cert: re-export spki

Cargo.lock, pkcs1/Cargo.toml, pkcs1/src/lib.rs, pkcs1/src/params.rs, pkcs1/tests/params.rs
Add support for parsing and generatign RSA PSS params.
Signed-off-by: Dmitry Baryshkov <dmitry.baryshkov@linaro.org>
=> pkcs1: implement support for PSS Params structure

pkcs1/Cargo.toml, pkcs1/src/lib.rs, pkcs1/src/params.rs, pkcs1/tests/params.rs
Followup to #698.
- Renames `RsaPSSParameters` => `RsaPssParams`
- Removes use of the `der` crate's `derive` feature
The `rsa` crate currently doesn't need any custom derive, and adding it here would make it a hard requirement.
We can consider switching to custom derive in `pkcs1`, but if we do it then it should be wholesale for all types in the crate, not using custom derive for some types and handwritten impls for others.
=> pkcs1: cleanups to `params` module

base32ct/src/alphabet.rs, base32ct/src/alphabet/rfc4648.rs, base64ct/src/alphabet.rs, base64ct/src/alphabet/bcrypt.rs, base64ct/src/alphabet/crypt.rs, base64ct/src/alphabet/standard.rs, base64ct/src/alphabet/url.rs
This is semantically more correct and avoids triggering the `almost_complete_letter_range` clippy lint.
Note that there was no bug here as the same range is still used behind the scenes.
=> base32ct+base64ct: use `RangeInclusive` for `DecodeStep`

x509-cert/Cargo.toml
- `rstest` v0.13 requires MSRV 1.59 for `async-global-executor`
- `rstest` v0.14 and above use namespaced cargo features which require MSRV 1.60. On earlier versions of rustc (for crates anywhere in the same workspace) this causes a confusing failure mode:
https://github.com/RustCrypto/formats/runs/8059634879
=> x509-cert: note why `rstest` can't easily be upgraded

pkcs1/src/lib.rs, pkcs1/src/params.rs, pkcs1/tests/params.rs
Add support for parsing and generatign RSA OAEP params.
Note: I was not sure regarding the `pSpecifiedEmpty.parameters`, but RFC3560 clearly defines it as `OCTET STRING (SIZE(0))`.
=> pkcs1: implement support for OAEP Params structure

.github/workflows/workspace.yml, pkcs1/src/traits.rs
The `doc` attribute was missing `cfg`.
=> pkcs1: fix rustdoc warnings

Cargo.lock, pkcs1/CHANGELOG.md, pkcs1/Cargo.toml
- `RsaPssParams` support ([#698])
- `RsaOaepParams` support ([#733])
[#698]: https://github.com/RustCrypto/formats/pull/698
[#733]: https://github.com/RustCrypto/formats/pull/733
=> pkcs1 v0.4.1

tls_codec/src/quic_vec.rs
- optionally impl serde (de)serialization for VLBytes (serde_serialize feature)
- implement AsRef, Hash, From<Vec<u8>>, From<&[u8]> for VLBytes
cc @raphaelrobert, @kkohbrok
=> tls_codec: Implement more traits for VLBytes

tls_codec/src/quic_vec.rs
I am working on switching hash references in OpenMLS to [variable length vectors](https://github.com/openmls/openmls/issues/928#event-7556019970). The references will be stored as `VLBytes`. OpenMLS contains tree operations that depend on an `Ord` implementation for hash references.
=> tls_codec: Implement `Ord/PartialOrd` for VLBytes

tls_codec/src/lib.rs, tls_codec/src/quic_vec.rs, tls_codec/tests/decode.rs
When fuzzing we don't want to assert all the things.
=> tls_codec: remove debug asserts from quic vec when fuzzing

Cargo.lock, base64ct/CHANGELOG.md, base64ct/Cargo.toml
- `Base64ShaCrypt` alphabet ([#742])
- Use `RangeInclusive` for `DecodeStep` ([#713])
[#713]: https://github.com/RustCrypto/formats/pull/713
[#742]: https://github.com/RustCrypto/formats/pull/742
=> base64ct v1.5.3

ssh-key/README.md
The new repo has existed for approximately 1 month.
This commit removes the placeholder directory with information about the repo's new location.
=> ssh-key: remove old directory

tls_codec/src/quic_vec.rs
Some more utility for VLBytes
* `push` and `pop`
* `Into<Vec<u8>>`
cc @raphaelrobert @kkohbrok
=> tls_codec: Add push/pop functions and Into<Vec<u8>> to VLBytes

const-oid/src/lib.rs
Adds an object safe value-dependent trait which returns an `ObjectIdentifier` dynamically, with a blanket impl for types which impl `AssociatedOid`.
=> const-oid: add `DynAssociatedOid` trait

Cargo.lock, const-oid/CHANGELOG.md, const-oid/Cargo.toml
- clippy lints for checked arithmetic and panics ([#561])
- `DynAssociatedOid` trait ([#758])
[#561]: https://github.com/RustCrypto/formats/pull/561
[#758]: https://github.com/RustCrypto/formats/pull/758
=> const-oid v0.9.1

x509-cert/src/attr.rs, x509-cert/tests/name.rs
I was doing some testing and came across the fact that creating a CSR / Certificate with countryName set in the DN leads to a different output. I narrowed it down to formats producing UTF8String for countryName and OpenSSL 3.0 producing PrintableString. 
I also came across this stack overflow post on the subject. The countryName field is required to be PrintableString according to X.502. https://stackoverflow.com/questions/17215598/country-name-field-in-ca-generated-by-openssl-is-encoded-as-printablestring-whil
If this isn't the right place to put this logic please let me know, thanks!
=> x509: `countryName` should always be `PrintableString`

der/derive/src/value_ord.rs, der/src/asn1/bit_string.rs, der/src/asn1/integer/bigint.rs, x509-cert/src/certificate.rs, x509-cert/src/crl.rs, x509-cert/src/ext.rs, x509-cert/src/ext/pkix/access.rs, x509-cert/src/ext/pkix/certpolicy.rs, x509-cert/src/ext/pkix/crl/dp.rs, x509-cert/src/ext/pkix/name/dirstr.rs, x509-cert/src/ext/pkix/name/dp.rs, x509-cert/src/ext/pkix/name/ediparty.rs, x509-cert/src/ext/pkix/name/general.rs, x509-cert/src/ext/pkix/name/other.rs, x509-cert/src/ext/pkix/policymap.rs, x509-cert/src/macros.rs, x509-cert/src/time.rs
I'm currently working on implementing [Authenticode](https://www.symbolcrash.com/wp-content/uploads/2019/02/Authenticode_PE-1.pdf) (microsoft's codesigning system). As part of this, I've had to implement a lot more of PKCS#7, and a problem I've been hitting fairly consistently is how few types implement ValueOrd.
This MR does three things:
1. It adds manual ValueOrd implementations for der's FlagSet, UIntRef, and x509-cert's Version.
2. It allows deriving ValueOrd for Choice enums (note - I'm not 100% sure the implementation is correct, more on this below).
3. It derives ValueOrd on a lot of different types.
---
The biggest improvement here is implementing ValueOrd for Choice enums. It works by generating an implementation that looks roughly like this:
```rust
match (self, other) { …
```
=> Implement ValueOrd in more places

der/src/asn1/octet_string.rs
The `ValueOrd` is implemented for the zero copy but it was missing for the owned version
=> der: missing ValueOrd for `OctetString`

Cargo.lock, der/derive/CHANGELOG.md, der/derive/Cargo.toml
- Support for deriving `ValueOrd` on `Choice` enums ([#723])
[#723]: https://github.com/RustCrypto/formats/pull/723
=> der_derive v0.6.1

Cargo.lock, der/CHANGELOG.md, der/Cargo.toml
- Rudimentary implementation of `TeletexString` and `VideotexString` ([#691])
- Impl `ValueOrd` for `FlagSet<T>` and `UIntRef` ([#723])
- Eliminate some boilerplate code by using `Deref` ([#697])
[#691]: https://github.com/RustCrypto/formats/pull/691
[#697]: https://github.com/RustCrypto/formats/pull/697
[#723]: https://github.com/RustCrypto/formats/pull/723
=> der v0.6.1

Cargo.lock, x509-cert/CHANGELOG.md, x509-cert/Cargo.toml
- Support `TeletexString` in `DirectoryString` ([#692])
- Re-export `spki` ([#701])
- `PemLabel` impl for `Certificate` ([#763])
- `ValueOrd` impl for `Version` and other derived types ([#723])
-  `countryName` should always be `PrintableString` ([#760])
[#692]: https://github.com/RustCrypto/formats/pull/692
[#701]: https://github.com/RustCrypto/formats/pull/701
[#723]: https://github.com/RustCrypto/formats/pull/723
[#760]: https://github.com/RustCrypto/formats/pull/760
[#763]: https://github.com/RustCrypto/formats/pull/763
=> x509-cert v0.1.1

Cargo.lock, const-oid/Cargo.toml, der/Cargo.toml, der/derive/Cargo.toml, pkcs1/Cargo.toml, pkcs5/Cargo.toml, pkcs7/Cargo.toml, pkcs8/Cargo.toml, sec1/Cargo.toml, spki/Cargo.toml, x509-cert/Cargo.toml, x509-ocsp/Cargo.toml
Begins the next cycle of breaking changes for all `const-oid`/`der`-dependent crates in this repository:
- `const-oid` v0.10.0-pre
- `der`/`der_derive` v0.7.0-pre
- `pkcs1` v0.5.0-pre
- `pkcs5` v0.6.0-pre
- `pkcs8` v0.10.0-pre
- `sec1` v0.4.0-pre
- `spki` v0.7.0-pre
- `x509-cert` v0.2.0-pre
=> Bump versions to prereleases

const-oid/src/arcs.rs, const-oid/src/buffer.rs, const-oid/src/db.rs, const-oid/src/encoder.rs, const-oid/src/lib.rs
The current buffering approach, with a fixed-sized `ArrayVec`-like backing buffer, is helpful for being able to use `const fn` to be able to parse OID strings at compile time and re-encode them in BER form. This functionality is preserved as a new `Buffer` type, which still supports all current `const fn` functionality.
`ObjectIdentifier` has been changed to be generic around `B: AsRef<[u8]>` which allows a `const fn` constructor that accepts a BER-encoded slice.
This is useful for when there are large numbers of OID constants, as in the `const_oid::db` module. However, while this module has been updated so the code compiles, it has not yet been changed to take advantage of this new approach.
=> const-oid: generic backing buffer

pkcs1/src/traits.rs, pkcs8/src/traits.rs, pkcs8/tests/traits.rs, sec1/src/traits.rs, spki/src/traits.rs, spki/tests/traits.rs
Previously these traits had `TryFrom` bounds for e.g. `PrivateKeyInfo`, which limits the applicability of these traits.
This commit changes to using blanket impls for `TryFrom`, which allows types to handle parsing raw DER on their own, as in the `ring-compat` crate.
=> pkcs8+spki: use blanket impls for `Decode*` traits

der/src/asn1.rs, der/src/asn1/integer/bigint.rs, der/src/lib.rs, pkcs1/src/lib.rs, pkcs1/src/private_key.rs, pkcs1/src/private_key/other_prime_info.rs, pkcs1/src/public_key.rs, x509-cert/src/certificate.rs, x509-cert/src/crl.rs, x509-cert/src/ext/pkix/authkeyid.rs, x509-cert/src/ext/pkix/certpolicy.rs, x509-cert/src/ext/pkix/crl.rs, x509-cert/tests/certificate.rs, x509-cert/tests/pkix_extensions.rs, x509-ocsp/src/lib.rs
From https://rust-lang.github.io/api-guidelines/naming.html
> In UpperCamelCase, acronyms and contractions of compound words count
> as one word: use Uuid rather than UUID, Usize rather than USize or
> Stdin rather than StdIn.
Based on the `Usize` example, it's pretty clear we should be using `Uint` rather than `UInt`.
This is also consistent with `num-bigint` and `crypto-bigint` as of RustCrypto/crypto-bigint#143
=> der: rename `UIntRef` => `UintRef`

pkcs1/src/lib.rs, pkcs1/src/params.rs, pkcs5/src/lib.rs, pkcs5/src/pbes1.rs, pkcs5/src/pbes2.rs, pkcs5/src/pbes2/kdf.rs, pkcs7/src/enveloped_data_content.rs, pkcs7/tests/content_tests.rs, pkcs8/src/error.rs, pkcs8/src/lib.rs, pkcs8/src/private_key_info.rs, sec1/src/traits.rs, spki/src/algorithm.rs, spki/src/lib.rs, spki/src/spki.rs, x509-cert/src/certificate.rs, x509-cert/src/crl.rs, x509-cert/src/request.rs, x509-cert/tests/certificate.rs, x509-ocsp/src/lib.rs
NOTE: breaking change.
Previously `AlgorithmIdentifier::parameters` were always `AnyRef`. This commit changes them to a generic parameter `Params`.
An alias `AlgorithmIdentifierRef` provides a type identical to the original with `AnyRef` as its `parameters`, which is used in all of the other crates in this repo.
cc @baloo @lumag
=> spki: make `AlgorithmIdentifier` generic around `Params`

Cargo.lock, x509-cert/Cargo.toml
Now that we're on MSRV 1.60 it's compatible
=> x509-cert: bump `rstest` to v0.16

tls_codec/src/quic_vec.rs, tls_codec/src/tls_vec.rs
Followup to #791 to actually use the feature
=> tls_codec: use serde feature instead of serde_serialize

der/src/asn1/any.rs, der/src/asn1/ia5_string.rs, der/src/asn1/printable_string.rs, der/src/asn1/teletex_string.rs, der/src/asn1/utf8_string.rs, der/src/asn1/videotex_string.rs, der/src/byte_slice.rs, der/src/byte_vec.rs, der/src/bytes.rs, der/src/lib.rs, x509-cert/src/anchor.rs, x509-cert/src/attr.rs, x509-cert/src/certificate.rs, x509-cert/src/crl.rs, x509-cert/src/ext/pkix.rs, x509-cert/src/ext/pkix/name/dp.rs, x509-cert/src/ext/pkix/name/general.rs, x509-cert/src/ext/pkix/name/other.rs, x509-cert/src/name.rs, x509-cert/src/request.rs, x509-cert/tests/certificate.rs, x509-cert/tests/certreq.rs, x509-cert/tests/name.rs, x509-cert/tests/pkix_extensions.rs, x509-cert/tests/trust_anchor_format.rs, x509-ocsp/src/lib.rs
NOTE: breaking change.
This changes x509 from a zero copy type to an owned type.
This brings along a rewrite of `der::Any` and a new `der::ByteVec` to come closer to `der::ByteSlice` backing `der::AnyRef`
=> x509-cert: make name an owned type

der/src/asn1/boolean.rs, der/src/byte_slice.rs, der/src/bytes.rs
This is a vestige from when more decoding/encoding was handled by way of `AnyRef` instead of generics/traits.
=> der: remove unused impls

.github/workflows/tls_codec.yml
It's been renamed to `serde`.
It's causing these build failures on `master`:
https://github.com/RustCrypto/formats/actions/runs/3721094404/jobs/6311010746
=> tls_codec: fix `serde_serialize` reference in CI

const-oid/Cargo.toml, const-oid/README.md, der/Cargo.toml, der/README.md, der/derive/Cargo.toml, der/derive/README.md, pkcs1/Cargo.toml, pkcs1/README.md, pkcs12/Cargo.toml, pkcs12/README.md, pkcs5/Cargo.toml, pkcs5/README.md, pkcs7/Cargo.toml, pkcs7/README.md, pkcs8/Cargo.toml, pkcs8/README.md, sec1/Cargo.toml, sec1/README.md, spki/Cargo.toml, spki/README.md, x509-cert/Cargo.toml, x509-cert/README.md, x509-ocsp/Cargo.toml, x509-ocsp/README.md
All `der`-dependent crates are now MSRV 1.65
Closes #804
=> Update `rust-version` and documented MSRV in README.md(s)

x509-cert/src/serial_number.rs
This adds a `Display` implementation for `SerialNumber`.
I went with a MAC-style format because that's the format OpenSSL uses.
=> x509-cert: add `Display` impl for `SerialNumber`

.github/workflows/workspace.yml, .github/workflows/x509-cert.yml, Cargo.lock, base16ct/src/lib.rs, base32ct/src/alphabet.rs, base32ct/src/lib.rs, base64ct/src/lib.rs, const-oid/src/lib.rs, der/src/datetime.rs, der/src/lib.rs, pem-rfc7468/src/lib.rs, pkcs1/src/lib.rs, pkcs12/src/lib.rs, pkcs5/src/lib.rs, pkcs5/src/pbes2/encryption.rs, pkcs7/src/lib.rs, pkcs8/src/lib.rs, sec1/src/lib.rs, sec1/src/point.rs, serdect/src/lib.rs, spki/src/lib.rs, tai64/src/lib.rs, tls_codec/benches/quic_vec.rs, tls_codec/src/lib.rs, tls_codec/src/quic_vec.rs, tls_codec/src/tls_vec.rs, tls_codec/tests/decode.rs, tls_codec/tests/encode.rs, x509-cert/src/lib.rs, x509-ocsp/src/lib.rs
Adopts the following lints as a baseline (with a few exceptions):
#![warn(
clippy::mod_module_files,
clippy::unwrap_used,
missing_docs,
rust_2018_idioms,
unused_lifetimes,
unused_qualifications
)]
=> Lint improvements

der/src/asn1/any.rs, der/src/asn1/bit_string.rs, der/src/asn1/generalized_time.rs, der/src/asn1/integer.rs, der/src/asn1/integer/bigint.rs, der/src/asn1/internal_macros.rs, der/src/asn1/null.rs, der/src/asn1/octet_string.rs, der/src/asn1/printable_string.rs, der/src/asn1/teletex_string.rs, der/src/asn1/utc_time.rs, der/src/asn1/utf8_string.rs, der/src/asn1/videotex_string.rs, pkcs1/tests/params.rs, pkcs5/src/pbes2.rs, pkcs7/tests/content_tests.rs, pkcs8/tests/private_key.rs, spki/src/algorithm.rs, spki/tests/spki.rs, x509-cert/tests/certreq.rs
Also renames `decode_into` -> `decode_as`
Removes almost all inherent methods for inherent ASN.1 types like `AnyRef::oid` and `AnyRef::octet_string`. `Any::sequence` is retained.
Replaces them with `Any::decode_as<T>`.
This simplifies the API by pushing things through the more flexible generic type-based API.
=> der: remove inherent `AnyRef` decoding methods

der/src/asn1/any.rs, x509-ocsp/src/lib.rs
Add value function to Any to address #832. Also changes BasicOcspResponse to use AlgorithmIdentifierOwned (the repo needs similar owned treatment as x509-cert but changing this one field is an immediate need).
=> der: add `Any::value` accessor

der/src/error.rs, der/src/length.rs, der/src/lib.rs
Per #823 and #827, making PKCS#7 work interoperably will involve supporting at limited number of BER productions, one of which is indefinite lengths.
The current built-in `Length` type rejects them, as a proper DER parser is expected to.
This commit adds a separate `IndefiniteLength` type as a newtype of `Option<Length>` with support for parsing indefinite lengths.
=> der: add `IndefiniteLength` type

der/src/asn1/any.rs, der/src/asn1/bit_string.rs, der/src/asn1/ia5_string.rs, der/src/asn1/integer/bigint.rs, der/src/asn1/printable_string.rs, der/src/asn1/teletex_string.rs, der/src/bytes_owned.rs, der/src/bytes_ref.rs, der/src/referenced.rs, der/src/str_owned.rs, der/src/str_ref.rs, spki/src/algorithm.rs, spki/src/spki.rs
The naming of the `to_owned` method was a bit unfortunate as it triggered conflicts with the `alloc::borrow::ToOwned` method. When used, this would make for compiler messages asking things like:
```
error[E0034]: multiple applicable items in scope
--> certval/src/validator/name_constraints_set.rs:748:34
|
748 |                         value: a.to_owned(),
|                                  ^^^^^^^^ multiple `to_owned` found
|
= note: candidate #1 is defined in an impl of the trait `RefToOwned` for the type `AnyRef<'a>`
= note: candidate #2 is defined in an impl of the trait `ToOwned` for the type `T`
help: disambiguate the associated function for candidate #1
|
748 |                         value: RefToOwned::to_owned(&a),
|                                ~~~~~~~~~~~~~~~~~~~~~~~~
help: …
```
=> der, spki: rename to_owned method

der/src/asn1/any.rs, der/src/asn1/bit_string.rs, der/src/asn1/generalized_time.rs, der/src/asn1/integer/bigint.rs, der/src/asn1/internal_macros.rs, der/src/asn1/null.rs, der/src/asn1/octet_string.rs, der/src/asn1/printable_string.rs, der/src/asn1/teletex_string.rs, der/src/asn1/utc_time.rs, der/src/asn1/utf8_string.rs, der/src/asn1/videotex_string.rs
This removes some duplication but most importantly adds the missing implementations.
=> der: missing impl TryFrom<AnyRef>

.github/workflows/crmf.yml, Cargo.lock, crmf/Cargo.toml, crmf/README.md, crmf/src/controls.rs
- Remove unused dependencies
- Bump version back to 0.0.0 (crate is unpublished)
- Fix links in README.md
- Fix capitalization style for `PkiArchiveOptions`
- Add CI configuration
=> crmf: minor fixups

tls_codec/README.md
The path needed to be updated per
https://github.com/badges/shields/issues/8671
=> Fix tls_codec-ci badge

tls_codec/derive/src/lib.rs, tls_codec/derive/tests/decode.rs, tls_codec/src/primitives.rs
This PR fixes deriving tls_codec for generic structs (missing some types and bounds) and adds a blanked implementation for `PhantomData`.
=> tls_codec: fix generics

cms/src/enveloped_data.rs, crmf/src/controls.rs, crmf/src/pop.rs, der/src/asn1/sequence.rs, der/src/decode.rs, der/src/encode.rs, x509-cert/src/certificate.rs
=> Added blanket impls for Box<T> for DecodeValue, EncodeValue and Sequence.

Cargo.lock, serdect/Cargo.toml, serdect/tests/toml.rs
The test was wrong in the first place, a string can't just sit there in TOML without a table.
Replaces https://github.com/RustCrypto/formats/pull/863.
=> serdect: bump `toml` to v0.7; fix test

const-oid/oiddbgen/rfc8410.txt, const-oid/oiddbgen/src/main.rs, const-oid/src/db/gen.rs
This includes: Ed25519, Ed448, X25519 and X448.
This RFC & the relevant OIDs aren't included in the IANA LDAP CSV. The full text of the RFC is included as an alternative.
=> const-oid: Add OIDs from rfc8410.

x509-cert/Cargo.toml
Just a small thing, noticed while trying to use the `Error` trait through a re-export here.
=> x509-cert: std feature implies const-oid/std

tls_codec/src/tls_vec.rs
Read::read is not guaranteed to fill the whole output buffer.
=> Replace Read::read with read_exact

der/src/asn1/bit_string.rs, der/src/asn1/generalized_time.rs, der/src/asn1/integer/bigint.rs, der/src/asn1/internal_macros.rs, der/src/asn1/null.rs, der/src/asn1/octet_string.rs, der/src/asn1/utc_time.rs
Renames the vague `impl_type!` macro to `impl_any_conversions!` and eliminates the use of superfluous nested modules.
=> der: cleanup `Any*` conversions

.github/workflows/base64ct.yml, Cargo.lock, Cargo.toml
Removes toplevel `Cargo.toml` to allow building on MSRV <1.60
=> base64ct: add back to workspace

base64ct/Cargo.lock
This crate has its own Cargo.lock so it can still build on MSRV
=> base64ct: bump dependencies

.github/workflows/base16ct.yml, .github/workflows/base32ct.yml, .github/workflows/base64ct.yml, .github/workflows/const-oid.yml, .github/workflows/crmf.yml, .github/workflows/der.yml, .github/workflows/pem-rfc7468.yml, .github/workflows/pkcs1.yml, .github/workflows/pkcs5.yml, .github/workflows/pkcs7.yml, .github/workflows/pkcs8.yml, .github/workflows/sec1.yml, .github/workflows/security-audit.yml, .github/workflows/serdect.yml, .github/workflows/spki.yml, .github/workflows/tai64.yml, .github/workflows/tls_codec.yml, .github/workflows/workspace.yml, .github/workflows/x509-cert.yml
Actions provided by https://github.com/actions-rs are unmaintained.
This switches to `dtolnay/rust-toolchain` which is maintained and much more minimal.
=> CI: use `dtolnay/rust-toolchain`

der/src/asn1/integer/int.rs, der/src/asn1/integer/uint.rs
Now that code has been factored into the appropriate modules in #881 the visibility of various integer decoding/encoding functions can be much more restricted.
This removes `pub(super)` where it's now unnecessary.
=> der: remove `pub(super)` from integer functions

Cargo.lock, base32ct/CHANGELOG.md, base32ct/Cargo.toml
=> base32ct v0.2.0

Cargo.lock, base64ct/CHANGELOG.md, base64ct/Cargo.toml, base64ct/tests/proptests.rs, pem-rfc7468/Cargo.toml, spki/Cargo.toml
=> base64ct v1.6.0

Cargo.lock, sec1/Cargo.toml, serdect/CHANGELOG.md, serdect/Cargo.toml
- Bump `base16ct` dependency to v0.2 ([#890])
- TOML test ([#864])
[#864]: https://github.com/RustCrypto/formats/pull/864
[#890]: https://github.com/RustCrypto/formats/pull/890
=> serdect v0.2.0

Cargo.lock, der/Cargo.toml, pem-rfc7468/CHANGELOG.md, pem-rfc7468/Cargo.toml
=> pem-rfc7468 v0.7.0

.github/workflows/const-oid.yml, .github/workflows/crmf.yml, .github/workflows/x509-cert.yml, Cargo.lock, cmpv2/Cargo.toml, cmpv2/src/status.rs, cms/Cargo.toml, cms/src/cert.rs, cms/src/content_info.rs, cms/src/enveloped_data.rs, cms/src/signed_data.rs, const-oid/CHANGELOG.md, const-oid/Cargo.toml, crmf/Cargo.toml, der/Cargo.toml, der/src/lib.rs, pkcs1/Cargo.toml, pkcs7/Cargo.toml, x509-cert/Cargo.toml, x509-cert/src/anchor.rs, x509-cert/src/ext/pkix/crl/dp.rs, x509-cert/src/ext/pkix/keyusage.rs, x509-ocsp/Cargo.toml
The `const-oid` crate is a shared dependency with many other crates including the `digest` crate and several hash function implementations, which makes upgrading it rather tricky.
This punts on upgrading it for this release cycle of the `der` crate and its dependencies so we can coordinate on an upgrade along with `digest`.
=> Downgrade `const-oid` to v0.9
