.github/workflows/cmpv2.yml
.github/workflows/cms.yml
.github/workflows/crmf.yml
.github/workflows/pkcs12.yml
.github/workflows/x509-ocsp.yml
x509-ocsp/Cargo.toml

The following crates did not have a CI config (most of which are newly merged and/or nascent):
- `cmpv2`
- `cms`
- `pkcs12`
- `x509-ocsp`

CI: add missing configuration files

---

Cargo.lock
crmf/Cargo.toml
der/CHANGELOG.md
der/Cargo.toml
der/derive/CHANGELOG.md
der/derive/Cargo.toml
pkcs1/Cargo.toml
pkcs5/Cargo.toml
pkcs7/Cargo.toml
pkcs8/Cargo.toml
sec1/Cargo.toml
spki/Cargo.toml
x509-cert/Cargo.toml
x509-ocsp/Cargo.toml

- `OwnedtoRef`/`RefToOwned` traits; MSRV 1.65 ([#797])
- `OctetStringRef::decode_into` ([#817])
- `Int` and `IntRef` types ([#823])
- `IndefiniteLength` type ([#830])
- `Any::value` accessor ([#833])
- Buffered PEM reader ([#839])
- `OctetString::into_bytes` ([#845])
- Blanket impls on `Box<T>` for `DecodeValue`, `EncodeValue`, and `Sequence` ([#860])
- Rename `UIntRef` => `UintRef` ([#786])
- Replace use of `dyn Writer` with `impl Writer` ([#828])
- Rename `AnyRef::decode_into` -> `::decode_as` ([#829])
- Bump `pem-rfc7468` dependency to v0.7 ([#894])
- Rename `Encode::to_vec` => `::to_der` ([#898])
- `Sequence::fields` method ([#828])
- Inherent `AnyRef` decoding methods ([#829])
[#786]: https://github.com/RustCrypto/formats/pull/786
[#797]: …

der v0.7.0

---

.github/workflows/spki.yml
Cargo.lock
crmf/Cargo.toml
pkcs1/Cargo.toml
pkcs5/Cargo.toml
pkcs7/Cargo.toml
pkcs8/Cargo.toml
spki/CHANGELOG.md
spki/Cargo.toml
spki/src/spki.rs
spki/tests/spki.rs
x509-cert/Cargo.toml
x509-ocsp/Cargo.toml

- Make `AlgorithmIdentifier` generic around `Params` ([#769])
- Use blanket impls for `Decode*` traits ([#785])
- Make `SubjectPublicKeyInfo` own the public key ([#790])
- Rename `to_owned` method ([#835])
[#769]: https://github.com/RustCrypto/formats/pull/769
[#785]: https://github.com/RustCrypto/formats/pull/785
[#790]: https://github.com/RustCrypto/formats/pull/790
[#835]: https://github.com/RustCrypto/formats/pull/835

spki v0.7.0

---

Cargo.lock
cms/Cargo.toml
pkcs5/CHANGELOG.md
pkcs5/Cargo.toml
pkcs8/Cargo.toml

- Bump `spki` dependency to v0.7 ([#900])

pkcs5 v0.7.0

---

Cargo.lock
pkcs1/Cargo.toml
pkcs8/CHANGELOG.md
pkcs8/Cargo.toml
sec1/Cargo.toml

- Use blanket impls for `Decode*` traits ([#785])
- Bump `spki` dependency to v0.7 ([#900])
- Bump `pkcs5` dependency to v0.7 ([#901])
[#785]: https://github.com/RustCrypto/formats/pull/785
[#901]: https://github.com/RustCrypto/formats/pull/901

pkcs8 v0.10.0

---

Cargo.lock
pkcs1/CHANGELOG.md
pkcs1/Cargo.toml

- Make PSS/OAEP params use generic `AlgorithmIdentifier` ([#799])
- Bump `spki` dependency to v0.7 ([#900])
- Bump `pkcs8` to v0.10 ([#902])
[#799]: https://github.com/RustCrypto/formats/pull/799
[#902]: https://github.com/RustCrypto/formats/pull/902

pkcs1 v0.7.0

---

Cargo.lock
sec1/CHANGELOG.md
sec1/Cargo.toml

- MSRV 1.65 ([#805])
- Bump `serdect` to v0.2 ([#893])
- Bump `spki` dependency to v0.7 ([#900])
- Bump `pkcs8` to v0.10 ([#902])
[#805]: https://github.com/RustCrypto/formats/pull/805
[#893]: https://github.com/RustCrypto/formats/pull/893
[#902]: https://github.com/RustCrypto/formats/pull/902

sec1 v0.7.0

---

sec1/Cargo.toml
sec1/src/lib.rs
sec1/src/private_key.rs
sec1/tests/private_key.rs
sec1/tests/traits.rs

Regression where the version number was lost from the encoder as part of the changes in #828.
It wasn't caught due to a lack of an encoding test, which has been added in this PR.

sec1: encode `ECPrivateKey` version

---

Cargo.lock
sec1/CHANGELOG.md
sec1/Cargo.toml

- Encode `ECPrivateKey` version ([#908])
[#908]: https://github.com/RustCrypto/formats/pull/908

sec1 v0.7.1

---

tls_codec/src/arrays.rs
tls_codec/src/lib.rs
tls_codec/src/quic_vec.rs

This PR makes it so that the `Debug`-print of `VLBytes` and `VLByteSlice` will have an additional comment `/* 0x... */` with the hex representation of the bytes.
Example: `Debug`-print of `VLBytes { vec: [0] }`:
```
VLBytes { vec: [0] /* 0x00 */ }
// "Pretty"
VLBytes {
vec: [
0,
] /* 0x00 */,
}
```
I decided against `[0x00, 0x01, ...]` because `0x0001` seems more useful to copy&paste (for use in hex editors, Python's binascii.unhexlify, JSON, ...). Also, having both representations at hand might be useful as well.

tls_codec: feat: Append a comment with the hex representation of `VLBytes` during `Debug`-printing.

---

pkcs5/CHANGELOG.md
pkcs5/Cargo.toml

- Bump `pbkdf2` to v0.12 ([#913])
- Bump `scrypt` to v0.11 ([#913])
[#913]: https://github.com/RustCrypto/formats/pull/913

pkcs5 v0.7.1

---

Cargo.lock
pkcs8/CHANGELOG.md
pkcs8/Cargo.toml

- `sha1-insecure` feature ([#913])
[#913]: https://github.com/RustCrypto/formats/pull/913

pkcs8 v0.10.1

---

pkcs1/src/traits.rs

Changes the error type to `spki::Error`, which matches the error type used in the `spki::DecodePublicKey` blanket impl:
https://docs.rs/spki/0.7.0/spki/trait.DecodePublicKey.html#impl-DecodePublicKey-for-T
Also removes the bounds on `DecodePublicKey` in the blanket impl of `DecodeRsaPublicKey`, since they aren't actually used.
This is a breaking change but also a bugfix, as with the previous bounds it's not possible to impl PKCS#1 support via these two blanket impls, since the error types don't match. The plan is to merge this, publish it, and yank the v0.7.0 release.

pkcs1: fixups for `DecodeRsaPublicKey` blanket impl

---

pkcs1/CHANGELOG.md
pkcs1/Cargo.toml

- `DecodeRsaPublicKey` blanket impl ([#916])
[#916]: https://github.com/RustCrypto/formats/pull/916

pkcs1 v0.7.1

---

der/Cargo.toml

Previously `zeroize`'s `alloc` feature would be enabled if `zeroize` was enabled in `der`. Now `zeroize`'s `alloc` feature is only enabled if this `der`'s `alloc` feature is enabled.
---
We were hoping to use p256 in a no-alloc environment. Moving p256 from 0.12.0->0.13.0 results in `alloc` getting pulled in.
It looks like when `sec1` went from 0.3.0->0.7.1, https://github.com/RustCrypto/formats/compare/sec1/v0.3.0...sec1/v0.7.1#diff-fe7c93733c51ed30397c61754e6d22958291335b1d61470ce78edcdf49a09399R36 its `der` dependency now uses `zeroize`. The `zeroize` dependency in `der` was calling out `alloc`.
Looking through `der` and `sec1` it seems that `alloc` + `zerioze` is only needed for `der`'s [document.rs](https://github.com/RustCrypto/formats/blob/master/der/src/document.rs).
Making this …

`der`: Make `zeroize`'s `alloc` feature conditional

---

tls_codec/derive/src/lib.rs

Added the name of the struct/enum where the error has occured to help tracking implementation errors

tls_codec: Improve error message in derived tls_deserialize

---

pkcs7/src/content_info.rs
pkcs7/tests/content_tests.rs

It appears between [RFC 2315](https://datatracker.ietf.org/doc/html/rfc2315#section-7) and [RFC 5652](https://datatracker.ietf.org/doc/html/rfc5652#section-3), the definition of the `content` field changed and is not optional anymore.

pkcs7: content is not optional anymore

---

der/src/lib.rs
der/src/reader.rs

`NestedReader` is exposed through `Reader::read_nested` but it's not documented.

der: expose NestedReader

---

cmpv2/Cargo.toml
cms/Cargo.toml
crmf/Cargo.toml

Be explicit about prerelease versions with `=` requirements

cmpv2+cms+crmf: version requirement fixups

---

Cargo.lock
cmpv2/Cargo.toml
cms/Cargo.toml
crmf/Cargo.toml
pkcs7/Cargo.toml
x509-cert/CHANGELOG.md
x509-cert/Cargo.toml
x509-ocsp/Cargo.toml

- Feature-gated `Arbitrary` impl for `Certificate` ([#761])
- Allow request to be serialized to PEM ([#819])
- `Display` impl for `SerialNumber` ([#820])
- `std` feature implies `const-oid/std` ([#874])
- Serial numbers are formatted as `PrintableString` ([#794])
- `SerialNumber` is now a specialized object ([#795])
- MSRV 1.65 ([#805])
- Make types owned instead of reference-based ([#806], [#841])
- Bump `der` to v0.7 ([#899])
- Bump `spki` to v0.7 ([#900])
- Handling of negative serial numbers ([#823], [#831])
- `alloc` feature: now unconditionally required ([#841])
[#761]: https://github.com/RustCrypto/formats/pull/761
[#794]: https://github.com/RustCrypto/formats/pull/794
[#795]: https://github.com/RustCrypto/formats/pull/795
[#805]: https://github.com/RustCrypto/formats/pull/805 …

x509-cert v0.2.0

---

Cargo.lock
pkcs7/CHANGELOG.md
pkcs7/Cargo.toml

- `SignedData` type to ([#813])
- `ValueOrd` impls ([#825])
- MSRV 1.65 ([#805])
- Bump `der` to v0.7 ([#899])
- Bump `spki` to v0.7 ([#900])
- Make `ContentInfo`'s `contentType` mandatory ([#924])
- Bump `x509-cert` to v0.2 ([#934])
[#805]: https://github.com/RustCrypto/formats/pull/805
[#813]: https://github.com/RustCrypto/formats/pull/813
[#825]: https://github.com/RustCrypto/formats/pull/825
[#924]: https://github.com/RustCrypto/formats/pull/924
[#934]: https://github.com/RustCrypto/formats/pull/934

pkcs7 v0.4.0

---

tls_codec/derive/src/lib.rs
tls_codec/derive/tests/attributes/test_that_duplicate_skip_attributes_dont_compile.stderr
tls_codec/derive/tests/attributes/that_skip_attribute_does_not_compile_on_enums.stderr
tls_codec/derive/tests/decode.rs
tls_codec/derive/tests/encode.rs

You can now provide paths to `#[tls_codec(discriminant = ...)]`, like so `#[tls_codec(discriminant ="path::to::const::or::enum::Variant")]`
I'm going to do a pass on documenting the new behavior and will undraft this PR.
Changes: 
* Allowed `PathExpr`s in `#[tls_codec(discriminant = ...)]` attributes that resolve to constants or enum variants that can be coerced to the enum's repr.
* Fixed the proc macros panicking instead of returning a compile time error

tls_codec: feat: Allow const exprs in discriminant attrs

---

x509-cert/src/attr.rs
x509-cert/src/name.rs
x509-cert/tests/name.rs

Defined on the following types:
- `RdnSequence`
- `RelativeDistingiushedName`
- `AttributeTypeAndValue`
The name is confusing and it can now be expressed as the combination of `FromStr` and `Encode::to_der`.

x509-cert: deprecate `encode_from_string` functions

---

Cargo.lock
x509-cert/CHANGELOG.md
x509-cert/Cargo.toml

- `FromStr` impls for `RdnSequence` (`Name`), `RelativeDistinguishedName`, and `AttributeTypeAndValue` ([#949])
- Deprecate `encode_from_string` functions ([#951])
[#949]: https://github.com/RustCrypto/formats/pull/949
[#951]: https://github.com/RustCrypto/formats/pull/951

x509-cert v0.2.1

---

.github/workflows/const-oid.yml
.github/workflows/der.yml
.github/workflows/spki.yml
.github/workflows/x509-cert.yml
der/Cargo.toml

This reverts commit 517adb7b82ee3774156a80c256d0b26e14246f74.
The issue in `arbitrary` has been fixed: rust-fuzz/arbitrary#136
See #837

const-oid+der+spki+x509-cert: re-enable min version check

---

spki/src/lib.rs
spki/src/traits.rs

This is an alternative to/continuation of #954, which defines both `AssociatedAlgorithmIdentifier` and `DynAssociatedAlgorithmIdentifier`, where the former provides an associated constant `AlgorithmIdentifierRef`, and the latter a trait/object-safe way to obtain an `AlgorithmIdentifierOwned` which can be computed from `&self`.
A blanket impl links the two.

spki: define trait to get associated `AlgorithmIdentifier`

---

const-oid/src/lib.rs
const-oid/tests/lib.rs

Adds a method for determining if one OID starts with another.

const-oid: add `ObjectIdentifier::starts_with`

---

der/src/asn1/oid.rs

This is useful for writing a blanket impl for converting generic `AlgorithmIdentifier<Params>` to `AlgorithmIdentifierOwned`, specifically for the `AlgorithmIdentifier<ObjectIdentifier>` case, but other types can opt into this same protocol.

der: add `From<ObjectIdentifier>` impl for `Any`

---

spki/src/traits.rs

Adds an associated `Params` type which is passed as `AlgorithmIdentifier<Params>`, which makes it *much* easier to define `AlgorithmIdentifier` constants.
Without this, `const fn` type conversions are required to `AnyRef<'static>`. This isn't currently possible for `ObjectIdentifier` for example.
cc @baloo @lumag

spki: add `AssociatedAlgorithmIdentifier::Params` type

---

.github/workflows/security-audit.yml

move audit-check to the one maintained by `rustsec` to stand away from nodejs 12.
See https://github.com/actions-rs/audit-check/issues/227

ci: nodejs12 is deprecated

---

Cargo.lock
der/CHANGELOG.md
der/Cargo.toml

- Expose `NestedReader ([#925])
- `From<ObjectIdentifier>` impl for `Any` ([#965])
- `Any::null` helper ([#969])
- `Any::encode_from` ([#976])
[#925]: https://github.com/RustCrypto/formats/pull/925
[#965]: https://github.com/RustCrypto/formats/pull/965
[#969]: https://github.com/RustCrypto/formats/pull/969
[#976]: https://github.com/RustCrypto/formats/pull/976

der v0.7.2

---

spki/src/traits.rs

Makes the associated type bounds `Tagged + EncodeValue` which means the blanket impls will always work.

spki: simplify bounds for `*AlgorithmIdentifier` traits

---

Cargo.lock
spki/CHANGELOG.md
spki/Cargo.toml

- `AssociatedAlgorithmIdentifier` trait ([#962], [#966])
- `DynAssociatedAlgorithmIdentifier` trait ([#962])
- `SignatureAlgorithmIdentifier` trait ([#967])
- `DynSignatureAlgorithmIdentifier` trait ([#967])
- Bump `der` dependency to v0.7.2 ([#979])
[#962]: https://github.com/RustCrypto/formats/pull/962
[#966]: https://github.com/RustCrypto/formats/pull/966
[#967]: https://github.com/RustCrypto/formats/pull/967
[#979]: https://github.com/RustCrypto/formats/pull/979

spki v0.7.1

---

Cargo.lock
pkcs8/CHANGELOG.md
pkcs8/Cargo.toml

- Bump `spki` to v0.7.1 ([#981])
[#981]: https://github.com/RustCrypto/formats/pull/981

pkcs8 v0.10.2

---

Cargo.lock
pkcs1/CHANGELOG.md
pkcs1/Cargo.toml

- `RsaPssParams::SALT_LEN_DEFAULT` ([#953])
[#953]: https://github.com/RustCrypto/formats/pull/953

pkcs1 v0.7.2

---

spki/src/algorithm.rs
spki/src/lib.rs

Type alias for `AlgorithmIdentifier<ObjectIdentifier>`

spki: add `AlgorithmIdentifierWithOid`

---

der/src/asn1/utc_time.rs

This is intended to be used in the x509 certificate builder to convert `GeneralTime` to `UtcTime` field in accordance with RFC5280.

der: export `asn1::UtcTime::MAX_YEAR`

---

Cargo.lock
tls_codec/Cargo.toml
tls_codec/derive/Cargo.toml
tls_codec/derive/src/lib.rs
tls_codec/derive/tests/decode.rs
tls_codec/src/lib.rs

This PR 
- fixes some warnings
- adds `tls_deserialize_exact` and `tls_deserialize_bytes` blanket implementations
- adds `UnknownValue` error for deserialising unknown types
- bumps the version to 0.3.0-pre.2

tls_codec: 0.3.0-pre.2 and more

---

x509-cert/src/ext/pkix/keyusage.rs

x509-cert: fix `KeyUsage` bit tests

---

Cargo.lock
der/CHANGELOG.md
der/Cargo.toml

- `UtcTime::MAX_YEAR` associated constant ([#989])
[#989]: https://github.com/RustCrypto/formats/pull/989

der v0.7.3

---

Cargo.lock
sec1/CHANGELOG.md
sec1/Cargo.toml

- Impl `ModulusSize` for `U24` ([#995])
[#995]: https://github.com/RustCrypto/formats/pull/995

sec1 v0.7.2

---

Cargo.toml
cmpv2/Cargo.toml
cms/Cargo.toml
crmf/Cargo.toml
der/Cargo.toml
pem-rfc7468/Cargo.toml
pkcs1/Cargo.toml
pkcs5/Cargo.toml
pkcs7/Cargo.toml
pkcs8/Cargo.toml
sec1/Cargo.toml
serdect/Cargo.toml
spki/Cargo.toml
tls_codec/Cargo.toml
x509-cert/Cargo.toml
x509-ocsp/Cargo.toml

When cyclic dependencies are used for either doctests or integrations tests (`x509-cert` depends on `rsa` which depends back to `der` in this workspace), the compiler will complain about lack of trait implementation because two crates will be pulled. One from this checkout as well as one from crates.io.
This migrates the inclusion from local `path` in each Cargo.toml to a global `patch.crates-io`.

Handle cyclic dependencies

---

pkcs7/Cargo.toml
pkcs7/src/algorithm_identifier_types.rs
pkcs7/src/lib.rs
pkcs7/src/signed_data_content.rs
pkcs7/src/signer_info.rs
pkcs7/tests/content_tests.rs

This is a proposal (say: a trial ballon) for how PKSC #7 messages could be created. The work is not done with this request. Signing and encryption is missing, but by making some types public, we can at least get a PKSC #7 scaffolding with certificates.
Is this a good way? Should I proceed with it? Or do you already have other plans?

Creating PKCS #7 messages

---

x509-cert/Cargo.toml
x509-cert/src/builder.rs
x509-cert/test-support/src/zlint.rs
x509-cert/tests/builder.rs

I started rebasing my code to use `CertificateBuilder` and I had to make several useful modifications.
Note: It is still not possible to create RSA PSS certificates, since there is no `Signer` implementation for RSA PSS, only `RandomizedSigner` (there is no standard detereministic RSA PSS signature process).  Locally I have changed the `CertificateBuilder` to accept `RandomizedSigner` instead of bare `Signer`, however this doesn't look like an universal solution too.

small builder updates

---

pkcs1/src/params.rs
pkcs1/tests/params.rs

- Use NULL parameters for digest params (as required by mozilla)
- Add functions to construct known-good parameters.

RsaPssParams and RsaOaepParams fixes

---

Cargo.lock
pkcs1/CHANGELOG.md
pkcs1/Cargo.toml

- Provide functions to construct `RsaPss` and `RsaOaepParams` ([#1010])
- Use `NULL` parameters for SHA `AlgorithmIdentifier`s ([#1010])
[#1010]: https://github.com/RustCrypto/formats/pull/1010

pkcs1 v0.7.3

---

der/src/decode.rs
der/src/encode.rs
der/tests/derive.rs

Allows `PhantomData` fields to be used with custom derive.
cc @baloo

der: add `Decode` and `Encode` impls for `PhantomData`

---

der/src/ord.rs

similar to #1009, provide a `der::DerOrd` and a `der::ValueOrd` noop implementation for PhantomData

der: provide a noop implementation for PhantomData

---

der/derive/src/choice.rs
der/derive/src/lib.rs
der/derive/src/sequence.rs

this is required for #987 to have parsing profiles like:
```rust
#[derive(Clone, Debug, Eq, PartialEq, Sequence, ValueOrd)]
pub struct CertificateInner<P: Profile = Rfc5280> {
pub tbs_certificate: TbsCertificate<P>,
pub signature_algorithm: AlgorithmIdentifierOwned,
pub signature: BitString,
}
```

der_derive: handle type generics in sequence

---

Cargo.lock
der/derive/CHANGELOG.md
der/derive/Cargo.toml

Added
- Support for type generics in `Sequence` macro ([#1014])
[#1014]: https://github.com/RustCrypto/formats/pull/1014

der_derive v0.7.1

---

Cargo.lock
der/CHANGELOG.md
der/Cargo.toml

Added
- `Decode` and `Encode` impls for `PhantomData` (#1009)
- `ValueOrd` and `DerOrd` impls for `PhantomData` (#1012)
Changed
- Bump `hex-literal` dependency to v0.4.1 (#999)
- Bump `der_derive` dependency to v0.7.1 (#1016)

der v0.7.4

---

x509-cert/src/builder.rs
x509-cert/src/certificate.rs

The `PhantomData` wasn't actually required in `TbsCertificate` (it's in `SerialNumber`)

x509-cert: extraneous PhantomData in `TbsCertificate`

---

Cargo.lock
pkcs1/Cargo.toml
pkcs1/src/traits.rs

Avoid pulling in dep `pkcs8` or `zeroize` just because feature `alloc` or `pem` is enabled.

Fix feature `alloc` and `pem` in `pkcs1`

---

Cargo.lock
pkcs1/CHANGELOG.md
pkcs1/Cargo.toml

- Have `alloc` feature only weakly activate `pkcs8?/alloc` ([#1013])
- Have `pem` feature only weakly activate `pkcs8?/pem` ([#1013])
[#1013]: https://github.com/RustCrypto/formats/pull/1013

pkcs1 v0.7.4

---

pkcs1/src/traits.rs

When building with the `alloc` and `pkcs8` features, the following error occurs:
```
error[E0433]: failed to resolve: use of undeclared type `RsaPrivateKey`
--> /Users/tarcieri/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pkcs1-0.7.4/src/traits.rs:190:9
|
190 |         RsaPrivateKey::from_der(pkcs8_key.private_key)?.try_into()
|         ^^^^^^^^^^^^^ use of undeclared type `RsaPrivateKey`
|
help: consider importing this struct
|
3   | use crate::RsaPrivateKey;
|
error[E0433]: failed to resolve: use of undeclared type `RsaPublicKey`
--> /Users/tarcieri/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pkcs1-0.7.4/src/traits.rs:200:9
|
200 |         RsaPublicKey::from_der(spki.subject_public_key.raw_bytes())?.try_into()
|         ^^^^^^^^^^^^ use of undeclared type `RsaPublicKey` …
```

pkcs1: fix import failure

---

der/src/asn1/generalized_time.rs
der/src/datetime.rs

When certificates are burned in hardware, the expiration date could be set to infinity.
For example with IDevID when burned to TPM:
https://trustedcomputinggroup.org/wp-content/uploads/TPM-2p0-Keys-for-Device-Identity-and-Attestation_v1_r12_pub10082021.pdf#page=55
Part1 of #1024

der: adds support for `DateTime::INFINITY`

---

x509-cert/Cargo.toml
x509-cert/src/time.rs

When certificates are burned in hardware, the expiration date could be set to infinity.
For example with IDevID when burned to TPM:
https://trustedcomputinggroup.org/wp-content/uploads/TPM-2p0-Keys-for-Device-Identity-and-Attestation_v1_r12_pub10082021.pdf#page=55

x509-cert: adds support for `Time::INFINITY`

---

tls_codec/Cargo.toml
tls_codec/src/lib.rs
tls_codec/src/quic_vec.rs

In contrast to the generic tls_vec implementations, there is no `Secret...` variant for VLBytes. Since the overhead is relatively low, this PR blanket-implements ZeriozeOnDrop for VLBytes. In the future, it might be worth exposing a dedicated `SecretVLBytes` struct.

Derive Zeroize and ZeroizeOnDrop for VLBytes

---

der/src/tag.rs

The tag was previously configured to be 0x1D.
The correct decimal value of BMPString's tag is 30, or 0x1E in hex.

der: fix off-by-one error in `BMPString` tag

---

x509-cert/src/builder.rs
x509-cert/src/ext.rs
x509-cert/src/ext/pkix.rs
x509-cert/src/ext/pkix/constraints/basic.rs
x509-cert/src/ext/pkix/keyusage.rs
x509-cert/src/macros.rs
x509-cert/src/request.rs
x509-cert/test-support/src/openssl.rs
x509-cert/tests/builder.rs

Fixes https://github.com/RustCrypto/formats/issues/1031
Generates CSR like:
```
---- certificate_request stdout ----
Certificate Request:
Data:
Version: 1 (0x0)
Subject: CN = service.domination.world
Subject Public Key Info:
Public Key Algorithm: id-ecPublicKey
Public-Key: (256 bit)
pub:
04:1c:ac:ff:b5:5f:2f:2c:ef:d8:9d:89:eb:37:4b:
26:81:15:24:52:80:2d:ee:a0:99:16:06:81:37:d8:
39:cf:7f:c4:81:a4:44:92:30:4d:7e:f6:6a:c1:17:
be:fe:83:a8:d0:8f:15:5f:2b:52:f9:f6:18:dd:44:
70:29:04:8e:0f
ASN1 OID: prime256v1
NIST CURVE: P-256
Attributes:
Requested Extensions:
X509v3 Subject Alternative Name:
IP Address:192.0.2.0
Signature Algorithm: ecdsa-with-SHA256
Signature Value:
73:29:74:17:23:a1:12:f4:94:82:3e:b8:8b:eb:f4:21:f4:80:
7e:ba:1a:0e:63:b4:ea:03:5e:6c:87:43:f1:01:6d:19:34:3c: …
```

x509-cert: adds a `CertReq` builder

---

Cargo.lock
x509-cert/Cargo.toml

rsa 0.9.1 provides a fix for invalid signatures sometimes generated

x509-cert: fixup CI flakiness

---

Cargo.lock
cms/CHANGELOG.md
cms/Cargo.toml
cms/src/cert.rs
cms/src/lib.rs

- Convenience functions for converting cert(s) to certs-only `SignedData` message ([#1032])
[#1032]: https://github.com/RustCrypto/formats/pull/1032

cms v0.2.1

---

spki/src/lib.rs
spki/src/traits.rs

This is used to differentiate the different encoding for signatures as x509 related structures rely on `BitString` encoding of the various signatures.
This is mostly used as a marker trait to ensure misuse resistance of the API.
See #1043 #1041

spki: Adds a `SignatureBitStringEncoding` trait

---

der/src/asn1/utc_time.rs
x509-cert/src/time.rs

It looks like `UtcTime` currently has a lower bound of 1970.
I'm very open to wording tweaks IFF a documentation change ends up being the way to address this.
RFC 5280 says that `UTCTime` is 1950-2049, however due the common use of
computer times being based off of `UNIX_EPOCH` the implementation of
[`UtcTime`](https://docs.rs/der/latest/der/asn1/struct.UtcTime.html) is limited to 1970.
This limitation is due to the `MIN_YEAR` bounding valid
[`DateTime`](https://docs.rs/der/latest/der/struct.DateTime.html)
structs.
The `DateTime` struct is the underlying implementation of `UTCTime`.
Thanks!

Add notes about `UTCTime` range being 1970-2049

---

Cargo.lock
x509-cert/Cargo.toml
x509-cert/src/builder.rs

This shows the use of #1047
This uses:
- https://github.com/RustCrypto/signatures/pull/716
- https://github.com/RustCrypto/RSA/pull/328

x509-cert: consume the `SignatureBitStringEncoding` trait

---

cms/Cargo.toml
cms/README.md
pkcs7/Cargo.toml
pkcs7/README.md

This commit adds a deprecation notice to README.md for the `pkcs7` crate announcing `cms` as its official successor.
Notably `pkcs7` predates many of the other format-related crates and uses entirely reference-based conventions which we migrated away from in the `x509-cert` crate. `cms` uses the newer conventions, and is more complete as a Cryptographic Message Syntax implementation.
We will not be accepting pull requests for `pkcs7` and are leaving its source code for now only to aid in porting functionality not yet present in the `cms` crate.
When the next breaking release of `der` occurs, we will delete the `pkcs7` source code from the repository, leaving only the deprecation notice to help assist people migrating.
Closes #1045.

pkcs7: deprecate in favor of `cms`

---

Cargo.lock
pkcs7/CHANGELOG.md
pkcs7/Cargo.toml

This release deprecates the `pkcs7` crate in favor of the `cms` crate

pkcs7 v0.4.1

---

der/src/asn1/set_of.rs
der/src/error.rs
der/tests/set_of.rs

The `TryFrom` constructors were not properly tested for the handling of duplicate items and allowed them to be inserted.
This commit fixes the handling and adds tests. In the event there are duplicates in a set, a newly added `ErrorKind::SetDuplicate` variant is returned with the error type.

der: fix handling of non-unique items in `SetOf`(Vec)

---

.github/workflows/pkcs7.yml
.github/workflows/x509-cert.yml
cms/src/content_info.rs
der/src/arrayvec.rs
der/src/asn1/sequence_of.rs
der/src/asn1/set_of.rs
pkcs7/tests/content_tests.rs
x509-cert/fuzz/Cargo.toml
x509-cert/src/builder.rs
x509-cert/src/request.rs
x509-cert/tests/name.rs

Renames the insertion methods on `SetOf` and `SetOfVec` from `add` to `insert_ordered`, deprecating the previous `add` method.
Also adds an `insert` method which pushes onto the underlying `(Array)Vec` then calls `der_sort`. This should be relatively fast since the underlying algorithm is insertion sort and operating on data which is mostly in-order.
The name `insert` is more consistent with `BTreeSet`/`HashSet`.

der: add `SetOf(Vec)::insert(_ordered)`; deprecate `add`

---

Cargo.lock
der/CHANGELOG.md
der/Cargo.toml
pkcs7/Cargo.toml
x509-cert/Cargo.toml

- `SetOfVec::{extend, from_iter}` methods ([#1065])
- `SetOf(Vec)::{insert, insert_ordered}` methods ([#1067])
- Deprecate `SetOf(Vec)::add` ([#1067])
- Off-by-one error in `BMPString` tag ([#1037])
- Handling of non-unique items in `SetOf`(Vec) ([#1066])
[#1037]: https://github.com/RustCrypto/formats/pull/1037
[#1065]: https://github.com/RustCrypto/formats/pull/1065
[#1066]: https://github.com/RustCrypto/formats/pull/1066
[#1067]: https://github.com/RustCrypto/formats/pull/1067

der v0.7.6

---

x509-cert/CHANGELOG.md

Added
- Certificate builder ([#764])
- Support for `RandomizedSigner` in builder ([#1007])
- Provide parsing profiles ([#987])
- Support for `Time::INFINITY` ([#1024])
- Conversion from `std::net::IpAddr` ([#1035])
- `CertReq` builder ([#1034])
- missing extension implementations ([#1050])
- notes about `UTCTime` range being 1970-2049 ([#1052])
- consume the `SignatureBitStringEncoding` trait ([#1048])
Changed
- use `ErrorKind::Value` for overlength serial ([#988])
- Bump `hex-literal` to v0.4.1 ([#999])
- Builder updates ([#1001])
- better debug info when `zlint` isn't installed ([#1018])
- make SKI optional in leaf certificate ([#1028])
- bump rsa from 0.9.0-pre.2 to 0.9.0 ([#1033])
- bump rsa from 0.9.1 to 0.9.2 ([#1056])
Fixed
- fix `KeyUsage` bit tests ([#993])
- extraneous …

x509-cert: v0.2.2

---

gss-api/README.md

Fixes some links in `README` to point to correct crate

fix doc links in new `gss-api` crate

---

.github/workflows/cmpv2.yml
.github/workflows/cms.yml
.github/workflows/crmf.yml
.github/workflows/x509-cert.yml
cms/Cargo.toml

All of the blockers on these checks should now be resolved

CI: re-enable all minimal-versions checks

---

Cargo.lock
x509-cert/CHANGELOG.md
x509-cert/Cargo.toml

Added
- Added `TryFrom` for `RelativeDistinguishedName` ([#1092])
- Load a chain of certificates from a slice ([#1081])

x509-cert: v0.2.3

---

tls_codec/src/quic_vec.rs
tls_codec/tests/decode.rs
tls_codec/tests/encode.rs

- Lengths over 2 bytes were serialised with an incorrect prefix
- Fixed off-by-one errors on encoding length boundaries
- Length prefix should be the logarithm of the number of bytes to read to extract the length

tls_codec: Fix variable length encoding

---

const-oid/oiddbgen/rfc6962.txt
const-oid/oiddbgen/src/main.rs
const-oid/src/db/gen.rs

This PR adds OIDs from [RFC 6962](https://www.rfc-editor.org/rfc/rfc6962).

const_oid: add RFC 6962 OIDs

---

sec1/src/point.rs

It would be nice to be able to have public ssh keys implement Hash so that they can be used as HashMap keys or be put in HashSets. 
This minimal change will in turn make it possible to do the analogous change in [ssh-key](https://github.com/RustCrypto/SSH/tree/master/ssh-key)

Add Hash implementation to EncodedPoint

---

const-oid/oiddbgen/rfc8894.md
const-oid/oiddbgen/src/main.rs
const-oid/src/db/gen.rs

RFC 8894 can't be easily parsed, as the OID definitions were formatted in an ASCII table with line breaks. Thus, I created a new markdown file for these OIDs.

Added RFC 8894 (SCEP) OIDs

---

x509-cert/src/name.rs
x509-cert/tests/name.rs

x509-cert: fixup RDN string representation

---

tls_codec/src/primitives.rs
tls_codec/tests/decode.rs

The implementation of `Option<T>` had a small bug, where the remainder was not returned correctly. This PR fixes that bug and adds a small test to test for its presence.

tls_codec: fix deserialization of `Option<T>`

---

const-oid/src/db.rs

Multiple RFCs may be defining the same OID. This commit provides a `Database::find_names_for_oid` method that will return all values that were matched.

const-oid: return all matched names when looking up oid

---

x509-cert/Cargo.toml
x509-cert/src/attr.rs
x509-cert/tests/name.rs

Before this commit, the string serialization will format some attributes with the longer name when the same OID was provided by two RFC.
For example this would use `STATEORPROVINCENAME` instead of `ST` for oid 2.5.4.8

x509-cert: use the shortest name when looking attr OID

---

Cargo.lock

with #1130 there were changes in `Cargo.lock` missing after the bump of `const-oid` version.

Missing `Cargo.lock` changes

---

tls_codec/src/tls_vec.rs
tls_codec/tests/decode_bytes.rs

This PR fixes the bug found in #1109. It adds a `DeserializeBytes::tls_deserialize` test for each of the `TlsByteVecUX` types and fixes the bug.

Fix TlsByteVecUX deserialization

---

cms/src/builder.rs

The current implementation of `SignedDataBuilder` inserted a signing time attribute by default. This was removed, as it is not required ans might even be unwanted.

cms: Don't insert signing time attribute by default.

---

x509-cert/src/certificate.rs
x509-cert/tests/certificate.rs

Fixes #1149
This broke with the parsing profiles (#987)

x509-cert: fixup `Arbitrary` for certificates

---

cms/src/signed_data.rs

Fixup for `SignerIdentifier` encoding by @bkstein
ported from #1115

cms: Fixed encoding of `SubjectKeyIdentifier`

---

Cargo.lock
cms/CHANGELOG.md
cms/Cargo.toml

Added
- `SignedData` builder ([#1051])
Changed
- Deprecate `pkcs7` in favor of `cms` ([#1062])
- der: add `SetOf(Vec)::insert(_ordered)`; deprecate `add` ([#1067])
- Re-enable all minimal-versions checks ([#1071])
Fixed
- Don't insert signing time attribute by default ([#1148])
- Fixed encoding of `SubjectKeyIdentifier` ([#1152])
[#1051]: https://github.com/RustCrypto/formats/pull/1051
[#1062]: https://github.com/RustCrypto/formats/pull/1062
[#1067]: https://github.com/RustCrypto/formats/pull/1067
[#1071]: https://github.com/RustCrypto/formats/pull/1071
[#1148]: https://github.com/RustCrypto/formats/pull/1148
[#1152]: https://github.com/RustCrypto/formats/pull/1152

cms v0.2.2

---

Cargo.lock
sec1/CHANGELOG.md
sec1/Cargo.toml

- Impl `Hash` for `EncodedPoint` ([#1102])
[#1102]: https://github.com/RustCrypto/formats/pull/1102

sec1 v0.7.3

---

Cargo.lock
der/Cargo.toml
der/src/asn1/octet_string.rs

Adds (optional) support for using `bytes::Bytes` as an `OctetString`.

der: `bytes` feature

---

Cargo.lock
pkcs12/Cargo.toml

- Remove unused `cfg-if` dependency
- Whitespace fixups
- Move features before docs.rs metadata
- Remove category `data-structures` which is more for data structure algorithms than data format decoders/encoders

pkcs12: Cargo.toml cleanups

---

pem-rfc7468/src/error.rs
pkcs8/src/traits.rs

This should give better errors for invalid PEM type labels even if there are subsequent Base64 processing errors, which might occur if e.g. Base64 is wrapped at a nonstandard width.
Notably such errors will include the expected PEM type label.

pkcs8: eagerly decode PEM labels

---

der/src/asn1.rs
der/src/asn1/bmp_string.rs
der/src/bytes_owned.rs

Adds initial support for a Basic Multilingual Plane (a.k.a. UCS-2) string type.

der: add `BmpString`

---

der/src/asn1/bmp_string.rs

der: no-panic cleanup

---

Cargo.lock
x509-cert/CHANGELOG.md
x509-cert/Cargo.toml

Added
- `add_attribute` to `RequestBuilder` ([#1137])
Changed
- bump `serde_json` from 1.0.97 to 1.0.99 ([#1122])
- use the shortest name when looking attr OID ([#1130])
- bump `serde_json` from 1.0.100 to 1.0.103 ([#1158])
Fixed
- RDN string representation ([#1126])
- `Arbitrary` for certificates ([#1150])
[#1122]: https://github.com/RustCrypto/formats/pull/1122
[#1126]: https://github.com/RustCrypto/formats/pull/1126
[#1130]: https://github.com/RustCrypto/formats/pull/1130
[#1137]: https://github.com/RustCrypto/formats/pull/1137
[#1150]: https://github.com/RustCrypto/formats/pull/1150
[#1158]: https://github.com/RustCrypto/formats/pull/1158

x509-cert v0.2.4

---

.github/workflows/x509-tsp.yml
Cargo.lock
x509-tsp/Cargo.toml
x509-tsp/src/lib.rs

This enables CI on x509-tsp. It also fixes tests that broke with #1130
Fixes #1176

x509-tsp: enable CI

---

der/derive/src/lib.rs

Add the missing close-parenthesis.
Also change the number in the example, because 42 isn't a valid tag, and will result in a vague compile-time error if the reader pastes this example into their code.

der_derive: fix doc typo and use a valid tag number

---

Cargo.lock
der/derive/Cargo.toml
der/derive/src/attributes.rs
der/derive/src/choice.rs
der/derive/src/choice/variant.rs
der/derive/src/enumerated.rs
der/derive/src/lib.rs
der/derive/src/sequence.rs
der/derive/src/sequence/field.rs
der/derive/src/value_ord.rs

Closes #1173.
I chose to minimize the diff by introducing a minimal `abort!` macro that early-returns like `anyhow::bail!` or similar macros, which reduces the amount of code that has to change a lot.
Further refactorings are possible (in particular, I personally prefer to collect all attribute errors and emitting them individually where possible, instead of short-circuiting on the first error), but I didn't do any of that in this PR for the same reason. Let me know if you're interested in anything like that.

Remove proc-macro-error dependency

---

Cargo.lock
der/derive/CHANGELOG.md
der/derive/Cargo.toml

Changed
- fix doc typo and use a valid tag number ([#1184])
- remove proc-macro-error dependency ([#1180])
[#1180]: https://github.com/RustCrypto/formats/pull/1180
[#1184]: https://github.com/RustCrypto/formats/pull/1184

der_derive: v0.7.2

---

Cargo.lock
der/CHANGELOG.md
der/Cargo.toml

Added
- `bytes` feature ([#1156])
- impl `RefToOwned`/`OwnedToRef` for `&[u8]`/`Box<[u8]>` ([#1188])
- `BmpString` ([#1164])
Changed
- no-panic cleanup ([#1169])
- Bump `der_derive` dependency to v0.7.2 ([#1192])
[#1156]: https://github.com/RustCrypto/formats/pull/1156
[#1164]: https://github.com/RustCrypto/formats/pull/1164
[#1169]: https://github.com/RustCrypto/formats/pull/1169
[#1188]: https://github.com/RustCrypto/formats/pull/1188
[#1192]: https://github.com/RustCrypto/formats/pull/1192

der: 0.7.8

---

.github/workflows/workspace.yml
Cargo.lock
const-oid/CHANGELOG.md
const-oid/Cargo.toml
const-oid/oiddbgen/rfc8410.txt
const-oid/oiddbgen/src/main.rs
const-oid/src/db/gen.rs

backport rfc8410 OIDs into new release from const-oid/v0.9 branch following form from #1139

const-oid/v0.9.5 backporting rfc8410 OIDs

---

tls_codec/src/tls_vec.rs
tls_codec/tests/encode_bytes.rs

This PR implements the `SerializeBytes` trait for all the `TlsByteVecUX` types. It also adds tests for serializing them using the `SerializeBytes` trait.

Implement `SerializeBytes` for `TlsByteVecUX` types

---

tls_codec/derive/src/lib.rs

This PR makes generated constants strictly upper case. This is one way to avoid clippy warnings that occur, when deriving TlsSerialize and others. Another way would be to allow lower case constants selectively.
EDIT: I just realized that the solution in this PR doesn't work in edge cases, where an enum has, for example, an `Ok` and an `OK` variant. A better solution might be to just `allow` non-snake-case constants.

tls_codec: Make constants generated during trait derivation upper case

---

Cargo.lock
serdect/CHANGELOG.md
serdect/Cargo.toml
tls_codec/Cargo.toml
x509-cert/test-support/Cargo.toml

`serde v1.0.172` and later include pre-compiled binaries which is a security hazard. So until the decision gets reverted, I believe it's worth to pin upper version of `serde`. This approach may cause issues if a different crate in someone's dependency tree will depend on a post-1.0.172 version of `serde`, but I think this issue is small enough when compared to the security concerns. Also, a number of other crates in the ecosystem follow this approach, so we are not alone.
`tai64` depends on `serde`, but does not use the `derive` feature, so pinning is not needed there. `serdect` uses `derive` only for dev builds, but I've pinned the version just in case.
More information and discussion about the `serde` change can be found in https://github.com/serde-rs/serde/issues/2538.

Pin upper version of serde to <1.0.172

---

Cargo.lock
der/src/asn1/bmp_string.rs
pkcs12/Cargo.toml
pkcs12/src/kdf.rs
pkcs12/tests/kdf.rs

Uses the `BmpString` type to implement transcoding from UTF-8 to BMP/UCS-2.
This type notably restricts the use of UTF-16 surrogate pairs, something the previous implementation was not doing correctly. This entailed making the methods which transcode UTF-8 fallible, since we need to handle the error case that they encode characters outside BMP/UCS-2.
cc @xemwebe

pkcs12: use `der::BmpString` for KDF

---

Cargo.lock
serdect/Cargo.toml
tls_codec/Cargo.toml

Updates the following dependencies:
Updating crates.io index
Updating aho-corasick v1.0.4 -> v1.0.5
Updating anstyle v1.0.1 -> v1.0.3
Updating base64 v0.21.2 -> v0.21.4
Updating bytes v1.4.0 -> v1.5.0
Updating clap v4.3.23 -> v4.4.2
Updating clap_builder v4.3.23 -> v4.4.2
Updating clap_lex v0.5.0 -> v0.5.1
Updating crypto-bigint v0.5.2 -> v0.5.3
Updating errno v0.3.2 -> v0.3.3
Updating flagset v0.4.3 -> v0.4.4
Updating linux-raw-sys v0.4.5 -> v0.4.7
Updating memchr v2.5.0 -> v2.6.3
Updating pin-project-lite v0.2.12 -> v0.2.13
Updating regex v1.9.3 -> v1.9.5
Updating regex-automata v0.3.6 -> v0.3.8
Updating regex-syntax v0.7.4 -> v0.7.5
Updating rustix v0.38.8 -> v0.38.13
Updating serde v1.0.185 -> v1.0.188
Updating serde_derive v1.0.185 -> v1.0.188
Updating serde_json v1.0.105 -> v1.0.106 …

Cargo.lock: update dependencies

---

crmf/src/request.rs

Add comment with language from X.680 to describe why two fields are decorated as EXPLICIT despite fact that module is IMPLICIT.

add comment to address #1206

---

Cargo.lock
serdect/Cargo.toml

PR #1112 contained breaking changes. To reflect that, this bumps the `serdect` version to a prerelease.
Note that there is not a crate release associated with this bump. If there is a prerelease, it will be `v0.3.0-pre.0`.

serdect: bump version to v0.3.0-pre

---

.github/workflows/serdect.yml
Cargo.lock
serdect/Cargo.toml
serdect/README.md

serdect: bump `toml` to v0.8

---

tls_codec/CHANGELOG.md
tls_codec/benches/quic_vec.rs
tls_codec/benches/tls_vec.rs
tls_codec/derive/src/lib.rs
tls_codec/derive/tests/decode.rs
tls_codec/derive/tests/decode_bytes.rs
tls_codec/src/arrays.rs
tls_codec/src/lib.rs
tls_codec/src/primitives.rs
tls_codec/src/quic_vec.rs
tls_codec/src/tls_vec.rs
tls_codec/tests/decode.rs
tls_codec/tests/decode_bytes.rs

This is a breaking change renaming the functions in the `DeserializeBytes` trait to avoid collisions with the functions in the `Deserialize` trait. The functions are renamed by appending a `_bytes` suffix.

tls_codec: Rename functions in DeserializeBytes trait

---

const-oid/oiddbgen/Cargo.lock
const-oid/oiddbgen/rfc8894.md
const-oid/src/db/gen.rs

As `id-pkix` was not explicitely noted in rfc8894.md, it was missing in the generated `gen.rs`. This PR fixes that.
Note: I recognized, that Cargo.lock was also changed, though I didn't make any changes, that could have caused that. Is this is intended?

const-oid: Added SCEP's failInfoText oid.

---

spki/src/spki.rs

This adds a `SubjectPublicKeyInfoOwned::from_key` helper that will accept any public key (an object implementing `EncodePublicKey`).

spki: adds a public key to SubjectPublicKeyInfoOwned helper

---

.cargo/audit.toml

It's not actionable until a new release of the `rsa` crate is available

.cargo/audit.toml: ignore RUSTSEC-2023-0071

---

Cargo.lock
x509-cert/CHANGELOG.md
x509-cert/Cargo.toml

- Signed Certificate Timestamp (SCT) extension support ([#1134])
- Relax dependencies ([#1179])
- Use `SubjectPublicKeyInfoOwned::from_key` ([#1271])
[#1134]: https://github.com/RustCrypto/formats/pull/1134
[#1179]: https://github.com/RustCrypto/formats/pull/1179
[#1271]: https://github.com/RustCrypto/formats/pull/1271

x509-cert v0.2.5

---

.github/workflows/der.yml
.github/workflows/pkcs1.yml
.github/workflows/pkcs5.yml
.github/workflows/pkcs8.yml
.github/workflows/sec1.yml
.github/workflows/spki.yml
Cargo.lock
der/Cargo.toml
der/derive/Cargo.toml
pem-rfc7468/Cargo.toml
pkcs1/Cargo.toml
pkcs5/Cargo.toml
pkcs8/Cargo.toml
sec1/Cargo.toml
sec1/README.md
spki/Cargo.toml

This bumps the following crates to prerelease versions (not intended for release, just to signal we're making breaking changes):
- `der`(_derive) v0.8.0-pre
- `pem-rfc7468` v1.0.0-pre
- `pkcs1` v0.8.0-pre
- `pkcs5` v0.8.0-pre
- `pkcs8` v0.11.0-pre
- `sec1` v0.8.0-pre
- `spki` v0.8.0-pre
This notably doesn't bump `x509-cert` or any crates which are dependent upon it due to a circular dependency problem: the certificate builder tests rely on updated public key crypto crates like `rsa`, so we'll need to do this update in two phases: this initial set of format-only crates, and then updating the cryptographic dependencies.
`pem-rfc7468` has been bumped to v1.0.0-pre based on the observation that there have been no significant changes since the last release, and that the baseline set of …

Bump versions to prereleases for next release cycle

---

spki/src/spki.rs

`SubjectPublicKeyInfoOwned` does not require the ownership of the key.
This is a breaking change.

spki: borrow the public key in `spki::from_key`

---

Cargo.lock
sec1/Cargo.toml
sec1/src/lib.rs
sec1/src/point.rs

The RustCrypto/traits crates are now using `hybrid-array`, which features a mostly safe implementation that natively leverages const generics as much as possible.

sec1: migrate from `generic-array` to `hybrid-array`

---

const-oid/src/lib.rs

Previously the v0.10-pre release series has attempted to make `ObjectIdentifier` generic around a backing buffer containing the BER encoding and bounded on `AsRef<[u8]>`.
This approach has a drawback though: we can't use derived `PartialEq`/`Eq`, which means it isn't possible to use in `match` expressions anymore, an ergonomics drawback noted in #1293, with the implementation reverted in #1299.
An alternative way to go for what it was trying to implement: an `ObjectIdentifierRef` backed by a `&[u8]` is to use a separate struct. With that approach, there could be overlapping `PartialEq`/`Eq` impls that would allow the two to be compared.
As a start towards going that route, this gets rid of the generic backing buffer and opts instead to make the struct const generic around its size with a …

const-oid: make `ObjectIdentifier`'s size const generic

---

const-oid/src/lib.rs
const-oid/src/traits.rs

Adds a `traits` module containing `AssociatedOid` and `DynAssociatedOid`

const-oid: factor traits into module

---

Cargo.lock
cmpv2/Cargo.toml
cms/Cargo.toml
der/Cargo.toml
pkcs1/Cargo.toml
pkcs12/Cargo.toml

...as sourced from this repo, as it has diverged from the crate release.
This is possible now that #1299 has landed.

der: bump `const-oid` to v0.10.0-pre.1

---

.github/workflows/const-oid.yml
.github/workflows/der.yml
.github/workflows/pkcs1.yml
.github/workflows/pkcs5.yml
.github/workflows/pkcs8.yml
.github/workflows/sec1.yml
.github/workflows/spki.yml
const-oid/Cargo.toml
const-oid/README.md
const-oid/src/buffer.rs
const-oid/src/encoder.rs
const-oid/src/lib.rs
const-oid/src/parser.rs
der/Cargo.toml
der/README.md
pkcs1/Cargo.toml
pkcs1/README.md
pkcs5/Cargo.toml
pkcs5/README.md
pkcs8/Cargo.toml
pkcs8/README.md
sec1/Cargo.toml
sec1/README.md
spki/README.md

Also bumps MSRV to 1.71 due to the const use of `[u8]::split_at`.
Additionally makes the internal `Encoder` type const generic around the size of the output buffer.

const-oid: make `ObjectIdentifier::as_bytes` a `const fn`

---

const-oid/src/encoder.rs

The `Encoder` previously returned `Error::Length` even when there was one remaining byte in the buffer.
This fixes that error and adds an edge case test.

const-oid: fix `Encoder` size check and off-by-one error

---

const-oid/src/arcs.rs
const-oid/src/db.rs
const-oid/src/encoder.rs
const-oid/src/error.rs
const-oid/src/lib.rs
const-oid/tests/oid.rs
const-oid/tests/oid_ref.rs

Adds a `repr(transparent)` newtype for a `[u8]` which is guaranteed to contain a valid BER serialization of an OID. This is a similar approach to how `Path`/`PathBuf` or `OsStr`/`OsString` work (except with `ObjectIdentifier` being stack-allocated instead of heap allocated).
An unsafe pointer cast is required to go from `&[u8]` to `&ObjectIdentifierRef`, so unfortunately this means the crate is no longer `forbid(unsafe_code)`, however it's been lowered to `deny(unsafe_code)` to ensure contributors think twice before adding more.
`Borrow` and `Deref` impls have been added to the owned `ObjectIdentifier` type, allowing common functionality to be moved to `ObjectIdentifierRef`, allowing both types to exist while eliminating code duplication.
A `PartialEq` impl allows them to be compared.
The …

const-oid: add `ObjectIdentifierRef`

---

x509-cert/src/serial_number.rs

This follows the CABF ballot 164 recommendation to have serials use 64 bits from a CSPRNG.
https://cabforum.org/2016/03/31/ballot-164/
This also provides the user with the option to prefix its values (for use of an instance id).

x509-cert: adds a serial numbers generator

---

pkcs12/src/kdf.rs

Quotes RFC 7292 Appendix B on why the PKCS#12 KDF is a poor choice which is deprecated for new usage

pkcs12: add KDF security warning

---

Cargo.lock
cms/CHANGELOG.md
cms/Cargo.toml

- RFC 5544 `TimeStampedData` implementation ([#1258])
[#1258]: https://github.com/RustCrypto/formats/pull/1258

cms v0.2.3

---

der/src/encoding_rules.rs
der/src/lib.rs
der/src/reader.rs
der/src/reader/nested.rs
der/src/reader/pem.rs
der/src/reader/slice.rs

Adds an enum with `Ber` and `Der` (default) variants which can be used to selectively allow a limited number of BER productions when decoding certain BER-based security-oriented formats, e.g. CMS, PKCS#8.
Currently this doesn't actually do anything, however the goal is to address #779, where we can't decode CMS generated by Apple tooling.
PR #810 is an example of how the rules could be relaxed to support `IndefiniteLength`s.

der: add `EncodingRules` enum

---

Cargo.lock
sec1/Cargo.toml
sec1/src/point.rs

Also cuts a `sec1` v0.8.0-pre.1 release

sec1: bump `hybrid-array` to v0.2.0-rc.0

---

x509-cert/tests/builder.rs

With the upgrade of zlint to 3.6.0 came new lints. One of them is enforcement of one of the measure from SC-62 removing commonName from the Subject.

x509-cert: ignore commonName warning

---

x509-cert/src/ext/pkix.rs

This PR fixes https://github.com/RustCrypto/formats/issues/1210
Though this does appear to be a bug, it's also a breaking change to incorporate the fix.
It can be merged as part of the next development cycle when we're making breaking changes.

fix(#1210): fix impl of SubjectDirectoryAttributes

---

cms/src/builder.rs
cms/tests/builder.rs
x509-cert/src/builder.rs
x509-cert/tests/builder.rs

This is mostly a draft after discussion in #1160
cc @bkstein @tarcieri @jstayton

x509-cert: don't bind builder with signer early

---

Cargo.lock
x509-cert/Cargo.toml
x509-cert/src/builder.rs
x509-cert/tests/builder.rs

This depends on:
- https://github.com/RustCrypto/formats/pull/1161
- https://github.com/RustCrypto/traits/pull/1428

x509-cert: introduce a `builder::AsyncBuilder` trait

---

cms/src/enveloped_data.rs

The type `RecipientKeyIdentifier` is a SEQUENCE, so it should use constructed encoding in the enum variant `KeyAgreeRecipientIdentifier::RKeyId(RecipientKeyIdentifier)`
I discovered this because of the error in this code snippet.
```Rust
use cms::{
cert::x509::ext::pkix::SubjectKeyIdentifier,
enveloped_data::{KeyAgreeRecipientIdentifier, RecipientKeyIdentifier},
};
use der::{asn1::OctetString, Decode, Encode};
fn main() {
let kari = KeyAgreeRecipientIdentifier::RKeyId(RecipientKeyIdentifier {
subject_key_identifier: SubjectKeyIdentifier(OctetString::new([0]).unwrap()),
date: None,
other: None,
});
let encoded = kari.to_der().unwrap();
let decoded = KeyAgreeRecipientIdentifier::from_der(&encoded).unwrap();
// Error { kind: Noncanonical { tag: Tag(0x80: CONTEXT-SPECIFIC [0] (primitive)) }, …
```

Change RKeyId enum variant to use constructed encoding

---

tls_codec/src/quic_vec.rs

`Read::read` is not guaranteed to fill the whole buffer, and similarly, `Write::write` is not guaranteed to write everything. This commit replaces them with `read_exact` and `write_all` respectively, and removes the corresponding assertions.

tls_codec: Read/write all available data in quic_vec

---

tls_codec/src/lib.rs

Just noticed that I forgot to add documentation for the `DeserializeBytes` trait.

tls_codec: Add missing docs

---

tls_codec/derive/src/lib.rs
tls_codec/derive/tests/decode.rs

This PR introduces the `#[tls_codec(cd_field)]` macro. It can be used alongside the `#[conditionally_deserializable]` macro to mark fields that are also conditionally deserializable and that internally need to have the const generic added.

tls_codec: Introduce helper macro for conditional deserialization

---

Cargo.lock
tls_codec/Cargo.toml
tls_codec/src/lib.rs
tls_codec/src/quic_vec.rs

Expose functions to read and write variable-length encodings for quic vectors.
This can be useful when manual parsing of variable-length structs is required.
There are no code changes in here. This only makes two existing functions public.

tls_codec: expose vlen functions

---

Cargo.lock
Cargo.toml
cms/Cargo.toml
pkcs12/Cargo.toml
x509-cert/Cargo.toml
x509-ocsp/Cargo.toml

async-signature 0.6.0-pre.1
digest 0.11.0-pre.8
ecdsa 0.17.0-pre.5
rsa 0.10.0-pre.1
sha1 0.11.0-pre.3
sha2 0.11.0-pre.3
sha3 0.11.0-pre.3
signature 2.3.0-pre.3
Requires:

async-signature+digest+ecdsa+rsa+sha+signature: bump pre-release version

---

x509-cert/src/serial_number.rs

x509-cert: typo in documentation

---

der/src/error.rs
pkcs1/src/error.rs
pkcs5/Cargo.toml
pkcs5/src/error.rs
pkcs5/src/lib.rs
pkcs8/Cargo.toml
pkcs8/src/error.rs
pkcs8/tests/encrypted_private_key.rs
sec1/src/error.rs
spki/src/error.rs

When the `std` feature is enabled, adds support for propagating an arbitrary error source which can be set using `Error::set_source`.
The main use case is passing back an arbitrary error value in the `ErrorKind::Value` use case, to handle passing back what specifically was wrong with a given value in a DER-encoded document.
This entails removing the `Clone` + `Copy` bounds since the error is stored in a `Box`, which can't be `Copy` and can't reflect a `Clone` bound. Fortunately, nothing in this repo ever seems to clone an `Error` so it's not really an issue.
Also adds `Error::source` impls to the downstream error types in `pkcs1`, `pkcs5`, `pkcs8`, `sec1`, and `spki`.

der: add `Error::(set_)source`; remove `Clone` + `Copy`

---

cms/src/authenveloped_data.rs
cms/src/lib.rs

Saw the issue #1171  regarding this missing CMS data type, most of the types were already implemented so it should be safe to include.

RFC5083 - AuthEnvelopedData

---

tls_codec/README.md

The links in the table were broken. I removed them.

tls_codec: Fix readme links

---

Cargo.lock
Cargo.toml

After https://github.com/RustCrypto/signatures/pull/809 merged, the branch has been removed, and this now breaks the CI.
Switch to master instead.

Fix CI // missing git branch

---

.github/workflows/x509-cert.yml
x509-cert/Cargo.toml

Allows creation of spki fingerprints without having to add the `spki` crate separately and keep versions in sync.

Forward feature flags to the spki crate

---

der/src/error.rs
pkcs1/src/error.rs
pkcs5/Cargo.toml
pkcs5/src/error.rs
pkcs5/src/lib.rs
pkcs8/Cargo.toml
pkcs8/src/error.rs
pkcs8/tests/encrypted_private_key.rs
sec1/src/error.rs
spki/src/error.rs

This reverts commit 7784f2dfda3a870f191f88c27159960a8ffacbe7.
This ended up complicating downstream error types, particularly in `no_std` contexts.
It's also not really necessary now that #1055 has landed.
cc @baloo

Revert "der: add `Error::(set_)source`; remove `Clone` + `Copy` (#1328)"

---

der/src/writer/slice.rs

`?` currently influences inference s.t. for `error()?` rustc infers `T = ()`. However, it is quite confusing -- `?` is not supposed to influence inference, it's just a conicidence because of the curent implementation. There is an idea to change this behavior in future Rust versions, such that this code won't compile without this change.
See https://github.com/rust-lang/rust/pull/122412 for more information about the change.
(`der` is used by cargo, so this partially blocks the PR, please ping me once you release a new `der` version so I can update it inside cargo)

Make sure `der` crate is compatible with potential language breaking changes

---

.cargo/audit.toml
Cargo.lock
der/CHANGELOG.md
der/Cargo.toml

Changed
- ignore RUSTSEC-2023-0071 (backport #1276)
- make sure der is comptatible with potential language breaking changed (backport of #1374)

der v0.7.9

---

spki/src/algorithm.rs

As noted in RustCrypto/RSA#422, we're not returning the actual "unknown OID" encountered in these cases, but the expected one, which makes it hard to debug mismatches.

spki: fix `OidUnknown` reporting

---

base64ct/src/decoder.rs

This is a curious corner case that can happen when, for example, you're reading the length-value encoded strings in OpenSSH. If the last string in the data is of zero-length, then decode() will be called with an empty buffer, so we don't need to read any bytes. However, since `is_finished()` was checked unconditionally, the zero-length read (which would be OK) was instead rejected because there was no data to (not) read.
The bug was particularly mischievous because `is_finished()` will return false if there's `=` padding, so 2/3 of empty read calls will work normally.

Don't fail with InvalidLength when reading nothing at end of data

---

der/src/decode.rs
der/src/reader/slice.rs

Support for decoding an input byte slice while specifying what encoding rules should be used with the given reader.

der: add `Decode::from_ber`

---

pkcs12/src/lib.rs
pkcs12/src/safe_bag.rs
pkcs12/tests/cert_tests.rs
x509-cert/src/request.rs

Several modules contain a single type. This removes those modules from the public API and re-exports such types at the toplevel.

pkcs12: flatten API

---

.github/workflows/pkcs1.yml
.github/workflows/pkcs5.yml
.github/workflows/pkcs8.yml
.github/workflows/sec1.yml
.github/workflows/spki.yml
Cargo.lock
Cargo.toml
cms/Cargo.toml
cms/src/builder.rs
cms/tests/builder.rs
pkcs1/Cargo.toml
pkcs5/Cargo.toml
pkcs5/src/pbes2/encryption.rs
pkcs8/Cargo.toml
sec1/Cargo.toml
spki/Cargo.toml

This makes pkcs5, cms, and spki to use pre-releases versions of:
- aes 0.9.0-pre
- cbc 0.2.0-pre
- cipher 0.5.0-pre.4
- des 0.9.0-pre.0
- pbkdf2 0.13.0-pre.0
- scrypt 0.12.0-pre.0
- sha1 0.11.0-pre.3
- sha2 0.11.0-pre.3

pkcs5: cms: spki: bump dependencies to pre-releases

---

base16ct/src/error.rs
base16ct/src/upper.rs
cms/src/builder.rs
pkcs1/src/error.rs
pkcs1/src/traits.rs
pkcs5/src/pbes1.rs
pkcs5/src/pbes2.rs
sec1/src/private_key.rs

rustc 1.78 just released and it brings new warnings.
This fixes all `unnecessary qualification` warnings

rust 1.78 fixups

---

der/derive/src/lib.rs

`der_derive` documentation doesn't mention `#[asn1(tag_mode = "...")]` attribute in _Field-level attributes_ section.

doc(der_derive): Add documentation for field-level tag_mode attribute.

---

x509-cert/src/builder.rs
x509-cert/src/builder/profile.rs
x509-cert/src/builder/profile/cabf.rs
x509-cert/src/builder/profile/cabf/tls.rs
x509-cert/src/builder/profile/devid.rs
x509-cert/src/ext/pkix/name.rs
x509-cert/src/ext/pkix/name/hardware.rs
x509-cert/tests/builder.rs

I tried to abide by the ETSI policy.
https://www.etsi.org/deliver/etsi_en/319400_319499/31941202/02.03.01_60/en_31941202v020301p.pdf
The policy recommends to make KeyUsage bits 0, 1, (2 and/or 4) exclusive. This is meant to avoid making signing of commitments during authentication.
This commit goes a bit further by making bit 2 and 4 exclusive. I don't find a use-case for requiring both at the same time (and I would think only key agreement is required.
Fixes #1281
Fixes #1392

x509-cert: rework certificate builder profiles

---

base32ct/src/alphabet/rfc4648.rs
base32ct/src/lib.rs
base32ct/tests/vectors.rs

This is a pretty straightforward addition, without any breaking change.
I added a couple of tests, almost copy-pasting the code already available.
Closes #1405

Add support for Base32 upper unpadded alphabet

---

x509-cert/src/certificate.rs
x509-ocsp/src/builder/request.rs
x509-ocsp/src/cert_id.rs
x509-ocsp/src/request.rs
x509-ocsp/tests/ocsp.rs

This allows an x509 validator to check for ocsp signature of RFC5280-invalid certificates.

x509-ocsp: add support for parsing profiles

---

der/src/reader.rs
der/src/reader/nested.rs
der/src/reader/pem.rs
der/src/reader/slice.rs

Right now `PemReader` uses interior mutability via `RefCell`, because peeking might involve filling an internal peek buffer (i.e. decoding the Base64 in a PEM document).
Rather than trying to hide the fact we're potentially modifying internal buffers (but not the cursor/position) when peeking, this changes the methods to explicitly accept `&mut self`, and with that change eliminates all usages of `RefCell`.
This change appears to have no practical drawbacks, since peeking always occurs during the decoding process where we need mutable access to the reader anyway.

der: have `Reader::peek*` methods take `&mut self`

---

Cargo.lock
base32ct/CHANGELOG.md
base32ct/Cargo.toml

- Support for Base32 upper unpadded alphabet ([#1406])
- Broken encoding of unpadded base32 ([#1421])
[#1406]: https://github.com/RustCrypto/formats/pull/1406
[#1421]: https://github.com/RustCrypto/formats/pull/1421

base32ct v0.2.1

---

.github/workflows/base64ct.yml
Cargo.lock
base32ct/Cargo.toml
base32ct/README.md
base64ct/Cargo.toml
base64ct/README.md

This seems like the lowest maintenance way to do this.
An alternative would be to check MSRV only on build, which would allow us to run tests with a higher rustc version, but that wouldn't actually verify tests pass under MSRV.

base32ct+base64ct: unpin `proptest`; MSRV 1.65

---

base32ct/src/encoding.rs
base32ct/src/lib.rs

This can be handy to avoid an heap allocation, because it is possible to use the result of the const fn to allocate an array of the right size.
EDIT: I changed a bit the initial proposal in order to make it actually easier to use in const context. Previously `encoded_len` took a slice (like in the trait), now it takes an `usize` representing the number of bytes to encode.

base32ct: add const encoded_len fn

---

der/src/asn1/any.rs
der/src/bytes_owned.rs
der/src/bytes_ref.rs
der/src/length.rs
der/src/tag.rs
der/src/tag/number.rs
spki/src/algorithm.rs
spki/tests/spki.rs

This allows to build an hashmap with various hashing algorithm when verifying objects.

spki: implement `Hash` for `AlgorithmIdentifier`

---

x509-cert/src/attr.rs

I'm also wondering if it's worth documenting that the `Name::from_str` functionality is not guaranteed to generate a valid X.501 Name as per RFC 5280, and that manual construction of a Name from OIDs and ASN.1 is the preferred method?

Correctly format email addresses.

---

cms/src/builder.rs
pkcs5/src/error.rs

I am using the `cms` crate to calculate a PKCS#7 signature. There, I have noticed that many RustCrypto crates support the conversion of errors into `anyhow::Error` but the `cms` crate does not provide it.
I looked through all crates in this repository and found `pkcs5`, too.
Here is my small demo program which I have used to test the PR:
```rust
use anyhow::Context;
use cms::builder::SignedDataBuilder;
use cms::signed_data::EncapsulatedContentInfo;
use der::asn1::PrintableStringRef;
use spki::AlgorithmIdentifierOwned;
fn main() -> anyhow::Result<()> {
// runtime error: '@' is not allowed in ASN.1 PrintableString
let content = "abc@example.com".to_owned();
let content = PrintableStringRef::new(&content).context("cannot create PrintableStringRef")?;
let content = EncapsulatedContentInfo { …
```

implement `std::error::Error` for `cms` and `pkcs5` crates

---

x509-tsp/src/lib.rs

`x509-tsp` makes use of structures defines in `cmpv2`:
- `cmpv2::status::PkiStatusInfo` which itself refers: - `cmpv2::status::PkiStatus` and - `cmpv2::status::PkiFailureInfo`
Reexporting it makes it more convenient for a consumer.

x509-tsp: re-export cmpv2

---

pkcs8/Cargo.toml
pkcs8/src/encrypted_private_key_info.rs
pkcs8/src/private_key_info.rs
pkcs8/src/traits.rs

When encrypting private keys, uses the recommended set of parameters from the `pbes2` crate.
This uses scrypt with parameters explicitly selected to be compatible with OpenSSL so it's capable of decrypting keys encrypted using the `pkcs8` crate.
Closes #429

pkcs8: use `pbes2::Parameters::recommended`

---

der/src/ord.rs

```
warning: bound is defined in more than one place
--> der/src/ord.rs:56:31
|
56 | pub(crate) fn iter_cmp<'a, I, T: 'a>(a: I, b: I) -> Result<Ordering>
|                               ^
...
59 |     T: DerOrd,
|     ^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#multiple_bound_locations
= note: `#[warn(clippy::multiple_bound_locations)]` on by default
```

der: fixup multiple-bounds-declaration warning

---

x509-cert/src/ext.rs
x509-cert/src/ext/pkix/constraints/basic.rs
x509-cert/src/ext/pkix/constraints/name.rs
x509-cert/src/ext/pkix/crl/dp.rs

rustc fails to infer the appropriate types with `Default::default` when building a crate depending on
```
femme = "2.2.1"
getrandom = { version = "0.2.15", features = ["js"] }
rand = "0.8.5
x509-cert = { version = "0.2.5", features = ["hazmat", "builder"] }
```
This is the primary reason we at [Wire](https://github.com/wireapp) have a fork of `formats` so it'd be nice if we could go back to tracking upstream.

x509-cert: specify concrete types to help the compiler

---

der/derive/src/sequence/field.rs
der/tests/derive.rs
x509-cert/src/ext.rs
x509-cert/src/ext/pkix/constraints/basic.rs
x509-cert/src/ext/pkix/constraints/name.rs
x509-cert/src/ext/pkix/crl/dp.rs

This is another take on #1441. This is intended to make sure we can still continue to use `Default::default` and not break future releases by mistake.

der-derive: avoid type inference when using default

---

.github/workflows/x509-cert.yml
Cargo.lock
base16ct/src/error.rs
base16ct/src/upper.rs
der/derive/CHANGELOG.md
der/derive/Cargo.toml
der/derive/src/sequence/field.rs
der/tests/derive.rs
pkcs1/src/error.rs
pkcs1/src/traits.rs
pkcs5/src/pbes1.rs
pkcs5/src/pbes2.rs
sec1/src/private_key.rs
x509-cert/src/request.rs
x509-cert/tests/builder.rs

- avoid type inference when using default ([#1443])
[#1443]: https://github.com/RustCrypto/formats/pull/1443

der-derive: v0.7.3

---

der/src/encode.rs
der/src/tag.rs

This fixes the `Tagged` and `Encode` trait impls on `str`, for example.
Closes #1365

der: allow all blanket impls on `?Sized` types

---

const-oid/src/arcs.rs
der/src/asn1/bit_string.rs
der/src/asn1/integer.rs
der/src/lib.rs
pkcs5/Cargo.toml
pkcs5/src/lib.rs
pkcs5/src/pbes2/kdf.rs
tls_codec/Cargo.toml

- `size_of` and `size_of_val` have been moved to the prelude, so import them directly as `core::mem::{size_of, size_of_val}` rather than importing `core::mem`.
- Removes dead code gated on removed features
- `pkcs5`: add missing `std` feature
- `tls_codec`: allow `cfg(fuzzing)`

Rust 1.80 fixes

---

Cargo.lock
const-oid/Cargo.toml
x509-cert/src/builder/profile/devid.rs

This release is a soft API freeze, and we can start relaxing requirements not to use `=`
cc @baloo

const-oid v0.10.0-rc.0

---

Cargo.lock
cms/Cargo.toml
der/Cargo.toml
pem-rfc7468/Cargo.toml

Due to circular dependencies with https://github.com/rustcrypto/traits it seems I'm going to have to break the build to get this published

pem-rfc7468 v1.0.0-rc.0

---

Cargo.lock
Cargo.toml
cmpv2/Cargo.toml
cms/Cargo.toml
crmf/Cargo.toml
gss-api/Cargo.toml
pkcs1/Cargo.toml
pkcs12/Cargo.toml
pkcs5/Cargo.toml
pkcs8/Cargo.toml
sec1/Cargo.toml
spki/Cargo.toml
x509-cert/Cargo.toml
x509-ocsp/Cargo.toml
x509-tsp/Cargo.toml

As well as `sec1` and `spki`:
- `pkcs1` v0.8.0-rc.0
- `pkcs5` v0.8.0-rc.0
- `pkcs8` v0.11.0-rc.0
- `sec1` v0.8.0-rc.0
- `spki` v0.8.0-rc.0

Cut `pkcs*` crate prereleases

---

Cargo.lock
Cargo.toml
cms/Cargo.toml
pkcs12/Cargo.toml
pkcs5/Cargo.toml
spki/Cargo.toml
x509-cert/Cargo.toml
x509-ocsp/Cargo.toml

Updates the following dependencies to their latest prerelease versions:
- `aes-gcm` v0.11.0-pre.1
- `async-signature` v0.6.0-pre.4
- `cbc` v0.2.0-pre.1
- `des` v0.9.0-pre.1
- `digest` v0.11.0-pre.9
- `ecdsa` v0.17.0-pre.7
- `pbkdf2` v0.13.0-pre.1
- `scrypt` v0.12.0-pre.1
- `sha1` v0.11.0-pre.4
- `sha2` v0.11.0-pre.4
- `sha3` v0.11.0-pre.4
- `signature` 2.3.0-pre.4
- `whirlpool` v0.11.0-pre.4

Use latest prereleases

---

.github/workflows/x509-cert.yml

Excludes several features from `cargo hack` to prevent a combinatorial explosion, namely features which just activate other features in dependencies:
- `arbitrary`
- `base64`
- `fingerprint`
- `hazmat`
- `sct`
The `arbitrary`, `hazmat`, and `sct` features are tested in isolation, and finally the crate is tested with `--all-features` in both debug and release modes.
This should significantly improve CI times.

x509-cert: simplify CI (fewer cargo-hack combos)

---

der/src/reader.rs
der/src/reader/nested.rs
der/src/reader/pem.rs
der/src/reader/slice.rs

Removes the internal buffer added in #839 in favor of just cloning the `PemReader`'s state.
This is a partial step towards #1475 and would greatly simplify the implementation of #1474.
This also eliminates the need for mutable access in `Reader::peek`, making it possible to revert #1418 as well.

der: `PemReader` simplifications

---

der/src/header.rs
der/src/length.rs
der/src/reader.rs
der/src/reader/pem.rs
der/src/reader/slice.rs

Adds a method for peeking from a reader into a provided buffer.
This method is used to provide implementations of `Reader::peek_byte` and `Reader::peek_header`.
Closes #1279

der: add `Reader::peek_into`

---

crmf/src/pop.rs
der/src/reader.rs
der/src/reader/slice.rs
der/src/tag.rs
der_derive/src/choice.rs

Removes the provided `Reader::peek_tag` method, factoring it onto the `Tag` type itself.

der: refactor `Tag::peek`

---

der/src/document.rs
der/src/header.rs
der/src/reader.rs
der/src/reader/slice.rs

Like #1479 did for `Tag::peek`, this refactors `Reader::peek_header` into `Header::peek`.

der: refactor `Header::peek`

---

der/src/asn1/set_of.rs

der: don't validate `SetOf` ordering after sorting

---

der/src/lib.rs
der/src/referenced.rs
spki/src/spki.rs

see https://github.com/RustCrypto/formats/issues/1488

der: document `RefToOwned` and `OwnedToRef`

---

Cargo.lock
Cargo.toml

Sources these crates from the `master` branch of their respective repos

ecdsa,elliptic-curve,rsa: use `master` branch

---

.github/workflows/tls_codec.yml
Cargo.lock
tls_codec/Cargo.toml
tls_codec/README.md

Bumps the following dependencies:
$ cargo update
Updating git repository `https://github.com/RustCrypto/signatures`
Updating git repository `https://github.com/RustCrypto/traits`
Updating git repository `https://github.com/RustCrypto/RSA`
Updating crates.io index
Locking 88 packages to latest compatible versions
Updating addr2line v0.21.0 -> v0.22.0 (latest: v0.24.1)
Updating aho-corasick v1.1.2 -> v1.1.3
Updating anstyle-query v1.0.0 -> v1.1.1
Updating autocfg v1.1.0 -> v1.3.0
Updating backtrace v0.3.69 -> v0.3.73
Removing basic-toml v0.1.7
Removing bitflags v1.3.2
Removing bitflags v2.4.1
Adding bitflags v2.6.0
Updating block-buffer v0.11.0-rc.0 -> v0.11.0-rc.1
Updating cc v1.0.83 -> v1.1.16
Updating ciborium v0.2.1 -> v0.2.2
Updating ciborium-io v0.2.1 -> v0.2.2
Updating ciborium-ll …

Cargo.lock: bump dependencies

---

x509-cert/src/certificate.rs
x509-cert/src/time.rs
x509-cert/tests/validity.rs

When serializing certificates, the validity should be encoded as UTCTime if the year is strictly below 2050, as per [RFC 5280 section 4.1.2.5]:
```
CAs conforming to this profile MUST always encode certificate
validity dates through the year 2049 as UTCTime; certificate validity
dates in 2050 or later MUST be encoded as GeneralizedTime.
Conforming applications MUST be able to process validity dates that
are encoded in either UTCTime or GeneralizedTime.
```
Parsing is left untouched, no enforcement is made there.
Fixes #1496
[RFC 5280 section 4.1.2.5]: https://www.rfc-editor.org/rfc/rfc5280#section-4.1.2.5

x509-cert: time encoding, comply with rfc

---

Cargo.lock
pkcs1/Cargo.toml
pkcs12/Cargo.toml
pkcs8/Cargo.toml
sec1/Cargo.toml

- pkcs1 `0.8.0-rc.1`
- pkcs8 `0.11.0-rc.1`
- sec1 `0.8.0-rc.1`
This comes after the merge of API breaks on pkcs8 ([#1483])
[#1483]: https://github.com/RustCrypto/formats/pull/1483

cut pkcs1 pkcs8 and sec1 pre-releases

---

x509-cert/src/anchor.rs
x509-cert/src/certificate.rs
x509-cert/src/crl.rs
x509-cert/src/time.rs

Avoids repeating the `Profile + 'static` bound by moving the requirement to the bounds of the `Profile` trait itself.

x509-cert: move `'static` bounds to `Profile` trait

---

Cargo.lock
Cargo.toml

Depends:
- https://github.com/RustCrypto/elliptic-curves/pull/1075

fix pkcs8 breaks in dependencies

---

x509-cert/src/certificate.rs
x509-cert/src/ext.rs

As noted in #1491, the naming of the helpers to get or filter extensions was confusing.
This also documents the methods and provide examples.
Fixes #1491.

x509-cert: rename helpers to `get_extension`/`filter_extensions`

---

cmpv2/tests/cert_req.rs
cmpv2/tests/init_req.rs
cmpv2/tests/p10cr_req.rs
cms/tests/builder.rs
cms/tests/enveloped_data.rs
x509-cert/src/certificate.rs
x509-cert/tests/certificate.rs
x509-cert/tests/pkix_extensions.rs
x509-ocsp/src/builder/response.rs
x509-ocsp/src/cert_id.rs

This allows them to maintain invariants.
Adds read-only accessor methods in place of public fields.
Closes #1486.

x509-cert: make (Tbs)`CertificateInner` fields private

---

x509-cert/src/name.rs

It's been deprecated. This removes it prior to the next breaking release.

x509-cert: remove `RelativeDistinguishedName::encode_from_string`

---

cms/tests/builder.rs
x509-cert/src/builder/profile/cabf.rs
x509-cert/src/builder/profile/cabf/tls.rs
x509-cert/src/name.rs
x509-cert/tests/certificate.rs
x509-cert/tests/certreq.rs
x509-cert/tests/name.rs
x509-cert/tests/pkix_extensions.rs
x509-cert/tests/trust_anchor_format.rs

Explicitly delegates the `iter`, `len`, and `push` methods.

x509-cert: make `RdnSequence`'s inner field private

---

x509-cert/src/builder/profile/cabf.rs
x509-cert/src/builder/profile/cabf/tls.rs
x509-cert/src/name.rs
x509-cert/tests/certificate.rs
x509-cert/tests/certreq.rs
x509-cert/tests/name.rs
x509-cert/tests/pkix_extensions.rs
x509-cert/tests/trust_anchor_format.rs

Like #1508 did to `RdnSequence`, this makes the inner field of the `RelativeDistinguishedName` struct private, instead explicitly delegating the `iter`, `len`, and `push` methods.

x509-cert: make `RelativeDistinguishedName` field private

---

cms/tests/builder.rs
x509-cert/src/builder/profile/cabf.rs
x509-cert/src/builder/profile/cabf/tls.rs
x509-cert/src/ext/pkix/name/dirstr.rs
x509-cert/src/name.rs
x509-cert/tests/certificate.rs
x509-cert/tests/certreq.rs
x509-cert/tests/name.rs
x509-cert/tests/pkix_extensions.rs
x509-cert/tests/trust_anchor_format.rs

This make `FromStr` documented way to build a name. This also exposes a set of getter methods to get elements from the name (CN, Org, ...).
see:
- #1489 
- fixes #1493

x509-cert: make `Name` a new type over `RdnSequence`

---

der/src/tag.rs

KerberosString requirement
see #1511

der: add GeneralString in Tag

---

serdect/src/array.rs
serdect/src/common.rs
serdect/src/slice.rs

Fixes #1322
Also fixed a TODO in `StrIntoBufVisitor::visit_str` by mapping `base16ct` errors to `serde` errors.

serdect: return the deserialized buffer during deserialization

---

x509-cert/src/builder.rs

This makes `add_extension` link back to the example provided in `AsExtension`.
Fixes #1490

x509-cert: document `add_extension` link to examples

---

x509-cert/src/builder.rs
x509-cert/src/builder/profile.rs
x509-cert/src/builder/profile/cabf.rs
x509-cert/src/builder/profile/cabf/tls.rs
x509-cert/src/builder/profile/devid.rs

x509-cert: rename `builder::BuildProfile` to avoid confusion

---

x509-cert/src/builder.rs
x509-cert/src/builder/profile.rs
x509-cert/src/builder/profile/cabf.rs
x509-cert/src/builder/profile/cabf/tls.rs
x509-cert/src/builder/profile/devid.rs

followup on #1514.
Use `BuilderProfile` instead of `BuildProfile` for consistency with the builder.

x509-cert: use `BuilderProfile` for consistency

---

der/src/reader/pem.rs

We now use `doc_auto_cfg` instead

der: remove remaining `doc(cfg(...))`

---

const-oid/src/encoder.rs
const-oid/tests/oid.rs

BER encodings were being miscomputed for certain large arcs.
The previous method was a bit wacky (in addition to being buggy) and attempted to encode each arc backwards within the BER output buffer.
This switches to a new method which splits the upper 7 bits from an arc and encodes that as a byte, continuing until all bytes of the arc have been encoded, which is much more straightforward.
The problematic cases which were reported have now been corrected.
Fixes #1520
cc @zhengyao-lin

const-oid: fix large arc handling in encoder

---

x509-cert/src/certificate.rs

x509_cert::time::Validity used to have Copy, but because it now carries a Profile, it may lose the Copy trait
This forces the profile to be copyable. Profile should not carry state so I don't believe this is much of an issue.

x509-cert: restore Copy for Validity

---

x509-cert/src/time.rs

This is used for idevid certificates burned in hardware.

x509-cert: creates a validity to infinity

---

x509-cert/src/time.rs

Having the profile be private makes it impossible to create a `Validity`. This adds a `Validity::new` to do that.

x509-cert: adds a `Validity::new` method

---

Cargo.lock
Cargo.toml
cms/Cargo.toml
x509-cert/Cargo.toml

ecdsa 0.17.0-pre.9 and p256 0.14.0-pre.2 have now been published

remove git dependencies to ecdsa and p256

---

x509-cert/src/builder.rs

I'm not entirely sure why I introduced that lifetime in the original PR (#1280).

x509-cert: loosen the lifetime requirement for AsyncBuilder

---

.github/workflows/const-oid.yml
.github/workflows/der.yml
const-oid/Cargo.toml
const-oid/README.md
const-oid/src/error.rs
const-oid/src/lib.rs
der/Cargo.toml
der/README.md
der/src/reader/slice.rs
x509-cert/Cargo.toml

Leverages stable support for `core::error::Error` in lieu of `std::error::Error`.
Since this was the only usage of `std`, also removes the `std` feature.

const-oid: remove `std` feature; MSRV 1.81

---

x509-cert/src/anchor.rs
x509-cert/src/builder.rs
x509-cert/src/certificate.rs
x509-cert/src/crl.rs
x509-cert/src/lib.rs
x509-cert/src/request.rs
x509-cert/tests/builder.rs

Re-exports the following with shorter names:
- `spki::AlgorithmIdentifierOwned` => `x509_cert::AlgorithmIdentifier`
- `spki::SubjectPublicKeyInfoOwned` => `x509_cert::SubjectPublicKeyInfo`
These names are already quite long to begin with even without the `*Owned` suffix.
The `x509-cert` crate has a hard dependency on `alloc` and always uses the `*Owned` types, so this allows for more convenient names in this scenario.

x509-cert: re-export `spki` types without `*Owned` suffixes

---

Cargo.lock
cms/Cargo.toml
cms/src/builder.rs
cms/tests/builder.rs

This is a followup on #1531 and #1532

cms: adds support for AsyncSigner

---

der/src/asn1/octet_string.rs

Adds `From` conversions between these types

der: conversions from `OctetString(Ref)` to `Vec`/`Bytes`

---

const-oid/oiddbgen/rfc5753.txt
const-oid/oiddbgen/src/main.rs
const-oid/src/db/gen.rs

**Overview**
This PR adds `RFC5753` OIDs to `const-oid`, as discussed in https://github.com/RustCrypto/formats/issues/1546.
**Rationale**
[RFC 5753 (Use of Elliptic Curve Cryptography (ECC) Algorithms in Cryptographic Message Syntax (CMS))](https://datatracker.ietf.org/doc/html/rfc5753) describes the use of ECC in CMS.
It would be needed for implementation of ECC in CMS - https://github.com/RustCrypto/formats/issues/1544

const-oid: add RFC 5753 OIDs

---

der/src/error.rs

Allows the `Error` trait to be used on `no_std` platforms

der: use `core::error::Error`

---

Cargo.lock
Cargo.toml
cms/Cargo.toml
x509-cert/Cargo.toml
x509-ocsp/Cargo.toml

This removes a git dependencies that was introduced when we broke `pkcs8` API.

chore(deps): bump rsa from 0.10.0-pre.2 to 0.10.0-pre.3

---

pkcs12/Cargo.toml

Only the `kdf` feature uses it.
Closes #1558

pkcs12: make `zeroize` dependency optional

---

der/src/asn1/ia5_string.rs
der/src/asn1/octet_string.rs
der/src/asn1/printable_string.rs
der/src/asn1/teletex_string.rs
der/src/asn1/utf8_string.rs
der_derive/src/asn1_type.rs
der_derive/src/choice/variant.rs

Previously it was using `<asn1_type>::new`.
Using `TryFrom` is more flexible in terms of the possible conversions that it permits.
Also fills out the missing `From`/`TryFrom` conversions needed for the existing crates in this repo (most notably `x509-cert` to compile with the changes).

der_derive: use `TryFrom` conversions for `asn1(type = ...)`

---

cms/Cargo.toml
x509-tsp/Cargo.toml

The crate has a hard dependency on liballoc, so it shouldn't be feature-gated

cms: remove `alloc` feature

---

cms/Cargo.toml

Gets rid of implicit features for each optional dependency

cms: use `dep:` syntax for `builder` feature in Cargo.toml

---

const-oid/oiddbgen/rfc7292.txt
const-oid/oiddbgen/src/main.rs
const-oid/src/db/gen.rs

Adds OIDs from RFC 7292 for PKCS#12 - Reference file available at https://www.rfc-editor.org/rfc/rfc7292.txt.
Closes https://github.com/RustCrypto/formats/issues/1543

const-oid: Add RFC 7292 for PKCS #12

---

.github/workflows/pem-rfc7468.yml
pem-rfc7468/Cargo.toml
pem-rfc7468/README.md
pem-rfc7468/src/error.rs

Allows use of the `Error` trait without the `std` feature enabled, which was stabilized in Rust 1.81

pem-rfc7468: leverage `core::error::Error`; MSRV 1.81

---

sec1/src/error.rs

Allows use of the `Error` trait without the `std` feature enabled, which was stabilized in Rust 1.81

sec1: leverage `core::error::Error`

---

cms/src/builder.rs

This is a followup on #1532. The lifetime requirement on the signature was a mistake.

cms: losen lifetime of the signature

---

.github/workflows/security-audit.yml

We're encountering errors like:
/home/runner/.cargo/bin/cargo-audit: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.39' not found (required by /home/runner/.cargo/bin/cargo-audit)
These are occurring even with freshly-built binaries.
To avoid blocking PRs, temporarily disable the build cache until we have time to properly investigate.

CI: disable `security-audit` cache

---

base64ct/src/alphabet/bcrypt.rs
base64ct/src/alphabet/crypt.rs
base64ct/src/alphabet/shacrypt.rs
base64ct/src/alphabet/standard.rs
base64ct/src/alphabet/url.rs

This PR will implement all derivable std-traits mentioned in [C-COMMON-TRAITS](https://rust-lang.github.io/api-guidelines/interoperability.html) for base64-alphabets. This allows using these types e.g. as `PhantomData<E> where E: Encoding` and derive `PartialOrd` for the container-type. These alphabet-types are unit-structs, so there is not really a reason not to derive everything possible to make them more usable.

base64ct: derive additional traits on alphabets

---

.github/workflows/tai64_update_leap_seconds.yml
tai64/src/lib.rs

Resolves : https://github.com/RustCrypto/formats/issues/675
This PR adds a github actions that runs each week, to check for the leap seconds change in a reputable source and creates a PR to update if necessary.
The PR doesn't contains the process to release automatically as the process could change and maybe we don't want to directly change the version and make the release.
This current PR also include the changes to start with the current value 37 seconds.
Here is some tests I did on a fork : https://github.com/AurelienFT/formats/actions/runs/11470018305/job/31918401654 / https://github.com/AurelienFT/formats/pull/5/files
It could be nice to release a new major this time to have the correct time available for everyone.

Add new action to update leap seconds automatically

---

Cargo.lock
tai64/CHANGELOG.md
tai64/Cargo.toml

Fixed:
- fix TAI offset and verify with GH Action (#1583)
Changed:
- MSRV bump from 1.56 to 1.60 (#802)

tai64: v4.1.0

---

const-oid/src/arcs.rs

Note that we follow Mozilla conventions using maximum 32-bit arcs, linking to a survey of various OID libraries and how they handle various sized arcs.
Also notes we deliberatly do not support UUIDs-as-OIDs, since they're not important (at least within the scope of what we currently implement) to cryptographic use cases this library is intended for.

const-oid: improve rustdoc on `Arc`

---

const-oid/tests/oid.rs

Changes an example to test the `u32::MAX` edge case for OIDs, and ensures all of the relevant methods are tested.

const-oid: test max arc edge case; more coverage

---

const-oid/src/error.rs
const-oid/src/parser.rs
const-oid/tests/oid.rs

Adds an `Error::RepeatedDot` case and handles it within the parser

const-oid: handle repeated dot characters in input

---

const-oid/src/encoder.rs

Prefer panicking instead so underflow bugs aren't silent

const-oid: eliminate `split_high_bits` side effects

---

const-oid/src/encoder.rs
const-oid/src/parser.rs

Ensures overflow will always cause a panic instead

const-oid: elimiate arithmetic side effects in arc encoder

---

const-oid/src/encoder.rs

Adds internal tests which check the basic behavior of `split_hi_bits` in the OID encoder logic.

const-oid: basic `split_hi_bits` smoke tests

---

const-oid/src/arcs.rs
const-oid/src/checked.rs
const-oid/src/encoder.rs
const-oid/src/error.rs
const-oid/src/parser.rs
const-oid/tests/oid.rs

This changes the base 128 decoder to calculate the length of a base 128-encoded arc and then iterates over each byte, computing the value for that byte, without any mutable state other than the position.
It also refactors the unit tests and adds an example extracted from proptest failures. The new implementation passes that test.
Closes #1585

const-oid: fix (and simplify) base 128 encoder

---

Cargo.lock
const-oid/Cargo.toml
const-oid/tests/proptests.proptest-regressions
const-oid/tests/proptests.rs

Exercises the parser beyond what we currently do in unit tests

const-oid: add basic proptests

---

const-oid/src/checked.rs
const-oid/src/encoder.rs
const-oid/src/error.rs

Returns `Error::Overflow` if any operations overflow

const-oid: replace panics with `checked_*!` macros

---

der/src/referenced.rs

Rust 1.83 has new suggestion on the formatting of code.
This fixes the CI.

chrore: fixup rust 1.83 formatting

---

pkcs5/src/pbes2/encryption.rs

Fixes https://github.com/RustCrypto/formats/issues/1624
Without digging into why the error occurs, this seems to fix the error, and it seems safe to do the conversion in this instance.

pkcs5: fix type annotation required error

---

cmpv2/src/body.rs

Looking at the rest of thge PkiBody the uppercase U in KUr seems to be a spelling error...

Fix spelling in body::PkiBody, change KUr to Kur

---

Cargo.lock
serdect/CHANGELOG.md
serdect/Cargo.toml
serdect/src/common.rs

NOTE: this release includes major breaking changes to the wire format, namely all bytestrings now include a length prefix, even when serializing fixed-size arrays. This is intended to work around deficiencies in the `serde` API (see serde-rs/serde#2120) as well as serde-based format implementations which have variable-time behavior when using `serialize_tuple`.
Any binary data serialized with previous versions of `serdect` now needs a length prefix prepended to the data, which will vary depending on the particular data format.
- Switch to length-prefixed encoding using the `serialize_bytes` method ([#1112], [#1515])
- MSRV 1.70 ([#1244])
[#1112]: https://github.com/RustCrypto/formats/pull/1112
[#1515]: https://github.com/RustCrypto/formats/pull/1515
[#1244]: …

serdect v0.3.0

---

x509-cert/src/builder/profile/cabf.rs

The former is available in liballoc.
Closes #1641

x509-cert: use `BTreeSet` instead of `HashSet`

---

x509-cert/src/builder.rs
x509-cert/src/ext/pkix/name/general.rs
x509-cert/src/lib.rs

Enables the following clippy lints:
- `clippy::alloc_instead_of_core`
- `clippy::std_instead_of_alloc`
- `clippy::std_instead_of_core`
These check that imports are coming from the correct package in the standard library, enabling more features to be used in `no_std` environments.

x509-cert: enable and fix clippy `core`/`alloc`/`std` lints

---

.github/workflows/workspace.yml
base64ct/src/encoder.rs
cms/tests/builder.rs
der/src/str_owned.rs
der/src/str_ref.rs
pem-rfc7468/src/encoder.rs
pkcs1/src/private_key.rs

Also runs `cargo clippy --fix` to correct warnings

CI: bump `clippy` to v1.84

---

tls_codec/benches/quic_vec.rs
tls_codec/benches/tls_vec.rs

Benches now use [`iter_batched_ref`] with provided buffers when serializing and returned buffers when deserializing. This avoids measuring allocations.
[`iter_batched_ref`]: https://docs.rs/criterion/0.5.1/criterion/struct.Bencher.html#method.iter_batched_ref

tls_codec: remove measuring allocs in benchmarks

---

.github/workflows/workspace.yml
const-oid/src/arcs.rs
der/src/asn1/real.rs

Rust 1.85 released today and brings new lints:
https://rust-lang.github.io/rust-clippy/master/index.html#precedence

fixup clippy 1.85 lints

---

Cargo.lock
base32ct/CHANGELOG.md
base32ct/Cargo.toml

- `const fn` for `encoded_len` ([#1424])
[#1424]: https://github.com/RustCrypto/formats/pull/1424

base32ct v0.2.2

---

Cargo.lock
const-oid/CHANGELOG.md
const-oid/Cargo.toml

- `ObjectIdentifier::starts_with` ([#964])
- SHA-3 OIDs ([#1000])
- RFC6962 OIDs ([#1094])
- RFC2985 OIDS for PKCS#9 ([#1248])
- `ObjectIdentifierRef` type ([#1305], [#1308])
- RFC7693 OIDs for BLAKE2 ([#1261])
- TPM-related OIDs ([#1337])
- STB (Belarus standards) OIDs ([#1394])
- RFC3161 OIDs ([#1407])
- OIDs for ML-DSA and SLH-DSA ([#1541])
- RFC5753 OIDs ([#1547])
- RFC7292 OIDs for PKCS#12 ([#1568])
- Brainpool RFC5639 OIDs ([#1636])
- Support for X.509 `GN` as an alias to `givenName` ([#1648])
- Return all matched names when looking up OID ([#1129])
- Make `ObjectIdentifier`'s size const generic ([#1300])
- Upgrade to 2024 edition; MSRV 1.85 ([#1670])
- Off-by-one error in `Encoder` size check ([#1304])
- Large arc handling ([#1522], [#1592])
- Handling of repeated dot characters in …

const-oid v0.10.0

---

der/src/asn1/context_specific.rs
der/src/asn1/optional.rs
der/src/encode.rs
der/src/header.rs
der/src/length.rs
der/src/reader.rs
der/src/tag.rs
der/src/tag/class.rs
der/src/tag/number.rs
pkcs1/src/version.rs
pkcs8/src/version.rs
x509-cert/tests/pkix_extensions.rs

This is a smaller version of https://github.com/RustCrypto/formats/pull/1416, but for 32-bit tag numbers.
The PR is intentionally small and only changes handling of `Tag` and `TagNumber` types.
The use case for 32-bit tag numbers instead of 16-bit is the [Image4 format](https://theapplewiki.com/wiki/IMG4_File_Format#IMG4_Manifest) used in apple firmware files which needs PRIVATE tags with 32-bit numbers.
* TagNumber::new() and TagNumber::value() use `u32` now
* Conversions from and to `u8` for `Tag` and `TagNumber` do not make sense anymore, this also applies to `Tag::octet()`
* `Length::for_tlv()` just assumed, that a tag is always one byte, it now somehow needs to know about the specific tag we are looking at

Make TagNumber support tags beyond 30.

---

der/src/asn1/octet_string.rs
der/tests/derive.rs

Fixes simple case:
```rust
#[derive(Sequence)]
pub struct MySequence<'a> {
#[asn1(type = "OCTET STRING", context_specific = "0", optional = "true")]
pub my_byte_slice: Option<&'a [u8]>,
}
```
Helpful:
`cargo test -p der -F derive,alloc,oid --test derive -- sequence::type_combinations_instance`
`cargo expand --test derive -p der -F derive,alloc,oid > expanded.rs`

fix: derive(Sequence) on field: Option<&'a [u8]>

---

Cargo.lock
base64ct/CHANGELOG.md
base64ct/Cargo.toml

Added
- derive additional traits on alphabets (#1578)
Changed
- MSRV 1.85 // Edition 2024 (#1670)
- reject zero-length decode requests (#1387)
- use `core::error::Error` (#1681)

base64ct: v1.7.0

---

der/src/asn1/bit_string.rs
der/src/asn1/octet_string.rs
der/tests/derive.rs
der_derive/src/asn1_type.rs
der_derive/src/attributes.rs
der_derive/src/sequence/field.rs

Fixes: 
- #1539
Adds attribute:
- `deref = "true"`
```rust
#[derive(Sequence)]
pub struct MySequence {
/// Without deref = "true" macro generates an error:
///
/// the trait `From<Vec<u8>>` is not implemented for `BitStringRef<'_>`
#[asn1(type = "OCTET STRING", deref = "true")]
pub owned_bytes: Vec<u8>,
}
```
Is there any better way to add `&` ?

der: fix derive(Sequence) on field: Vec<u8>

---

const-oid/oiddbgen/rfc9688.txt
const-oid/oiddbgen/src/main.rs
const-oid/src/db/generated.rs

This includes OIDs for the use of sha3 digests in various contexts.

const-oid: Add OIDs from rfc9688.

---

.cargo/audit.toml
.github/workflows/security-audit.yml

Ignores RUSTSEC-2024-0436: `paste` is unmaintained

CI: fix security audit

---

base64ct/CHANGELOG.md
base64ct/Cargo.lock
base64ct/Cargo.toml
base64ct/README.md

- MSRV 1.81 - edition downgraded to 2021 from [yanked 1.7.0 release](https://github.com/RustCrypto/formats/blob/master/base64ct/CHANGELOG.md#170-2025-02-25-yanked) ([#1702])
[#1702]: https://github.com/RustCrypto/formats/pull/1702

base64ct v1.7.1

---

base64ct/src/decoder.rs

This reverts commit a375cbf5bd0abd5159d4b3ec203d8b0a9166d1d6 from #1387.
This was a breaking change which is causing issues in the `der` crate.
See #1711

Revert "base64ct: reject zero-length decode requests (#1387)"

---

base64ct/CHANGELOG.md
base64ct/Cargo.lock
base64ct/Cargo.toml

- Revert [#1387]: reject zero-length decode requests as it's a breaking change ([#1714])
[#1387]: https://github.com/RustCrypto/formats/pull/1387
[#1714]: https://github.com/RustCrypto/formats/pull/1714

base64ct v1.7.2

---

base64ct/src/decoder.rs
der/tests/pem.rs

This is another take on https://github.com/RustCrypto/formats/pull/1714
That brings back the original fix, but does not reject with `InvalidLength` when the out buffer is empty.

base64ct: Don't fail with `InvalidLength` when reading nothing at end of data

---

base64ct/CHANGELOG.md
base64ct/Cargo.lock
base64ct/Cargo.toml

- Don't fail with `InvalidLength` when reading nothing at end of data ([#1716]).
[#1716]: https://github.com/RustCrypto/formats/pull/1716

base64ct: v1.7.3

---

der/src/asn1.rs
der/src/asn1/bit_string.rs
der/src/asn1/bit_string/fixed_len_bit_string.rs
der/src/lib.rs
der/tests/derive.rs
der_derive/src/bitstring.rs
der_derive/src/bitstring/field.rs
der_derive/src/lib.rs

Adds macro:
```rust
#[derive(BitString)]
pub struct MyBitString {
pub flag_0: bool,
pub flag_1: bool,
pub flag_2: bool,
}
```
Which produces example ASN.1: https://lapo.it/asn1js/#AwIF4A
```
BIT STRING (3 bit) 111
03 02 05 E0
```

der_derive: add BitString macro

---

der/src/asn1/generalized_time.rs
der/src/datetime.rs

der: const GeneralizedTime::from_date_time

---

der/src/decode.rs
der/src/reader/slice.rs
der/tests/derive.rs

der: add from_der_partial on Decode trait

---

der/src/length.rs

`Length` type was previously limited to 256 MiB. This PR removes the limit and changes the internal representation to `usize` instead of `u32`.

der: remove 256 MiB limit on `Length`

---

der/src/asn1/bit_string.rs
der/src/asn1/octet_string.rs
der/tests/derive.rs

Fixes: 
- #1730
```rust
#[derive(Sequence)]
pub struct MyStackAllocSequence {
#[asn1(type = "OCTET STRING", deref = "true")]
pub array_bytes: [u8; 2],
}
```

der: conversions between `BitStringRef`/`OctetStringRef` and `[u8; N]`

---

der/src/asn1/bit_string.rs
der/src/asn1/bit_string/allowed_len_bit_string.rs
der/src/lib.rs
der/tests/derive.rs
der_derive/src/bitstring.rs

Fixes my previous mistake in `value_len` for derived BitString.
Mistake: https://github.com/RustCrypto/formats/commit/c1d90bfcea8e2f8a813bec38a19f1c205838b0c4#diff-3576513639170e7fef485dabdeaf8981757ade091a9d0bcb4c5b43d62dcb65b5R150
Encoded length is now data-independent.

der_derive: fix derive(BitString): always encode max length

---

cmpv2/src/body.rs

Hey all, my PR is related to the cmpv2 crate.
I noticed that `PkiBody::PollReq` and `PkiBody::PollRep` have the same variant content:
```rust
enum PkiBody<'a> {
PollReq(PollRepContent<'a>),
PollRep(PollRepContent<'a>),
}
```
In [RFC4210 section 5.1.2](https://www.rfc-editor.org/rfc/rfc4210#section-5.1.2), they are declared as follows:
```
/// PKIBody ::= CHOICE {       -- message-specific body elements
///     ...other variants omitted for brevity...
///     pollReq  [25] PollReqContent,         --Polling request
///     pollRep  [26] PollRepContent          --Polling response
/// }
```
I believe this discrepancy was unintended and my PR fixes it. Please let me know if you have any feedback. 
Thank you!

cmpv2: fix content of PkiBody::PollReq

---

der/src/lib.rs
der/tests/derive.rs
der_derive/src/lib.rs
der_derive/src/sequence.rs

Fixes
- #1705
Adds DecodeValue macro:
```rust
#[derive(DecodeValue)]
struct MyDecodeOnly {
field: u8,
}
impl FixedTag for MyDecodeOnly {
const TAG: Tag = Tag::Sequence;
}
```
and EncodeValue:
```rust
#[derive(EncodeValue)]
struct MyEncodeOnly {
field: u8,
}
impl FixedTag for MyEncodeOnly {
const TAG: Tag = Tag::Sequence;
}
```

der_derive: add DecodeValue, EncodeValue macros

---

der/src/tag/class.rs
der/tests/derive.rs

It's needed for generic Application, ContextSpecific, Private tags.
My old PR:
- #1545
This PR contains [der/src/tag/class.rs](https://github.com/RustCrypto/formats/pull/1545/files#diff-8177ef1197997d88f9183da076e7c87e5768cc482aac5ad5ab1dc4d877a84b2d)
`.bits()` will be used in generic wrappers like this:
```rust
impl<'a, const TAG: u32, T, const CLASS: u8> Choice<'a> for CustomClassExplicit<TAG, T, CLASS>
where
T: Decode<'a> + Tagged,
{
fn can_decode(tag: Tag) -> bool {
tag.class().bits() == CLASS && tag.number() == TagNumber(TAG)
}
}
```
and `const`s like this:
```rust
/// Application class wrapper, EXPLICIT
pub type ApplicationExplicit<const TAG: u32, T> = CustomClassExplicit<TAG, T, CLASS_APPLICATION>;
```

der: add class bits consts for Application and Private tag support

---

pkcs8/src/private_key_info.rs

Adds a hint that might have prevented #1749.
The different formats of the private key per algorithm is already mentioned in the struct documentation and the referenced RFC also documents this fact.
Here we add a breadcrumb inline on the specific field to that fact. This should tell people "Hey, this isn't the actual private key. It's still encoded."
The new generic struct already gives a neat hint towards that fact. Previously it was just a byte slice.

pkcs8: add hint on `private_key` field about its format (#1749)

---

const-oid/CHANGELOG.md
const-oid/Cargo.toml

- RFC9688 OIDs ([#1692])
- Encoder `base128_len` calculation ([#1753])
[#1692]: https://github.com/RustCrypto/formats/pull/1692
[#1753]: https://github.com/RustCrypto/formats/pull/1753

const-oid v0.10.1

---

der/tests/derive.rs
der_derive/src/asn1_type.rs
der_derive/src/attributes.rs

der: fix derive optional OCTET/BIT STRING on `Option<&[u8]>`

---

der/src/encode.rs
der/tests/derive.rs

This is a request to backport #1760 to `der` v0.7 and a consequent point release.
Context: some parts of PKCS#11 require supplying ASN.1 encoded values. I spent quite some time until I figured out something is wrong with the encoding :sweat_smile:.

Backport #1760

---

der/CHANGELOG.md
der/Cargo.toml

Fixed:
- append in `Encode::encode_to_vec` (backport [#1760])
[#1760]: https://github.com/RustCrypto/formats/pull/1760

der: v0.7.10

---

der/src/arrayvec.rs
der/src/asn1/set_of.rs
x509-cert/src/attr.rs
x509-cert/src/name.rs

Fixes https://github.com/RustCrypto/formats/issues/1763
This is stacked on #1689 for convenience.

x509-cert: impl hash for name

---

base64ct/src/encoder.rs

base64ct: docs: return `Ok(())` in `Encoder::encode`

---

der/src/asn1/context_specific.rs
x509-cert/tests/pkix_extensions.rs

der: read_nested: check header length matches contents of IMPLICIT

---

Cargo.lock
cmpv2/Cargo.toml
cmpv2/src/oob.rs
crmf/src/controls.rs
x509-cert/Cargo.toml
x509-cert/src/certificate.rs

cmpv2: build `OobCertHash` from a certificate

---

x509-cert/Cargo.toml
x509-cert/src/builder.rs
x509-cert/tests/builder.rs

- Removed sha1/default, since that includes std feature.
- Set der to the latest rc version.
- Used dep: syntax for feature based dependencies
Note: I was unable to run **all** tests due to not having the `zlint` installed.

x509-cert: remove unnecessary `builder` feature activations

---

der/src/asn1.rs
der/src/asn1/general_string.rs
gss-api/src/negotiation.rs

Better than using `AnyRef` and `.value()[2..]`

gss-api: change `NegHints::hint_name` to GeneralStringRef type

---

pkcs8/src/private_key_info.rs

Future-proof reading of [1] requires reading [0] first

pkcs8: add `PrivateKeyInfo.attributes` [0] IMPLICIT reader

---

der/src/asn1/context_specific.rs
der/src/lib.rs
der/src/tag.rs
der/tests/derive.rs
der_derive/src/choice.rs

Closes #1741 
Depends on:
- #1779
This PR drops the need to implement `Tagged` on all structs that are IMPLICIT.
Such change simplifies trait bounds for generic `IMPLICIT` fields and enforces strict `const` constructed bit check.

der: add `IsConstructed` trait, impl'ed on any `FixedTag`

---

der/src/asn1/bmp_string.rs
der_derive/src/asn1_type.rs

Partial fix for:
- #1792
```rust
#[derive(Clone, Debug, Eq, PartialEq, Choice, ValueOrd)]
pub enum DirectoryString {
// ..
#[asn1(type = "BMPString")]
BmpString(BmpString),
}
```

der: fix BMPString compatibility in derive macros

---

der/src/asn1/any.rs
der/src/bytes_owned.rs
der/src/bytes_ref.rs
der/src/length.rs

Removes `expect`/`unwrap` in `AnyRef::from`

der: const `Any::to_ref`, `BytesOwned::to_ref`

---

der/src/ord.rs

Fixes #1798
Should produce faster compile times for anything using `der`.
`x509-cert` with new `der_ord`:
```shell
./formats$ CARGO_PROFILE_RELEASE_LTO=fat cargo llvm-lines --release -p x509-cert | head -20
Lines                Copies              Function name
-----                ------              -------------
58324                1305                (TOTAL)
2241 (3.8%,  3.8%)    12 (0.9%,  0.9%)  <der::reader::slice::SliceReader as der::reader::Reader>::read_nested
1826 (3.1%,  7.0%)    24 (1.8%,  2.8%)  <core::ops::index_range::IndexRange as core::iter::traits::iterator::Iterator>::try_fold
1711 (2.9%,  9.9%)    59 (4.5%,  7.3%)  <T as der::encode::Encode>::encoded_len
1668 (2.9%, 12.8%)    12 (0.9%,  8.2%)  der::ord::iter_cmp
1663 (2.9%, 15.6%)    23 (1.8%, 10.0%) …
```

der: rewrite `der_ord` as match without try! `?` operator

---

der/src/asn1/sequence_of.rs
der_derive/src/sequence.rs

Same command, `cargo bloat`,
before:
```shell
./formats$ cargo bloat -p x509-cert --test certificate --filter "decode_value" --full-fn -w --release -n 40
Analyzing target/release/deps/certificate-4493036956d2881b
File .text   Size Crate Name
0.0%  0.0%   383B   der der::asn1::integer::uint::<impl der::decode::DecodeValue for u8>::decode_value::h99fa4cf07ef3366b
0.0%  0.0%   362B   der der::asn1::integer::uint::<impl der::decode::DecodeValue for u8>::decode_value::he68458e496aeea63
0.0%  0.0%   295B   der <der::asn1::bit_string::allocating::BitString as der::decode::DecodeValue>::decode_value::hc7370e53337cbdd6
0.0%  0.0%   263B   der <der::asn1::bit_string::allocating::BitString as der::decode::DecodeValue>::decode_value::h5311ed49f05453cb
0.0%  0.2% 1.3KiB       filtered data size, the …
```

der: rename `decode_value` fns for cleaner cargo bloat output

---

der/src/asn1/context_specific.rs
der/src/tag.rs

Fixes #1723
I simplified fn `decode_with` into `peek_tag_matches`.
Depends on:
- #1783

der: use strict context-specific skipping condition (equal tag numbers only)

---

der/src/length.rs
der/src/lib.rs

The original idea of this type was to have a type-safe distinction between DER lengths (`Length`) and potentially indefinite BER lengths (`IndefiniteLength`), but really what's needed is to make the `Length` type support idefinite lengths when `EncodingRules::Ber` are in use.
Otherwise, we need to change `Header` to use `IndefiniteLength`, which kind of defeats the point.

der: remove `IndefiniteLength`

---

Cargo.lock
Cargo.toml
cms/Cargo.toml
x509-cert/Cargo.toml
x509-ocsp/Cargo.toml

This depends on:
- https://github.com/RustCrypto/RSA/pull/513
- https://github.com/RustCrypto/signatures/pull/953
- https://github.com/RustCrypto/elliptic-curves/pull/1181
- https://github.com/RustCrypto/signatures/pull/955

Bump to `signature` 3

---

der_derive/src/sequence.rs

Fixes #1800
```shell
./formats$ cargo llvm-lines --release -p x509-cert | head -20
Lines                Copies              Function name
-----                ------              -------------
56603                1235                (TOTAL)
2065 (3.6%,  3.6%)    59 (4.8%,  4.8%)  <T as der::encode::Encode>::encoded_len
1791 (3.2%,  6.8%)    25 (2.0%,  6.8%)  core::iter::traits::iterator::Iterator::try_fold
1728 (3.1%,  9.9%)    12 (1.0%,  7.8%)  der::ord::iter_cmp
1708 (3.0%, 12.9%)    12 (1.0%,  8.7%)  <der::reader::slice::SliceReader as der::reader::Reader>::read_nested
1597 (2.8%, 15.7%)    13 (1.1%,  9.8%)  <T as der::decode::Decode>::decode
1343 (2.4%, 18.1%)    14 (1.1%, 10.9%)  <der::reader::slice::SliceReader as der::reader::Reader>::finish
1240 (2.2%, 20.3%)    20 (1.6%, 12.6%) …
```

der_derive: rewrite `EncodeValue::value_len` as simple addition

---

der/src/asn1/context_specific.rs
der/src/tag.rs

Also removed generic `E: From<Error>`

der: simplify `Tag::peek_matches` in context-specific decoder

---

x509-cert/src/builder.rs

Reverts RustCrypto/formats#1777
There is regression in ecdsa that causes tests to fail on master. This triggers because of this. I'll revert it for now.

Revert "x509-cert: document builder mistakes"

---

x509-cert/src/builder/profile/cabf/tls.rs

Relevant CABF profile:
https://github.com/cabforum/servercert/blob/main/docs/BR.md#71272-domain-validated

x509-cert: domain validated should accept CN even though not recommended

---

Cargo.lock
x509-cert/src/builder.rs

This reverts #1816 and this is a redo of https://github.com/RustCrypto/formats/pull/1777

x509-cert: document builder mistakes

---

x509-cert/src/builder.rs
x509-cert/src/crl.rs
x509-cert/src/ext/pkix/crl.rs
x509-cert/test-support/src/openssl.rs
x509-cert/tests/builder_crl.rs

This adds a builder interface for CRLs.
This would accept an iterator for the certificates to be revoked.
```rust
let builder = CrlBuilder::new(&ca_certificate, crl_number)?
.with_certificates(
vec![
RevokedCert {
serial_number: serial_number1,
revocation_date: Time::now()?,
crl_entry_extensions: None,
},
RevokedCert {
serial_number: serial_number2,
revocation_date: Time::now()?,
crl_entry_extensions: None,
},
]
.into_iter(),
);
let crl = builder.build(&signer)?;
```

x509-cert: add a CRL builder

---

cmpv2/src/status.rs

Hey all.
These changes are related to the cmpv2 crate:
1. When trying to decode an error message which has, e.g. `transactionIdInUse` set, parsing will fail with an error. The type of the `PkiFailureInfoValues` flagset should be a `u32` instead of a `u16`, there are currently 27 possible values for this enum (see [RFC 4210 section 5.2.3](https://datatracker.ietf.org/doc/html/rfc4210#section-5.2.3)).
2. The value of the `BadTime` variant must be 3 not 2, according to [RFC 4210 section 5.2.3](https://datatracker.ietf.org/doc/html/rfc4210#section-5.2.3).

cmpv2: make `PkiFailureInfoValues` a `u32`; fix `BadTime` variant 

---

der/tests/derive.rs
der_derive/src/attributes.rs
der_derive/src/choice.rs
der_derive/src/choice/variant.rs
der_derive/src/sequence.rs
der_derive/src/sequence/field.rs
der_derive/src/tag.rs

der: add derive support for `APPLICATION` and `PRIVATE` tags

---

der_derive/src/sequence.rs

Forgot `#[doc(hidden)]` in #1802
I don't know if `#[automatically_derived]` is needed.

der_derive: decode_value_inner `#[doc(hidden)]`

---

der/src/header.rs
der/src/length.rs
der/src/tag.rs

Bug: 11-byte peek read only 10 bytes previously

der: fix `Header::peek` + add tests

---

der/src/asn1/null.rs

der: test `Null` decode invalid length

---

crmf/src/pop.rs

crmf: fix infinite recursion in `EncKeyWithIdChoice::tag`

---

der/src/asn1/bit_string.rs
der/src/asn1/sequence_of.rs
der/src/asn1/set_of.rs

The test was failing because:
```
failures:
---- asn1::set_of::tests::setof_valueord stdout ----
thread 'asn1::set_of::tests::setof_valueord' panicked at core/src/iter/traits/exact_size.rs:122:9:
assertion `left == right` failed
left: None
right: Some(0)
```

der: fix panic in `value_cmp`: add `Iterator::size_hint` + tests

---

.github/workflows/cmpv2.yml
.github/workflows/cms.yml
.github/workflows/crmf.yml
.github/workflows/gss-api.yml
.github/workflows/x509-cert.yml
.github/workflows/x509-ocsp.yml
.github/workflows/x509-tsp.yml
Cargo.lock
Cargo.toml
pkcs12/src/kdf.rs
pkcs5/src/pbes2/encryption.rs

Sadly there is some API breaks and we need to split the workspace again to be able to have pkcs5 pass the break first, and then pull RSA, and then we will be able to bring back the workspace together.
Depends:
- https://github.com/RustCrypto/password-hashes/pull/592

pkcs5+pkcs12: migrate to the digest newtype api

---

Cargo.lock
Cargo.toml
cmpv2/Cargo.toml
cms/Cargo.toml
crmf/Cargo.toml
gss-api/Cargo.toml
pkcs1/Cargo.toml
pkcs12/Cargo.toml
pkcs5/Cargo.toml
pkcs5/src/pbes2.rs
pkcs5/src/pbes2/encryption.rs
pkcs5/src/pbes2/kdf.rs
pkcs8/Cargo.toml
pkcs8/tests/encrypted_private_key.rs
sec1/Cargo.toml
spki/Cargo.toml
x509-cert/Cargo.toml
x509-ocsp/Cargo.toml
x509-tsp/Cargo.toml

- `pkcs1` 0.8.0-rc.2
- `pkcs5` 0.8.0-rc.4
- `pkcs8` 0.11.0-rc.4
- `sec1` 0.8.0-rc.5
- `spki` 0.8.0-rc.2

 pkcs1+pkcs5+pkcs8+sec1+spki: rc releases

---

.cargo/audit.toml
.github/workflows/cmpv2.yml
.github/workflows/cms.yml
.github/workflows/crmf.yml
.github/workflows/gss-api.yml
.github/workflows/x509-cert.yml
.github/workflows/x509-ocsp.yml
.github/workflows/x509-tsp.yml
Cargo.lock
Cargo.toml
cms/Cargo.toml
x509-cert/Cargo.toml
x509-ocsp/Cargo.toml

We've split the workspace in https://github.com/RustCrypto/formats/pull/1847 to be able to release pkcs* crates and make a release of rsa.
This brings back the workspace together.

reunite workspace

---

der/src/asn1/octet_string.rs

```
_______________________________________
/ #[asn1(context_specific = "6", type = \
| "OCTET STRING", deref = "true")]      |
|                                       |
\ public_point: Cow<'a, [u8]>,          /
---------------------------------------
\   ^__^
\  (oo)\_______
(__)\       )\/\
||----w |
||     ||
```

der: support `Cow<[u8]>` in derive(Sequence)

---

Cargo.lock
base64ct/CHANGELOG.md
base64ct/Cargo.toml

- Bump edition to 2024; MSRV 1.85 ([#1839])
[#1839]: https://github.com/RustCrypto/formats/pull/1839

base64ct v1.8.0

---

Cargo.lock

```
Updating anstyle v1.0.10 -> v1.0.11
Unchanged bincode v1.3.3 (available: v2.0.1)
Updating bitflags v2.9.0 -> v2.9.1
Updating clap v4.5.35 -> v4.5.40
Updating clap_builder v4.5.35 -> v4.5.40
Updating clap_lex v0.7.4 -> v0.7.5
Updating errno v0.3.11 -> v0.3.12
Removing getrandom v0.2.15
Updating hashbrown v0.15.2 -> v0.15.4
Updating inout v0.2.0-rc.4 -> v0.2.0-rc.5
Updating libc v0.2.171 -> v0.2.172
Updating linux-raw-sys v0.9.3 -> v0.9.4
Updating proc-macro2 v1.0.94 -> v1.0.95
Updating proptest v1.6.0 -> v1.7.0
Removing rand v0.8.5
Removing rand_chacha v0.3.1
Removing rand_core v0.6.4
Updating rand_xorshift v0.3.0 -> v0.4.0
Updating rustix v1.0.5 -> v1.0.7
Updating serde_spanned v0.6.8 -> v0.6.9
Updating syn v2.0.100 -> v2.0.101
Updating tempfile v3.19.1 -> v3.20.0
Updating toml …
```

workspace: update dependencies

---

x509-cert/src/certificate.rs

When storing serialnumbers in a database, a btree or similar structure, the serial number could be required to implement Ord. This is useful for a CRL database for example.
This is only possible if the Profile itself implements Ord. As this is a very cheap requirement for the profile itself, this is now part of the Profile trait.

x509-cert: allow serialnumbers to be stored in a database

---

x509-cert/src/builder.rs
x509-cert/tests/builder_crl.rs

Entries in a CRL may not comply fully with RFC5280 and the builder should not put undue bounds on the serial numbers.

x509-cert: expose profile in the CrlBuilder

---

Cargo.lock
cms/Cargo.toml
x509-cert/Cargo.toml

This bumps:
- `elliptic-curve` from `0.14.0-rc.5` to `0.14.0-rc.6`
- `ecdsa` from `0.17.0-rc.1` to `0.17.0-rc.2`

workspace: bump dependencies

---

der/src/asn1/internal_macros.rs
der/src/asn1/sequence_of.rs
der/src/asn1/set_of.rs
der/src/decode.rs
der/src/reader.rs
der_derive/src/sequence.rs
pkcs1/src/params.rs
pkcs1/src/private_key.rs
pkcs1/src/private_key/other_prime_info.rs
pkcs1/src/public_key.rs
pkcs12/src/safe_bag.rs
pkcs8/src/encrypted_private_key_info.rs
pkcs8/src/private_key_info.rs
sec1/src/private_key.rs
spki/src/algorithm.rs
spki/src/spki.rs
x509-cert/src/time.rs
x509-cert/tests/certificate.rs

Previously `der` lacked an abstraction for automatically setting up nested readers when decoding values, so every `DecodeValue` impl ended up handling its own nesting.
This adds a new provided method to the `Reader` trait which automatically handles nesting.
This change is backwards compatible in that if a `DecodeValue` impl does its own `reader.read_nested`, it will just create another nested reader of the same length, which is redundant but doesn't break anything. However, we should remove all of the `read_nested` calls from `DecodeValue` impls with this approach anyway as they're redundant.
Using a provided method for this opens up the possibility of reader-specific handling of field decoding, which would be useful for addressing indefinite length handling for BER decoding (#779).

der: add `Reader::read_value`, auto-nest `DecodeValue`

---

der/src/reader.rs
der/src/reader/pem.rs
der/src/reader/position.rs

Extracts a state management struct for nested position tracking.
The goal is to support nested message parsing keeping track of where we are in the message using only the call stack, i.e. without the need to keep such information on the heap, as this crate is intended to support no_std/no-alloc "heapless" targets.
Extracting this logic into its struct not only makes it potentially reusable, but makes it significantly easier to test, and this commit also adds a number of initial tests.

der: extract `reader::position::Position`

---

Cargo.lock
cms/Cargo.toml
x509-cert/Cargo.toml
x509-ocsp/Cargo.toml

Also bumps: `ecdsa`, `rsa`, `p256`

Bump `crypto-bigint` to v0.7.0-pre.5

---

der/src/error.rs
der/src/length.rs
der/src/reader.rs

Adds initial support to the `Length` type for decoding indefinite lengths when `EncodingRules::Ber` are in use.
Note that this only adds the needed support to the `Length` type and handling of the constructed form of various universal tags (which may require a special `Reader` implementation for BER).

der: preliminary indefinite length support

---

der/src/length.rs
der/src/tag/number.rs

The bytes `00 00` are used as a marker that we've reached the end of an indefinite length field, and are not of interest to someone who wants the actual value contained in the field.

der: remove EOC bytes from decoded indefinite lengths

---

der/src/asn1/optional.rs
der/src/header.rs
der/src/tag.rs

We can rely on the ability to clone the `Reader` to use the `Decode` implementation to implement peeking, so we don't need a separate bespoke implementation.
This also avoids losing the `Reader` context while peeking.

der: simplify `Header::peek` and `Tag::peek`

---

der/src/asn1/internal_macros.rs
der/src/decode.rs
der/src/reader.rs

This was added in #1877 but the real value of that PR was the automatic `read_nested` on `DecodeValue` impls. `Reader::read_value` isn't actually necessary for that at all.
It may be useful in the future if we introduce a BER reader that can handle decoding constructed e.g. strings from indefinite length encoding, but since we don't actually have anything like that yet, removing this avoids some unnecessary duplication and API surface for the `Reader`.

der: remove `Reader::read_value`

---

Cargo.lock
Cargo.toml
der/src/tag.rs

The relevant branches have been merged

Cargo.toml: remove branches from `patch.crates-io`

---

x509-cert/tests/certificate.rs
x509-cert/tests/examples/lenovo_pk.pem

It is convenient to have the text form alongside a certificate for debug purpose.
This test ensures we can accpt them.

x509-cert: ensure pem reader accept preambles

---

cms/tests/tests_from_pkcs7_crate.rs
der/src/asn1/internal_macros.rs
der/src/decode.rs
der/src/length.rs
der/src/reader.rs

One of the blockers for addressing indefinite length handling (#779) has been where to consume the EOC tag.
This commit (re)introduces `Reader::read_value` (added in #1877, removed in #1887) and handles decoding the EOC there. This gives us a single place where EOC can be handled for all constructed messages.
With these changes, the decoder is able to parse `cms_ber.bin` from `cms/tests`, from which the `cms_der.bin` file has been translated. This file provides a real-world example of nested indefinite lengths from CMS.
Note, however, that the example contains a constructed `Any` which isn't yet being correctly handled. A `TODO` for ensuring the BER and DER decode identically has been added.
cc @dishmaker

der: (re-)add `Reader::read_value` with EOC support

---

der/src/asn1/any.rs
der/src/asn1/internal_macros.rs
der/src/decode.rs
der/src/reader.rs

Moves `Reader::read_value` out of the trait and into an internal free function

der: move `read_value` out of public API

---

der/src/bytes_owned.rs
der/src/reader.rs

Extracts it out of `BytesOwned` so it's generally useful

der: refactor indefinite length decoder

---

der/src/bytes_owned.rs
der/src/length.rs
der/src/length/indefinite.rs
der/src/reader.rs

Extracts a module containing everything related to indefinite length handling in a single place

der: extract `length::indefinite` module

---

.github/workflows/mcf.yml
Cargo.lock
Cargo.toml
mcf/CHANGELOG.md
mcf/Cargo.toml
mcf/LICENSE-APACHE
mcf/LICENSE-MIT
mcf/README.md
mcf/src/lib.rs
mcf/tests/mcf.rs

Initial implementation of the MCF pseudo-format as described at: https://passlib.readthedocs.io/en/stable/modular_crypt_format.html
Note that MCF is less a specification than an ad hoc set of conventions.
As MCF lacks the kind of rigidly specified sizes of its various components, a heapless `no_std` implementation isn't really possible like it is with the PHC format, and so this implementation has a hard dependency on `alloc` (though it should be possible to extract an `alloc`-free reference type which borrows from its input).

mcf: Modular Crypt Format implementation

---

mcf/Cargo.toml
mcf/README.md
mcf/src/fields.rs
mcf/src/lib.rs
mcf/tests/mcf.rs

Support for using the `Fields`/`Field` types in heapless environments.
Ideally we'd support something like `McfHashRef` for parsing MCF from a `str` input, but this PR doesn't add that for now.

mcf: introduce basic no-`alloc` profile

---

Cargo.lock
mcf/Cargo.toml
mcf/src/base64.rs
mcf/src/error.rs
mcf/src/fields.rs
mcf/src/lib.rs
mcf/tests/mcf.rs

Adds a `Base64` enum with variants for `Bcrypt`, `Crypt`, and `ShaCrypt`, i.e. the non-standard Base64 variants used in MCF hashes.
This is extracted from `password_hash::Encoding` which was straddling the line between the PHC format and MCF with such a feature. That type can now be removed in the next breaking release.

mcf: Base64 decoding support

---

mcf/src/lib.rs
mcf/tests/mcf.rs

Support for pushing additional fields onto an MCF hash string:
- `push_field`: pushes a `Field`
- `push_field_base64`: encodes a `&[u8]` using the given Base64 alphabet

mcf: add `push_field*` methods to `McfHash`

---

mcf/src/lib.rs
mcf/tests/mcf.rs

Simplifies constructing MCF hashes starting with a leading identifier.
Also removes the previous logic for mandating at least one field, instead changing it to disallowing trailing `$`

mcf: add `McfHash::from_id`

---

mcf/src/fields.rs
mcf/src/lib.rs

Adds a reference type for MCF hashes which works in no-`alloc` environments.
Some methods of `McfHash` are now directly delegated. It would be possible to make a fully borrowed reference type that works like `&McfHashRef`, which could be used with the standard `AsRef`/`Borrow`/`Deref` `ToOwned` traits, but it would require unsafe code, which this avoids for the time being.

mcf: add `McfHashRef`

---

der/src/asn1/application.rs
der/src/asn1/context_specific.rs
der/src/asn1/integer/int.rs
der/src/asn1/integer/uint.rs
der/src/asn1/internal_macros.rs
der/src/asn1/octet_string.rs
der/src/asn1/private.rs
der/src/bytes.rs
der/src/length/indefinite.rs

Ignores `the encoding shall be constructed if the base encoding is constructed` when using BER.
Issue reported in #779

der: fix BER `IMPLICIT` constructed octet string

---

Cargo.lock
Cargo.toml
pkcs1/Cargo.toml
pkcs1/src/error.rs
pkcs1/src/lib.rs
pkcs1/src/traits.rs
sec1/Cargo.toml
sec1/src/error.rs
sec1/src/lib.rs
sec1/src/traits.rs
x509-ocsp/Cargo.toml

Both `pkcs1` and `sec1` used some "clever" tricks to write blanket impls of their traits for any types which impl the `pkcs8` traits.
However, we've received some complaints this makes the impls of these traits more confusing and less discoverable (#1611), and adds a maintenance burden in that the blanket impl relationship is fundamentally "backwards" in that PKCS#8 builds on PKCS#1 and SEC1, not the other way around.
These could potentially be replaced with a macro that writes impls of the `pkcs8` traits for types which impl the `pkcs1`/`sec1` traits. However, for now, each of these is only used in one place (i.e. the `rsa` and `elliptic-curve` crates respectively), so we can start by moving the relevant code there for now.

pkcs1+sec1: remove `pkcs8` integration/feature

---

pkcs1/Cargo.toml

pkcs1: remove stub `pkcs8` feature

---

Cargo.lock
cmpv2/Cargo.toml
cms/Cargo.toml
crmf/Cargo.toml
der/Cargo.toml
gss-api/Cargo.toml
pkcs1/Cargo.toml
pkcs12/Cargo.toml
pkcs5/Cargo.toml
pkcs8/Cargo.toml
sec1/Cargo.toml
spki/Cargo.toml
x509-cert/Cargo.toml
x509-ocsp/Cargo.toml
x509-tsp/Cargo.toml

Releases the following:
- `der` v0.8.0-rc.7
- `pkcs1` v0.8.0-rc.3
- `pkcs5` v0.8.0-rc.6
- `pkcs8` v0.11.0-rc.6
- `sec1` v0.8.0-rc.8
- `spki` v0.8.0-rc.4

Cut new prereleases

---

base64ct/benches/mod.rs

Fixes:
```
running 3 tests
test decode_bench          ... FAILED
thread 'main' panicked at base64ct/benches/mod.rs:35:63:
called `Result::unwrap()` on an `Err` value: InvalidEncoding
```

base64ct: fix benchmarks

---

der/src/tag.rs

This does not include full support for relative OIDs, but allows for creating and encoding objects that contain relative OID from the raw bytes. For example, we can now create an `RdnSequence` as follows:
```
let _ = RdnSequence::from(vec![RelativeDistinguishedName(
SetOfVec::from_iter([AttributeTypeAndValue {
oid: ObjectIdentifier::new_unwrap("1.3.6.1.4.1.44363.47.1"),
value: Any::new(Tag::RelativeOid, b"\x81\xfd\x59\x01".as_slice()).unwrap(),
}])
.unwrap(),
)]);
```

der: Add `Tag::RelativeOid`, fixes #1875

---

cms/Cargo.toml
der/Cargo.toml
der/src/asn1/octet_string.rs
der/src/bytes.rs
der/src/decode.rs
der/src/encoding_rules.rs
der/src/header.rs
der/src/length.rs
der/src/length/indefinite.rs
der/src/reader.rs
der/src/tag.rs

As noted in #1934, there is noticeable performance impact of adding `indefinite: bool` field to `Length`.
This PR allows to disable BER decoder.

der: add `ber` feature

---

der/src/asn1/application.rs
der/src/asn1/context_specific.rs
der/src/asn1/internal_macros.rs
der/src/asn1/private.rs
der/src/bytes.rs
der/src/encoding_rules.rs
der/src/tag.rs

Adds `is_ber` and `is_der` to simplify these predicates and avoid having to import `EncodingRules`

der: add predicate methods to `EncodingRules`

---

cms/src/signed_data.rs

This one is a bit problematic, the [RFC] would read the `SignerIdentifier` is to reuse the `SubjectKeyIdentifier` (SKI) for X.509 exclusively:
```
sid specifies the signer's certificate (and thereby the signer's
public key).  The signer's public key is needed by the recipient
to verify the signature.  SignerIdentifier provides two
alternatives for specifying the signer's public key.  The
issuerAndSerialNumber alternative identifies the signer's
certificate by the issuer's distinguished name and the certificate
serial number; the subjectKeyIdentifier identifies the signer's
certificate by a key identifier.  When an X.509 certificate is
referenced, the key identifier matches the X.509
subjectKeyIdentifier extension value.  When other certificate
formats are referenced, the documents that …
```

cms: impl From<Certificate> for SignerIdentifier

---

der/src/asn1/ia5_string.rs
der/src/string.rs

As previously cleared in #1971, this simple PR adds `std::hash::Hash` derives to `Ia5String` and `StringOwned`. `StringOwned` requires `Hash`, because it is used in `Ia5String`.

der: add `Hash` derive for `StringOwned` and `Ia5String`

---

Cargo.lock
Cargo.toml
der/src/asn1/any.rs
der/src/asn1/bit_string.rs
der/src/asn1/bmp_string.rs
der/src/asn1/boolean.rs
der/src/asn1/generalized_time.rs
der/src/asn1/integer/int.rs
der/src/asn1/integer/uint.rs
der/src/asn1/internal_macros.rs
der/src/asn1/null.rs
der/src/asn1/octet_string.rs
der/src/asn1/oid.rs
der/src/asn1/real.rs
der/src/asn1/utc_time.rs
der/src/asn1/utf8_string.rs
der/src/bytes.rs
der/src/decode.rs
der/src/document.rs
der/src/encode.rs
der/src/header.rs
der/src/length/indefinite.rs
der/src/reader.rs
der/src/writer/slice.rs
pkcs5/src/pbes2/kdf/salt.rs
x509-cert/src/ext/pkix/name/dirstr.rs

Ensure octet strings with constructed, definite-length method return an error, rather than an incorrect decoding.

Negative test case for constructed, definite-length octet string

---

cms/src/builder.rs

This reuses the logic already implemented in `x509_cert::time::Time` instead of duplicating it.

cms: simplify `create_signing_time`

---

cms/src/builder.rs

When producing a document with inline content, the Content-Type comparison would compared against the oid of the attribute and not its value.

cms: fixup content-type comparison

---

cms/src/lib.rs
cms/src/symmetric_key.rs

Implementation of types as defined in [RFC 6031](https://datatracker.ietf.org/doc/html/rfc6031#section-2)
- I've used `Utf8StringRef` in the types that require an ASN.1 UTF8String, would it be preferable to have the structs own this data and use the `String` type instead?
- const-oid seems to generate relevantt oids by parsing RFC documents, should I therefore add the RFC-6031.txt file to the ones already present in oidbindgen?

cms: Implement types from RFC 6031 - Cryptographic Message Syntax (CMS) Symmetric Key Package Content Type

---

.github/workflows/cmpv2.yml
.github/workflows/cms.yml
.github/workflows/crmf.yml
.github/workflows/gss-api.yml
.github/workflows/x509-cert.yml
.github/workflows/x509-ocsp.yml
.github/workflows/x509-tsp.yml
Cargo.lock
Cargo.toml.orig
Cargo.toml.rej
der/Cargo.toml
der_derive/Cargo.toml

- `der` v0.8.0-rc-8
- `der_derive` v0.8.0-rc.4
This splits the workspace temporarily to get over the API break of der.

der/der_derive: cut new prereleases

---

cms/tests/signed_data.rs
der_derive/src/asn1_type.rs
der_derive/src/attributes.rs
der_derive/src/choice.rs
der_derive/src/choice/variant.rs
x509-cert/src/ext/pkix/name/dirstr.rs
x509-cert/src/time.rs

To deserialize SigningTime attributes from CMS, Time needs implement DecodeValue.
```
-- rfc3852
Attribute ::= SEQUENCE {
attrType OBJECT IDENTIFIER,
attrValues SET OF AttributeValue }
AttributeValue ::= ANY
-- rfc5911
SigningTime  ::= Time
Time ::= CHOICE {
utcTime UTCTime,
generalTime GeneralizedTime }
aa-signingTime ATTRIBUTE ::=
{ TYPE SigningTime IDENTIFIED BY id-signingTime }
id-signingTime OBJECT IDENTIFIER ::= { iso(1) member-body(2)
us(840) rsadsi(113549) pkcs(1) pkcs9(9) 5 }
```
This adds the missing implementation.

x509-cert: impl `DecodeValue` for `Time`

---

Cargo.lock
x509-cert/Cargo.toml

Not sure why dependabot hasn’t proposed this yet, but I’m preparing to patch the `rstest` dev-dependency [downstream in Fedora](https://src.fedoraproject.org/rpms/rust-x509-cert), so this PR suggests the same change upstream.
I verified that `cargo test` still passes in `x509-cert/`, and I didn’t see anything in https://github.com/la10736/rstest/blob/v0.26.1/CHANGELOG.md that seemed like it should impact this project.

chore(deps): bump rstest from 0.25.0 to 0.26.1

---

cms/Cargo.toml

Followup to https://github.com/RustCrypto/formats/pull/1968 which did not enable std on `x509-cert` that's required to access `Time::now`

cms: propagate std feature to x509-cert

---

base16ct/README.md
base32ct/README.md
base64ct/README.md
mcf/README.md
serdect/README.md
tai64/README.md

Add info about new MSRV policy to crates we can imminently release

---

Cargo.lock
base16ct/CHANGELOG.md
base16ct/Cargo.toml

- Upgrade to 2024 edition; MSRV 1.85 ([#1670])
- Use `core::error:Error` ([#1842])
- `std` feature ([#2004])
[#1670]: https://github.com/RustCrypto/formats/pull/1670
[#1842]: https://github.com/RustCrypto/formats/pull/1842
[#2004]: https://github.com/RustCrypto/formats/pull/2004

base16ct v0.3.0

---

.github/workflows/base32ct.yml
Cargo.lock
base32ct/Cargo.toml
base32ct/src/error.rs
base32ct/src/lib.rs

The only reason we had a `std` feature was for `std::error::Error`, but now the trait is available in `core`

base32ct: remove `std` feature; use `core::error::Error`

---

Cargo.lock
serdect/CHANGELOG.md
serdect/Cargo.toml

- Bump `base16ct` to v0.3 ([#2017])
[#2017]: https://github.com/RustCrypto/formats/pull/2017

serdect v0.4.1

---

Cargo.lock
sec1/Cargo.toml

Includes `hybrid-array` v0.4 support

sec1 v0.8.0-rc.9

---

mcf/src/base64.rs

This reverts commit 731509599473441f91897314a482d1905b8d07f3 (#2025)
Though it confused me, the original text is correct about the ordering.

Revert "mcf: improve Base64 comments"

---

mcf/src/lib.rs

Adds impls for converting both `McfHash` and `McfHashRef` to/from `&str`

mcf: add `(Try)From` impls for `McfHashRef` and `&str`

---

Cargo.lock
mcf/Cargo.toml
mcf/src/lib.rs
mcf/tests/mcf.rs

Slightly shorter and matches the other methods, also it doesn't act on a `Field` type so the old name was slightly confusing.

mcf: rename `McfHash::push_field_base64` to `McfHash::push_base64`

---

mcf/src/lib.rs
mcf/tests/mcf.rs

Renames the following:
- `McfHash` => `PasswordHash`
- `McfHashRef` => `PasswordHashRef`
This makes it much clearer the types represent password hash strings

mcf: rename `PasswordHash`/`PasswordHashRef`

---

Cargo.lock
mcf/CHANGELOG.md
mcf/Cargo.toml

- `(Try)From` impls for `PasswordHash` <=> `String` ([#2027])
- `(Try)From` impls for `PasswordHashRef` and `&str` ([#2028])
- `PasswordHash::push_str` ([#2029])
- Rename `McfHash::push_field_base64` to `McfHash::push_base64` ([#2030])
- Rename `McfHash` => `PasswordHash` ([#2031])
- Rename `McfHashRef` => `PasswordHashRef` ([#2031])
- Make `base64` an optional (on-by-default) feature ([#2032])
[#2027]: https://github.com/RustCrypto/formats/pull/2027
[#2028]: https://github.com/RustCrypto/formats/pull/2028
[#2029]: https://github.com/RustCrypto/formats/pull/2029
[#2030]: https://github.com/RustCrypto/formats/pull/2030
[#2031]: https://github.com/RustCrypto/formats/pull/2031
[#2032]: https://github.com/RustCrypto/formats/pull/2032

mcf v0.2.0

---

cms/src/attr.rs
cms/src/timestamped_data.rs
cms/tests/builder.rs
cms/tests/tests_from_pkcs7_crate.rs
der/src/asn1.rs
der/src/asn1/octet_string.rs
der/src/bytes.rs
der_derive/src/asn1_type.rs
gss-api/src/negotiation.rs
pkcs1/src/private_key.rs
pkcs1/tests/params.rs
pkcs5/src/pbes1.rs
pkcs5/src/pbes2.rs
pkcs8/src/encrypted_private_key_info.rs
pkcs8/src/lib.rs
pkcs8/src/private_key_info.rs
sec1/src/private_key.rs
x509-cert/tests/name.rs

Following the pattern of #1921, removes the lifetime from the struct, instead changing `OctetStringRef` to a proper reference type to be used as `&OctetStringRef`.
This makes it possible to `impl Borrow<OctetStringRef> for OctetString` and `impl ToOwned for OctetStringRef`, so they can work with `Cow`.
cc @dishmaker

der: remove lifetime from `OctetStringRef`

---

Cargo.lock
cmpv2/Cargo.toml
cms/Cargo.toml
crmf/Cargo.toml
der/Cargo.toml
der_derive/Cargo.toml
gss-api/Cargo.toml
pkcs1/Cargo.toml
pkcs12/Cargo.toml
pkcs5/Cargo.toml
pkcs8/Cargo.toml
sec1/Cargo.toml
spki/Cargo.toml
x509-cert/Cargo.toml
x509-ocsp/Cargo.toml
x509-tsp/Cargo.toml

Also releases: `der_derive` v0.8.0-rc.5

der v0.8.0-rc.9

---

der/src/decode.rs
der/src/encode.rs

der: improve docs for `Encode` and `Decode`
